import type { VocabWordBase } from "../german-types";

export const EXPANDED_ADJECTIVES: VocabWordBase[] = [
  // ─── Size & Shape ───────────────────────────────────────────────
  { german: "breit", english: "wide, broad", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Straße ist sehr breit.", exampleEn: "The street is very wide." },
  { german: "schmal", english: "narrow", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Weg ist zu schmal für das Auto.", exampleEn: "The path is too narrow for the car." },
  { german: "dick", english: "thick, fat", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Buch ist sehr dick.", exampleEn: "The book is very thick." },
  { german: "dünn", english: "thin", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Eis ist zu dünn.", exampleEn: "The ice is too thin." },
  { german: "hoch", english: "high, tall", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Berg ist sehr hoch.", exampleEn: "The mountain is very high." },
  { german: "tief", english: "deep", partOfSpeech: "adjective", category: "Size & Shape", example: "Der See ist sehr tief.", exampleEn: "The lake is very deep." },
  { german: "flach", english: "flat", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Land hier ist sehr flach.", exampleEn: "The land here is very flat." },
  { german: "rund", english: "round", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Tisch ist rund.", exampleEn: "The table is round." },
  { german: "eckig", english: "angular, square", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Box ist eckig.", exampleEn: "The box is angular." },
  { german: "eng", english: "tight, narrow", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Hose ist mir zu eng.", exampleEn: "The pants are too tight for me." },
  { german: "weit", english: "wide, far", partOfSpeech: "adjective", category: "Size & Shape", example: "Das T-Shirt ist mir zu weit.", exampleEn: "The T-shirt is too wide for me." },
  { german: "riesig", english: "huge, enormous", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Gebäude ist riesig.", exampleEn: "The building is huge." },
  { german: "winzig", english: "tiny", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Wohnung ist winzig.", exampleEn: "The apartment is tiny." },
  { german: "massiv", english: "massive, solid", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Tisch ist aus massivem Holz.", exampleEn: "The table is made of solid wood." },
  { german: "oval", english: "oval", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Spiegel ist oval.", exampleEn: "The mirror is oval." },
  { german: "spitz", english: "pointed, sharp", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Messer ist sehr spitz.", exampleEn: "The knife is very pointed." },
  { german: "steil", english: "steep", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Weg ist sehr steil.", exampleEn: "The path is very steep." },
  { german: "gerade", english: "straight", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Linie ist gerade.", exampleEn: "The line is straight." },
  { german: "krumm", english: "crooked, bent", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Nagel ist krumm.", exampleEn: "The nail is bent." },
  { german: "gewaltig", english: "enormous, tremendous", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Unterschied ist gewaltig.", exampleEn: "The difference is enormous." },
  { german: "kompakt", english: "compact", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Auto ist sehr kompakt.", exampleEn: "The car is very compact." },
  { german: "glatt", english: "smooth", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Straße ist glatt im Winter.", exampleEn: "The road is smooth (slippery) in winter." },
  { german: "rau", english: "rough", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Oberfläche ist rau.", exampleEn: "The surface is rough." },
  { german: "schräg", english: "slanted, diagonal", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Bild hängt schräg.", exampleEn: "The picture hangs crooked." },

  // ─── Color ──────────────────────────────────────────────────────
  { german: "rot", english: "red", partOfSpeech: "adjective", category: "Color", example: "Die Rose ist rot.", exampleEn: "The rose is red." },
  { german: "blau", english: "blue", partOfSpeech: "adjective", category: "Color", example: "Der Himmel ist blau.", exampleEn: "The sky is blue." },
  { german: "grün", english: "green", partOfSpeech: "adjective", category: "Color", example: "Das Gras ist grün.", exampleEn: "The grass is green." },
  { german: "gelb", english: "yellow", partOfSpeech: "adjective", category: "Color", example: "Die Sonne ist gelb.", exampleEn: "The sun is yellow." },
  { german: "schwarz", english: "black", partOfSpeech: "adjective", category: "Color", example: "Die Katze ist schwarz.", exampleEn: "The cat is black." },
  { german: "weiß", english: "white", partOfSpeech: "adjective", category: "Color", example: "Der Schnee ist weiß.", exampleEn: "The snow is white." },
  { german: "grau", english: "gray", partOfSpeech: "adjective", category: "Color", example: "Der Himmel ist heute grau.", exampleEn: "The sky is gray today." },
  { german: "braun", english: "brown", partOfSpeech: "adjective", category: "Color", example: "Der Hund ist braun.", exampleEn: "The dog is brown." },
  { german: "rosa", english: "pink", partOfSpeech: "adjective", category: "Color", example: "Ihr Kleid ist rosa.", exampleEn: "Her dress is pink." },
  { german: "lila", english: "purple", partOfSpeech: "adjective", category: "Color", example: "Die Blumen sind lila.", exampleEn: "The flowers are purple." },
  { german: "orange", english: "orange", partOfSpeech: "adjective", category: "Color", example: "Der Kürbis ist orange.", exampleEn: "The pumpkin is orange." },
  { german: "silbern", english: "silver", partOfSpeech: "adjective", category: "Color", example: "Der Ring ist silbern.", exampleEn: "The ring is silver." },
  { german: "golden", english: "golden", partOfSpeech: "adjective", category: "Color", example: "Die Kette ist golden.", exampleEn: "The necklace is golden." },
  { german: "dunkel", english: "dark", partOfSpeech: "adjective", category: "Color", example: "Das Zimmer ist dunkel.", exampleEn: "The room is dark." },
  { german: "hell", english: "light, bright", partOfSpeech: "adjective", category: "Color", example: "Die Farbe ist hell.", exampleEn: "The color is light." },
  { german: "bunt", english: "colorful", partOfSpeech: "adjective", category: "Color", example: "Die Blumen sind bunt.", exampleEn: "The flowers are colorful." },
  { german: "blass", english: "pale", partOfSpeech: "adjective", category: "Color", example: "Du siehst heute blass aus.", exampleEn: "You look pale today." },
  { german: "türkis", english: "turquoise", partOfSpeech: "adjective", category: "Color", example: "Das Meer ist türkis.", exampleEn: "The sea is turquoise." },
  { german: "beige", english: "beige", partOfSpeech: "adjective", category: "Color", example: "Die Wand ist beige.", exampleEn: "The wall is beige." },
  { german: "violett", english: "violet", partOfSpeech: "adjective", category: "Color", example: "Der Pullover ist violett.", exampleEn: "The sweater is violet." },

  // ─── Personality ────────────────────────────────────────────────
  { german: "freundlich", english: "friendly", partOfSpeech: "adjective", category: "Personality", example: "Die Nachbarn sind sehr freundlich.", exampleEn: "The neighbors are very friendly." },
  { german: "nett", english: "nice, kind", partOfSpeech: "adjective", category: "Personality", example: "Er ist ein netter Mensch.", exampleEn: "He is a nice person." },
  { german: "ehrlich", english: "honest", partOfSpeech: "adjective", category: "Personality", example: "Sie ist immer ehrlich.", exampleEn: "She is always honest." },
  { german: "mutig", english: "brave, courageous", partOfSpeech: "adjective", category: "Personality", example: "Das Kind ist sehr mutig.", exampleEn: "The child is very brave." },
  { german: "faul", english: "lazy", partOfSpeech: "adjective", category: "Personality", example: "Die Katze ist faul.", exampleEn: "The cat is lazy." },
  { german: "fleißig", english: "hardworking, diligent", partOfSpeech: "adjective", category: "Personality", example: "Die Schüler sind fleißig.", exampleEn: "The students are hardworking." },
  { german: "geduldig", english: "patient", partOfSpeech: "adjective", category: "Personality", example: "Der Lehrer ist sehr geduldig.", exampleEn: "The teacher is very patient." },
  { german: "ungeduldig", english: "impatient", partOfSpeech: "adjective", category: "Personality", example: "Er wird schnell ungeduldig.", exampleEn: "He quickly becomes impatient." },
  { german: "neugierig", english: "curious", partOfSpeech: "adjective", category: "Personality", example: "Kinder sind immer neugierig.", exampleEn: "Children are always curious." },
  { german: "schüchtern", english: "shy", partOfSpeech: "adjective", category: "Personality", example: "Das Mädchen ist schüchtern.", exampleEn: "The girl is shy." },
  { german: "selbstbewusst", english: "confident, self-assured", partOfSpeech: "adjective", category: "Personality", example: "Sie ist eine selbstbewusste Frau.", exampleEn: "She is a confident woman." },
  { german: "klug", english: "clever, smart", partOfSpeech: "adjective", category: "Personality", example: "Er ist ein kluger Junge.", exampleEn: "He is a clever boy." },
  { german: "dumm", english: "stupid, dumb", partOfSpeech: "adjective", category: "Personality", example: "Das war eine dumme Idee.", exampleEn: "That was a stupid idea." },
  { german: "lustig", english: "funny", partOfSpeech: "adjective", category: "Personality", example: "Der Film war sehr lustig.", exampleEn: "The movie was very funny." },
  { german: "ernst", english: "serious", partOfSpeech: "adjective", category: "Personality", example: "Er ist ein ernster Mensch.", exampleEn: "He is a serious person." },
  { german: "höflich", english: "polite", partOfSpeech: "adjective", category: "Personality", example: "Die Kellnerin war sehr höflich.", exampleEn: "The waitress was very polite." },
  { german: "unhöflich", english: "rude, impolite", partOfSpeech: "adjective", category: "Personality", example: "Sein Verhalten war unhöflich.", exampleEn: "His behavior was rude." },
  { german: "großzügig", english: "generous", partOfSpeech: "adjective", category: "Personality", example: "Meine Oma ist sehr großzügig.", exampleEn: "My grandma is very generous." },
  { german: "geizig", english: "stingy, miserly", partOfSpeech: "adjective", category: "Personality", example: "Er ist zu geizig, um Trinkgeld zu geben.", exampleEn: "He is too stingy to tip." },
  { german: "verantwortungsvoll", english: "responsible", partOfSpeech: "adjective", category: "Personality", example: "Sie ist eine verantwortungsvolle Mutter.", exampleEn: "She is a responsible mother." },
  { german: "zuverlässig", english: "reliable", partOfSpeech: "adjective", category: "Personality", example: "Er ist ein zuverlässiger Freund.", exampleEn: "He is a reliable friend." },
  { german: "stur", english: "stubborn", partOfSpeech: "adjective", category: "Personality", example: "Mein Bruder ist manchmal stur.", exampleEn: "My brother is sometimes stubborn." },
  { german: "offen", english: "open, open-minded", partOfSpeech: "adjective", category: "Personality", example: "Sie ist offen für neue Ideen.", exampleEn: "She is open to new ideas." },
  { german: "bescheiden", english: "modest, humble", partOfSpeech: "adjective", category: "Personality", example: "Trotz seines Erfolgs ist er bescheiden.", exampleEn: "Despite his success, he is modest." },
  { german: "arrogant", english: "arrogant", partOfSpeech: "adjective", category: "Personality", example: "Der Chef ist manchmal arrogant.", exampleEn: "The boss is sometimes arrogant." },
  { german: "treu", english: "loyal, faithful", partOfSpeech: "adjective", category: "Personality", example: "Der Hund ist seinem Besitzer treu.", exampleEn: "The dog is loyal to its owner." },
  { german: "eifersüchtig", english: "jealous", partOfSpeech: "adjective", category: "Personality", example: "Er ist eifersüchtig auf seinen Bruder.", exampleEn: "He is jealous of his brother." },
  { german: "streng", english: "strict", partOfSpeech: "adjective", category: "Personality", example: "Die Lehrerin ist streng aber fair.", exampleEn: "The teacher is strict but fair." },
  { german: "hilfsbereit", english: "helpful", partOfSpeech: "adjective", category: "Personality", example: "Die Mitarbeiter sind sehr hilfsbereit.", exampleEn: "The employees are very helpful." },
  { german: "humorvoll", english: "humorous", partOfSpeech: "adjective", category: "Personality", example: "Sie ist eine humorvolle Person.", exampleEn: "She is a humorous person." },
  { german: "intelligent", english: "intelligent", partOfSpeech: "adjective", category: "Personality", example: "Er ist ein intelligenter Schüler.", exampleEn: "He is an intelligent student." },
  { german: "kreativ", english: "creative", partOfSpeech: "adjective", category: "Personality", example: "Sie ist eine kreative Künstlerin.", exampleEn: "She is a creative artist." },
  { german: "sensibel", english: "sensitive", partOfSpeech: "adjective", category: "Personality", example: "Er ist ein sensibler Mensch.", exampleEn: "He is a sensitive person." },
  { german: "abenteuerlustig", english: "adventurous", partOfSpeech: "adjective", category: "Personality", example: "Sie ist sehr abenteuerlustig.", exampleEn: "She is very adventurous." },
  { german: "optimistisch", english: "optimistic", partOfSpeech: "adjective", category: "Personality", example: "Er bleibt immer optimistisch.", exampleEn: "He always stays optimistic." },
  { german: "pessimistisch", english: "pessimistic", partOfSpeech: "adjective", category: "Personality", example: "Sie ist manchmal pessimistisch.", exampleEn: "She is sometimes pessimistic." },
  { german: "nachdenklich", english: "thoughtful, reflective", partOfSpeech: "adjective", category: "Personality", example: "Er wirkt heute nachdenklich.", exampleEn: "He seems thoughtful today." },
  { german: "aufmerksam", english: "attentive", partOfSpeech: "adjective", category: "Personality", example: "Die Schüler sind aufmerksam.", exampleEn: "The students are attentive." },
  { german: "respektvoll", english: "respectful", partOfSpeech: "adjective", category: "Personality", example: "Die Kinder sind respektvoll.", exampleEn: "The children are respectful." },
  { german: "gemein", english: "mean", partOfSpeech: "adjective", category: "Personality", example: "Das war gemein von dir.", exampleEn: "That was mean of you." },
  { german: "gesellig", english: "sociable", partOfSpeech: "adjective", category: "Personality", example: "Er ist ein geselliger Mensch.", exampleEn: "He is a sociable person." },
  { german: "ehrgeizig", english: "ambitious", partOfSpeech: "adjective", category: "Personality", example: "Sie ist eine ehrgeizige Studentin.", exampleEn: "She is an ambitious student." },
  { german: "tapfer", english: "brave, valiant", partOfSpeech: "adjective", category: "Personality", example: "Der Soldat war sehr tapfer.", exampleEn: "The soldier was very brave." },
  { german: "weise", english: "wise", partOfSpeech: "adjective", category: "Personality", example: "Mein Großvater ist ein weiser Mann.", exampleEn: "My grandfather is a wise man." },
  { german: "liebevoll", english: "loving, affectionate", partOfSpeech: "adjective", category: "Personality", example: "Sie ist eine liebevolle Mutter.", exampleEn: "She is a loving mother." },

  // ─── Emotion ────────────────────────────────────────────────────
  { german: "glücklich", english: "happy", partOfSpeech: "adjective", category: "Emotion", example: "Ich bin heute sehr glücklich.", exampleEn: "I am very happy today." },
  { german: "traurig", english: "sad", partOfSpeech: "adjective", category: "Emotion", example: "Sie ist traurig, weil ihr Hund krank ist.", exampleEn: "She is sad because her dog is sick." },
  { german: "wütend", english: "angry, furious", partOfSpeech: "adjective", category: "Emotion", example: "Er ist wütend auf seinen Bruder.", exampleEn: "He is angry at his brother." },
  { german: "ängstlich", english: "anxious, fearful", partOfSpeech: "adjective", category: "Emotion", example: "Das Kind ist ängstlich im Dunkeln.", exampleEn: "The child is anxious in the dark." },
  { german: "froh", english: "glad, happy", partOfSpeech: "adjective", category: "Emotion", example: "Ich bin froh, dass du da bist.", exampleEn: "I am glad that you are here." },
  { german: "zufrieden", english: "satisfied, content", partOfSpeech: "adjective", category: "Emotion", example: "Er ist mit seiner Arbeit zufrieden.", exampleEn: "He is satisfied with his work." },
  { german: "enttäuscht", english: "disappointed", partOfSpeech: "adjective", category: "Emotion", example: "Sie ist enttäuscht von dem Ergebnis.", exampleEn: "She is disappointed with the result." },
  { german: "überrascht", english: "surprised", partOfSpeech: "adjective", category: "Emotion", example: "Wir waren überrascht von der Nachricht.", exampleEn: "We were surprised by the news." },
  { german: "besorgt", english: "worried, concerned", partOfSpeech: "adjective", category: "Emotion", example: "Die Eltern sind besorgt.", exampleEn: "The parents are worried." },
  { german: "nervös", english: "nervous", partOfSpeech: "adjective", category: "Emotion", example: "Ich bin nervös vor der Prüfung.", exampleEn: "I am nervous before the exam." },
  { german: "aufgeregt", english: "excited", partOfSpeech: "adjective", category: "Emotion", example: "Die Kinder sind aufgeregt wegen der Reise.", exampleEn: "The children are excited about the trip." },
  { german: "gelangweilt", english: "bored", partOfSpeech: "adjective", category: "Emotion", example: "Die Schüler sind gelangweilt.", exampleEn: "The students are bored." },
  { german: "stolz", english: "proud", partOfSpeech: "adjective", category: "Emotion", example: "Die Eltern sind stolz auf ihre Tochter.", exampleEn: "The parents are proud of their daughter." },
  { german: "einsam", english: "lonely", partOfSpeech: "adjective", category: "Emotion", example: "Er fühlt sich einsam.", exampleEn: "He feels lonely." },
  { german: "verliebt", english: "in love", partOfSpeech: "adjective", category: "Emotion", example: "Sie ist verliebt in ihn.", exampleEn: "She is in love with him." },
  { german: "dankbar", english: "grateful, thankful", partOfSpeech: "adjective", category: "Emotion", example: "Ich bin dankbar für deine Hilfe.", exampleEn: "I am grateful for your help." },
  { german: "neidisch", english: "envious", partOfSpeech: "adjective", category: "Emotion", example: "Er ist neidisch auf seinen Kollegen.", exampleEn: "He is envious of his colleague." },
  { german: "frustriert", english: "frustrated", partOfSpeech: "adjective", category: "Emotion", example: "Sie ist frustriert mit der Situation.", exampleEn: "She is frustrated with the situation." },
  { german: "erschrocken", english: "frightened, startled", partOfSpeech: "adjective", category: "Emotion", example: "Das Kind war erschrocken.", exampleEn: "The child was frightened." },
  { german: "verzweifelt", english: "desperate", partOfSpeech: "adjective", category: "Emotion", example: "Er war verzweifelt nach dem Verlust.", exampleEn: "He was desperate after the loss." },
  { german: "erleichtert", english: "relieved", partOfSpeech: "adjective", category: "Emotion", example: "Sie war erleichtert nach der Prüfung.", exampleEn: "She was relieved after the exam." },
  { german: "begeistert", english: "enthusiastic, thrilled", partOfSpeech: "adjective", category: "Emotion", example: "Er ist begeistert von der Idee.", exampleEn: "He is thrilled by the idea." },
  { german: "verärgert", english: "annoyed, upset", partOfSpeech: "adjective", category: "Emotion", example: "Sie ist verärgert über die Verspätung.", exampleEn: "She is annoyed about the delay." },
  { german: "peinlich", english: "embarrassing", partOfSpeech: "adjective", category: "Emotion", example: "Die Situation war peinlich.", exampleEn: "The situation was embarrassing." },
  { german: "schockiert", english: "shocked", partOfSpeech: "adjective", category: "Emotion", example: "Wir waren schockiert von der Nachricht.", exampleEn: "We were shocked by the news." },
  { german: "gerührt", english: "moved, touched", partOfSpeech: "adjective", category: "Emotion", example: "Sie war gerührt von dem Geschenk.", exampleEn: "She was moved by the gift." },
  { german: "hoffnungsvoll", english: "hopeful", partOfSpeech: "adjective", category: "Emotion", example: "Er ist hoffnungsvoll für die Zukunft.", exampleEn: "He is hopeful for the future." },
  { german: "nostalgisch", english: "nostalgic", partOfSpeech: "adjective", category: "Emotion", example: "Das Lied macht mich nostalgisch.", exampleEn: "The song makes me nostalgic." },
  { german: "panisch", english: "panicked", partOfSpeech: "adjective", category: "Emotion", example: "Die Leute wurden panisch.", exampleEn: "The people became panicked." },
  { german: "entspannt", english: "relaxed", partOfSpeech: "adjective", category: "Emotion", example: "Am Wochenende bin ich entspannt.", exampleEn: "On the weekend I am relaxed." },
  { german: "genervt", english: "annoyed, irritated", partOfSpeech: "adjective", category: "Emotion", example: "Er ist genervt von dem Lärm.", exampleEn: "He is annoyed by the noise." },
  { german: "verwirrt", english: "confused", partOfSpeech: "adjective", category: "Emotion", example: "Ich bin verwirrt von der Aufgabe.", exampleEn: "I am confused by the task." },
  { german: "gestresst", english: "stressed", partOfSpeech: "adjective", category: "Emotion", example: "Sie ist gestresst wegen der Arbeit.", exampleEn: "She is stressed because of work." },

  // ─── Quality ────────────────────────────────────────────────────
  { german: "perfekt", english: "perfect", partOfSpeech: "adjective", category: "Quality", example: "Das Wetter ist perfekt heute.", exampleEn: "The weather is perfect today." },
  { german: "ausgezeichnet", english: "excellent", partOfSpeech: "adjective", category: "Quality", example: "Das Essen war ausgezeichnet.", exampleEn: "The food was excellent." },
  { german: "wunderbar", english: "wonderful", partOfSpeech: "adjective", category: "Quality", example: "Der Urlaub war wunderbar.", exampleEn: "The vacation was wonderful." },
  { german: "schrecklich", english: "terrible, awful", partOfSpeech: "adjective", category: "Quality", example: "Das Wetter ist schrecklich.", exampleEn: "The weather is terrible." },
  { german: "furchtbar", english: "dreadful, awful", partOfSpeech: "adjective", category: "Quality", example: "Der Lärm ist furchtbar.", exampleEn: "The noise is dreadful." },
  { german: "sauber", english: "clean", partOfSpeech: "adjective", category: "Quality", example: "Das Zimmer ist sauber.", exampleEn: "The room is clean." },
  { german: "schmutzig", english: "dirty", partOfSpeech: "adjective", category: "Quality", example: "Die Schuhe sind schmutzig.", exampleEn: "The shoes are dirty." },
  { german: "frisch", english: "fresh", partOfSpeech: "adjective", category: "Quality", example: "Das Brot ist frisch.", exampleEn: "The bread is fresh." },
  { german: "trocken", english: "dry", partOfSpeech: "adjective", category: "Quality", example: "Die Wäsche ist schon trocken.", exampleEn: "The laundry is already dry." },
  { german: "nass", english: "wet", partOfSpeech: "adjective", category: "Quality", example: "Die Straßen sind nass vom Regen.", exampleEn: "The streets are wet from the rain." },
  { german: "weich", english: "soft", partOfSpeech: "adjective", category: "Quality", example: "Das Kissen ist sehr weich.", exampleEn: "The pillow is very soft." },
  { german: "hart", english: "hard", partOfSpeech: "adjective", category: "Quality", example: "Das Bett ist zu hart.", exampleEn: "The bed is too hard." },
  { german: "leer", english: "empty", partOfSpeech: "adjective", category: "Quality", example: "Die Flasche ist leer.", exampleEn: "The bottle is empty." },
  { german: "voll", english: "full", partOfSpeech: "adjective", category: "Quality", example: "Das Glas ist voll.", exampleEn: "The glass is full." },
  { german: "kaputt", english: "broken", partOfSpeech: "adjective", category: "Quality", example: "Mein Handy ist kaputt.", exampleEn: "My phone is broken." },
  { german: "laut", english: "loud", partOfSpeech: "adjective", category: "Quality", example: "Die Musik ist zu laut.", exampleEn: "The music is too loud." },
  { german: "leise", english: "quiet, soft", partOfSpeech: "adjective", category: "Quality", example: "Bitte sei leise im Krankenhaus.", exampleEn: "Please be quiet in the hospital." },
  { german: "hell", english: "bright", partOfSpeech: "adjective", category: "Quality", example: "Das Licht ist sehr hell.", exampleEn: "The light is very bright." },
  { german: "süß", english: "sweet", partOfSpeech: "adjective", category: "Quality", example: "Der Kuchen ist sehr süß.", exampleEn: "The cake is very sweet." },
  { german: "sauer", english: "sour", partOfSpeech: "adjective", category: "Quality", example: "Die Zitrone ist sauer.", exampleEn: "The lemon is sour." },
  { german: "bitter", english: "bitter", partOfSpeech: "adjective", category: "Quality", example: "Der Kaffee ist bitter.", exampleEn: "The coffee is bitter." },
  { german: "salzig", english: "salty", partOfSpeech: "adjective", category: "Quality", example: "Die Suppe ist zu salzig.", exampleEn: "The soup is too salty." },
  { german: "scharf", english: "spicy, sharp", partOfSpeech: "adjective", category: "Quality", example: "Das Essen ist sehr scharf.", exampleEn: "The food is very spicy." },
  { german: "lecker", english: "delicious, tasty", partOfSpeech: "adjective", category: "Quality", example: "Das Essen schmeckt lecker.", exampleEn: "The food tastes delicious." },
  { german: "eklig", english: "disgusting", partOfSpeech: "adjective", category: "Quality", example: "Das schmeckt eklig.", exampleEn: "That tastes disgusting." },
  { german: "praktisch", english: "practical", partOfSpeech: "adjective", category: "Quality", example: "Die Tasche ist sehr praktisch.", exampleEn: "The bag is very practical." },
  { german: "nützlich", english: "useful", partOfSpeech: "adjective", category: "Quality", example: "Das Buch ist sehr nützlich.", exampleEn: "The book is very useful." },
  { german: "nutzlos", english: "useless", partOfSpeech: "adjective", category: "Quality", example: "Dieses Werkzeug ist nutzlos.", exampleEn: "This tool is useless." },
  { german: "wertvoll", english: "valuable", partOfSpeech: "adjective", category: "Quality", example: "Der Ring ist sehr wertvoll.", exampleEn: "The ring is very valuable." },
  { german: "seltsam", english: "strange, odd", partOfSpeech: "adjective", category: "Quality", example: "Das ist eine seltsame Geschichte.", exampleEn: "That is a strange story." },
  { german: "normal", english: "normal", partOfSpeech: "adjective", category: "Quality", example: "Das ist völlig normal.", exampleEn: "That is completely normal." },
  { german: "typisch", english: "typical", partOfSpeech: "adjective", category: "Quality", example: "Das ist typisch deutsch.", exampleEn: "That is typically German." },
  { german: "besonder", english: "special, particular", partOfSpeech: "adjective", category: "Quality", example: "Das ist ein besonderer Tag.", exampleEn: "This is a special day." },
  { german: "einfach", english: "simple, easy", partOfSpeech: "adjective", category: "Quality", example: "Die Aufgabe ist einfach.", exampleEn: "The task is simple." },
  { german: "kompliziert", english: "complicated", partOfSpeech: "adjective", category: "Quality", example: "Die Situation ist kompliziert.", exampleEn: "The situation is complicated." },
  { german: "gefährlich", english: "dangerous", partOfSpeech: "adjective", category: "Quality", example: "Die Straße ist gefährlich bei Nacht.", exampleEn: "The street is dangerous at night." },
  { german: "sicher", english: "safe, secure", partOfSpeech: "adjective", category: "Quality", example: "Die Gegend ist sicher.", exampleEn: "The area is safe." },
  { german: "berühmt", english: "famous", partOfSpeech: "adjective", category: "Quality", example: "Der Sänger ist berühmt.", exampleEn: "The singer is famous." },
  { german: "bekannt", english: "known, well-known", partOfSpeech: "adjective", category: "Quality", example: "Das Restaurant ist bekannt für seine Pizza.", exampleEn: "The restaurant is known for its pizza." },
  { german: "unbekannt", english: "unknown", partOfSpeech: "adjective", category: "Quality", example: "Der Absender ist unbekannt.", exampleEn: "The sender is unknown." },
  { german: "beliebt", english: "popular", partOfSpeech: "adjective", category: "Quality", example: "Der Park ist bei Familien beliebt.", exampleEn: "The park is popular with families." },
  { german: "notwendig", english: "necessary", partOfSpeech: "adjective", category: "Quality", example: "Eine Reservierung ist notwendig.", exampleEn: "A reservation is necessary." },
  { german: "überflüssig", english: "unnecessary, superfluous", partOfSpeech: "adjective", category: "Quality", example: "Dieser Kommentar war überflüssig.", exampleEn: "That comment was unnecessary." },
  { german: "dringend", english: "urgent", partOfSpeech: "adjective", category: "Quality", example: "Es gibt ein dringendes Problem.", exampleEn: "There is an urgent problem." },
  { german: "pünktlich", english: "punctual, on time", partOfSpeech: "adjective", category: "Quality", example: "Der Zug ist pünktlich.", exampleEn: "The train is on time." },
  { german: "zerbrechlich", english: "fragile", partOfSpeech: "adjective", category: "Quality", example: "Das Glas ist zerbrechlich.", exampleEn: "The glass is fragile." },
  { german: "stabil", english: "stable, sturdy", partOfSpeech: "adjective", category: "Quality", example: "Der Tisch ist sehr stabil.", exampleEn: "The table is very sturdy." },
  { german: "echt", english: "real, genuine", partOfSpeech: "adjective", category: "Quality", example: "Ist die Tasche echt?", exampleEn: "Is the bag genuine?" },
  { german: "falsch", english: "fake, false", partOfSpeech: "adjective", category: "Quality", example: "Das ist eine falsche Banknote.", exampleEn: "That is a fake banknote." },
  { german: "original", english: "original", partOfSpeech: "adjective", category: "Quality", example: "Das ist das originale Gemälde.", exampleEn: "That is the original painting." },
  { german: "modern", english: "modern", partOfSpeech: "adjective", category: "Quality", example: "Die Küche ist sehr modern.", exampleEn: "The kitchen is very modern." },
  { german: "traditionell", english: "traditional", partOfSpeech: "adjective", category: "Quality", example: "Das ist ein traditionelles Gericht.", exampleEn: "That is a traditional dish." },
  { german: "natürlich", english: "natural", partOfSpeech: "adjective", category: "Quality", example: "Das Produkt ist natürlich.", exampleEn: "The product is natural." },
  { german: "künstlich", english: "artificial", partOfSpeech: "adjective", category: "Quality", example: "Das Licht ist künstlich.", exampleEn: "The light is artificial." },
  { german: "automatisch", english: "automatic", partOfSpeech: "adjective", category: "Quality", example: "Die Tür öffnet sich automatisch.", exampleEn: "The door opens automatically." },

  // ─── Temperature ────────────────────────────────────────────────
  { german: "warm", english: "warm", partOfSpeech: "adjective", category: "Temperature", example: "Das Wetter ist warm heute.", exampleEn: "The weather is warm today." },
  { german: "kühl", english: "cool", partOfSpeech: "adjective", category: "Temperature", example: "Die Nächte sind kühl im Herbst.", exampleEn: "The nights are cool in autumn." },
  { german: "frostig", english: "frosty", partOfSpeech: "adjective", category: "Temperature", example: "Der Morgen ist frostig.", exampleEn: "The morning is frosty." },
  { german: "eisig", english: "icy", partOfSpeech: "adjective", category: "Temperature", example: "Der Wind ist eisig heute.", exampleEn: "The wind is icy today." },
  { german: "mild", english: "mild", partOfSpeech: "adjective", category: "Temperature", example: "Der Winter war mild dieses Jahr.", exampleEn: "The winter was mild this year." },
  { german: "schwül", english: "humid, muggy", partOfSpeech: "adjective", category: "Temperature", example: "Es ist schwül im Sommer.", exampleEn: "It is muggy in summer." },
  { german: "lauwarm", english: "lukewarm", partOfSpeech: "adjective", category: "Temperature", example: "Der Kaffee ist nur lauwarm.", exampleEn: "The coffee is only lukewarm." },
  { german: "siedend", english: "boiling", partOfSpeech: "adjective", category: "Temperature", example: "Das Wasser ist siedend heiß.", exampleEn: "The water is boiling hot." },
  { german: "gefroren", english: "frozen", partOfSpeech: "adjective", category: "Temperature", example: "Der See ist gefroren.", exampleEn: "The lake is frozen." },
  { german: "tropisch", english: "tropical", partOfSpeech: "adjective", category: "Temperature", example: "Das Klima ist tropisch.", exampleEn: "The climate is tropical." },

  // ─── Appearance ─────────────────────────────────────────────────
  { german: "hübsch", english: "pretty", partOfSpeech: "adjective", category: "Appearance", example: "Das Kleid ist sehr hübsch.", exampleEn: "The dress is very pretty." },
  { german: "hässlich", english: "ugly", partOfSpeech: "adjective", category: "Appearance", example: "Das Gebäude ist hässlich.", exampleEn: "The building is ugly." },
  { german: "elegant", english: "elegant", partOfSpeech: "adjective", category: "Appearance", example: "Sie trägt ein elegantes Kleid.", exampleEn: "She is wearing an elegant dress." },
  { german: "sportlich", english: "sporty, athletic", partOfSpeech: "adjective", category: "Appearance", example: "Er sieht sportlich aus.", exampleEn: "He looks athletic." },
  { german: "schlank", english: "slim, slender", partOfSpeech: "adjective", category: "Appearance", example: "Sie ist groß und schlank.", exampleEn: "She is tall and slim." },
  { german: "mollig", english: "chubby, plump", partOfSpeech: "adjective", category: "Appearance", example: "Das Baby ist mollig.", exampleEn: "The baby is chubby." },
  { german: "muskulös", english: "muscular", partOfSpeech: "adjective", category: "Appearance", example: "Der Sportler ist muskulös.", exampleEn: "The athlete is muscular." },
  { german: "gepflegt", english: "well-groomed", partOfSpeech: "adjective", category: "Appearance", example: "Er ist immer gepflegt.", exampleEn: "He is always well-groomed." },
  { german: "attraktiv", english: "attractive", partOfSpeech: "adjective", category: "Appearance", example: "Sie findet ihn attraktiv.", exampleEn: "She finds him attractive." },
  { german: "jugendlich", english: "youthful", partOfSpeech: "adjective", category: "Appearance", example: "Sie sieht jugendlich aus.", exampleEn: "She looks youthful." },
  { german: "altmodisch", english: "old-fashioned", partOfSpeech: "adjective", category: "Appearance", example: "Die Möbel sind altmodisch.", exampleEn: "The furniture is old-fashioned." },
  { german: "modisch", english: "fashionable", partOfSpeech: "adjective", category: "Appearance", example: "Sie kleidet sich modisch.", exampleEn: "She dresses fashionably." },
  { german: "ordentlich", english: "neat, tidy", partOfSpeech: "adjective", category: "Appearance", example: "Sein Zimmer ist ordentlich.", exampleEn: "His room is tidy." },
  { german: "unordentlich", english: "messy, untidy", partOfSpeech: "adjective", category: "Appearance", example: "Der Schreibtisch ist unordentlich.", exampleEn: "The desk is messy." },
  { german: "auffällig", english: "conspicuous, striking", partOfSpeech: "adjective", category: "Appearance", example: "Sie trägt auffällige Kleidung.", exampleEn: "She wears striking clothing." },
  { german: "unauffällig", english: "inconspicuous", partOfSpeech: "adjective", category: "Appearance", example: "Er kleidet sich unauffällig.", exampleEn: "He dresses inconspicuously." },
  { german: "lockig", english: "curly", partOfSpeech: "adjective", category: "Appearance", example: "Sie hat lockige Haare.", exampleEn: "She has curly hair." },
  { german: "glänzend", english: "shiny, glossy", partOfSpeech: "adjective", category: "Appearance", example: "Die Schuhe sind glänzend.", exampleEn: "The shoes are shiny." },
  { german: "matt", english: "matte, dull", partOfSpeech: "adjective", category: "Appearance", example: "Die Farbe ist matt.", exampleEn: "The paint is matte." },
  { german: "transparent", english: "transparent", partOfSpeech: "adjective", category: "Appearance", example: "Das Glas ist transparent.", exampleEn: "The glass is transparent." },
  { german: "bärtig", english: "bearded", partOfSpeech: "adjective", category: "Appearance", example: "Der bärtige Mann sitzt am Tisch.", exampleEn: "The bearded man is sitting at the table." },
  { german: "sommersprossig", english: "freckled", partOfSpeech: "adjective", category: "Appearance", example: "Sie hat ein sommersprossiges Gesicht.", exampleEn: "She has a freckled face." },
  { german: "zierlich", english: "petite, dainty", partOfSpeech: "adjective", category: "Appearance", example: "Sie ist zierlich und klein.", exampleEn: "She is petite and small." },

  // ─── Time ───────────────────────────────────────────────────────
  { german: "früh", english: "early", partOfSpeech: "adjective", category: "Time", example: "Er steht immer früh auf.", exampleEn: "He always gets up early." },
  { german: "spät", english: "late", partOfSpeech: "adjective", category: "Time", example: "Es ist schon spät.", exampleEn: "It is already late." },
  { german: "täglich", english: "daily", partOfSpeech: "adjective", category: "Time", example: "Er macht täglich Sport.", exampleEn: "He exercises daily." },
  { german: "wöchentlich", english: "weekly", partOfSpeech: "adjective", category: "Time", example: "Wir haben wöchentlich ein Meeting.", exampleEn: "We have a meeting weekly." },
  { german: "monatlich", english: "monthly", partOfSpeech: "adjective", category: "Time", example: "Die Miete wird monatlich bezahlt.", exampleEn: "The rent is paid monthly." },
  { german: "jährlich", english: "yearly, annual", partOfSpeech: "adjective", category: "Time", example: "Es gibt eine jährliche Feier.", exampleEn: "There is an annual celebration." },
  { german: "regelmäßig", english: "regular", partOfSpeech: "adjective", category: "Time", example: "Er besucht regelmäßig den Arzt.", exampleEn: "He visits the doctor regularly." },
  { german: "ständig", english: "constant, continual", partOfSpeech: "adjective", category: "Time", example: "Er beschwert sich ständig.", exampleEn: "He constantly complains." },
  { german: "vorübergehend", english: "temporary", partOfSpeech: "adjective", category: "Time", example: "Die Störung ist vorübergehend.", exampleEn: "The disruption is temporary." },
  { german: "dauerhaft", english: "permanent", partOfSpeech: "adjective", category: "Time", example: "Er sucht eine dauerhafte Lösung.", exampleEn: "He is looking for a permanent solution." },
  { german: "sofortig", english: "immediate", partOfSpeech: "adjective", category: "Time", example: "Wir brauchen sofortige Hilfe.", exampleEn: "We need immediate help." },
  { german: "aktuell", english: "current", partOfSpeech: "adjective", category: "Time", example: "Das ist die aktuelle Situation.", exampleEn: "That is the current situation." },
  { german: "ehemalig", english: "former", partOfSpeech: "adjective", category: "Time", example: "Er ist ein ehemaliger Schüler.", exampleEn: "He is a former student." },
  { german: "zukünftig", english: "future", partOfSpeech: "adjective", category: "Time", example: "Wir planen zukünftige Projekte.", exampleEn: "We are planning future projects." },
  { german: "gleichzeitig", english: "simultaneous", partOfSpeech: "adjective", category: "Time", example: "Die Ereignisse passieren gleichzeitig.", exampleEn: "The events happen simultaneously." },
  { german: "endgültig", english: "final, definitive", partOfSpeech: "adjective", category: "Time", example: "Das ist die endgültige Entscheidung.", exampleEn: "That is the final decision." },
  { german: "rechtzeitig", english: "timely, on time", partOfSpeech: "adjective", category: "Time", example: "Wir sind rechtzeitig angekommen.", exampleEn: "We arrived on time." },
  { german: "plötzlich", english: "sudden", partOfSpeech: "adjective", category: "Time", example: "Es gab eine plötzliche Änderung.", exampleEn: "There was a sudden change." },
  { german: "allmählich", english: "gradual", partOfSpeech: "adjective", category: "Time", example: "Die Verbesserung ist allmählich.", exampleEn: "The improvement is gradual." },
  { german: "vergangen", english: "past, previous", partOfSpeech: "adjective", category: "Time", example: "Im vergangenen Jahr war ich in Berlin.", exampleEn: "Last year I was in Berlin." },

  // ─── Quantity ───────────────────────────────────────────────────
  { german: "viel", english: "much, a lot", partOfSpeech: "adjective", category: "Quantity", example: "Er hat viel Geld.", exampleEn: "He has a lot of money." },
  { german: "wenig", english: "little, few", partOfSpeech: "adjective", category: "Quantity", example: "Ich habe wenig Zeit.", exampleEn: "I have little time." },
  { german: "ganz", english: "whole, entire", partOfSpeech: "adjective", category: "Quantity", example: "Ich habe den ganzen Tag gearbeitet.", exampleEn: "I worked the whole day." },
  { german: "halb", english: "half", partOfSpeech: "adjective", category: "Quantity", example: "Ich möchte ein halbes Brot.", exampleEn: "I would like half a loaf of bread." },
  { german: "doppelt", english: "double", partOfSpeech: "adjective", category: "Quantity", example: "Er verdient das Doppelte.", exampleEn: "He earns double." },
  { german: "einzeln", english: "individual, single", partOfSpeech: "adjective", category: "Quantity", example: "Jeder einzelne Schüler muss kommen.", exampleEn: "Every single student must come." },
  { german: "zahlreich", english: "numerous", partOfSpeech: "adjective", category: "Quantity", example: "Es gibt zahlreiche Möglichkeiten.", exampleEn: "There are numerous possibilities." },
  { german: "reichlich", english: "plentiful, ample", partOfSpeech: "adjective", category: "Quantity", example: "Es gibt reichlich Essen.", exampleEn: "There is plenty of food." },
  { german: "knapp", english: "scarce, barely enough", partOfSpeech: "adjective", category: "Quantity", example: "Die Zeit ist knapp.", exampleEn: "Time is scarce." },
  { german: "übrig", english: "remaining, leftover", partOfSpeech: "adjective", category: "Quantity", example: "Ist noch Kuchen übrig?", exampleEn: "Is there any cake left?" },
  { german: "sämtlich", english: "all, entire", partOfSpeech: "adjective", category: "Quantity", example: "Sämtliche Plätze sind besetzt.", exampleEn: "All seats are taken." },
  { german: "mehrere", english: "several", partOfSpeech: "adjective", category: "Quantity", example: "Ich habe mehrere Bücher gelesen.", exampleEn: "I have read several books." },
  { german: "genug", english: "enough", partOfSpeech: "adjective", category: "Quantity", example: "Wir haben genug Essen.", exampleEn: "We have enough food." },
  { german: "zusätzlich", english: "additional", partOfSpeech: "adjective", category: "Quantity", example: "Wir brauchen zusätzliche Stühle.", exampleEn: "We need additional chairs." },
  { german: "unzählig", english: "countless", partOfSpeech: "adjective", category: "Quantity", example: "Es gibt unzählige Sterne am Himmel.", exampleEn: "There are countless stars in the sky." },
  { german: "gesamt", english: "total, overall", partOfSpeech: "adjective", category: "Quantity", example: "Die Gesamtkosten sind hoch.", exampleEn: "The total costs are high." },
  { german: "durchschnittlich", english: "average", partOfSpeech: "adjective", category: "Quantity", example: "Die durchschnittliche Temperatur ist 20 Grad.", exampleEn: "The average temperature is 20 degrees." },
  { german: "minimal", english: "minimal", partOfSpeech: "adjective", category: "Quantity", example: "Der Unterschied ist minimal.", exampleEn: "The difference is minimal." },
  { german: "maximal", english: "maximum", partOfSpeech: "adjective", category: "Quantity", example: "Die maximale Geschwindigkeit ist 120.", exampleEn: "The maximum speed is 120." },
  { german: "vollständig", english: "complete", partOfSpeech: "adjective", category: "Quantity", example: "Die Liste ist vollständig.", exampleEn: "The list is complete." },

  // ─── Opinion ────────────────────────────────────────────────────
  { german: "toll", english: "great, awesome", partOfSpeech: "adjective", category: "Opinion", example: "Das Konzert war toll!", exampleEn: "The concert was great!" },
  { german: "fantastisch", english: "fantastic", partOfSpeech: "adjective", category: "Opinion", example: "Die Aussicht ist fantastisch.", exampleEn: "The view is fantastic." },
  { german: "großartig", english: "magnificent, great", partOfSpeech: "adjective", category: "Opinion", example: "Das war eine großartige Leistung.", exampleEn: "That was a magnificent achievement." },
  { german: "herrlich", english: "splendid, magnificent", partOfSpeech: "adjective", category: "Opinion", example: "Das Wetter ist herrlich.", exampleEn: "The weather is splendid." },
  { german: "prima", english: "excellent, great", partOfSpeech: "adjective", category: "Opinion", example: "Das ist eine prima Idee!", exampleEn: "That is an excellent idea!" },
  { german: "super", english: "super, great", partOfSpeech: "adjective", category: "Opinion", example: "Der Film war super.", exampleEn: "The movie was great." },
  { german: "langweilig", english: "boring", partOfSpeech: "adjective", category: "Opinion", example: "Der Vortrag war langweilig.", exampleEn: "The lecture was boring." },
  { german: "interessant", english: "interesting", partOfSpeech: "adjective", category: "Opinion", example: "Das Buch ist sehr interessant.", exampleEn: "The book is very interesting." },
  { german: "spannend", english: "exciting, thrilling", partOfSpeech: "adjective", category: "Opinion", example: "Der Film war sehr spannend.", exampleEn: "The movie was very exciting." },
  { german: "angenehm", english: "pleasant", partOfSpeech: "adjective", category: "Opinion", example: "Das Gespräch war angenehm.", exampleEn: "The conversation was pleasant." },
  { german: "unangenehm", english: "unpleasant", partOfSpeech: "adjective", category: "Opinion", example: "Die Situation war unangenehm.", exampleEn: "The situation was unpleasant." },
  { german: "gemütlich", english: "cozy, comfortable", partOfSpeech: "adjective", category: "Opinion", example: "Das Café ist sehr gemütlich.", exampleEn: "The cafe is very cozy." },
  { german: "bequem", english: "comfortable", partOfSpeech: "adjective", category: "Opinion", example: "Die Schuhe sind bequem.", exampleEn: "The shoes are comfortable." },
  { german: "unbequem", english: "uncomfortable", partOfSpeech: "adjective", category: "Opinion", example: "Der Stuhl ist unbequem.", exampleEn: "The chair is uncomfortable." },
  { german: "merkwürdig", english: "strange, peculiar", partOfSpeech: "adjective", category: "Opinion", example: "Das ist ein merkwürdiger Zufall.", exampleEn: "That is a strange coincidence." },
  { german: "komisch", english: "funny, strange", partOfSpeech: "adjective", category: "Opinion", example: "Das schmeckt komisch.", exampleEn: "That tastes strange." },
  { german: "erstaunlich", english: "astonishing, amazing", partOfSpeech: "adjective", category: "Opinion", example: "Das Ergebnis ist erstaunlich.", exampleEn: "The result is astonishing." },
  { german: "beeindruckend", english: "impressive", partOfSpeech: "adjective", category: "Opinion", example: "Die Leistung war beeindruckend.", exampleEn: "The performance was impressive." },
  { german: "enorm", english: "enormous", partOfSpeech: "adjective", category: "Opinion", example: "Der Druck ist enorm.", exampleEn: "The pressure is enormous." },
  { german: "unglaublich", english: "incredible, unbelievable", partOfSpeech: "adjective", category: "Opinion", example: "Die Geschichte ist unglaublich.", exampleEn: "The story is incredible." },
  { german: "wunderbar", english: "marvelous", partOfSpeech: "adjective", category: "Opinion", example: "Der Abend war wunderbar.", exampleEn: "The evening was marvelous." },
  { german: "ekelhaft", english: "disgusting, revolting", partOfSpeech: "adjective", category: "Opinion", example: "Der Geruch ist ekelhaft.", exampleEn: "The smell is disgusting." },
  { german: "lächerlich", english: "ridiculous", partOfSpeech: "adjective", category: "Opinion", example: "Der Preis ist lächerlich hoch.", exampleEn: "The price is ridiculously high." },
  { german: "ungewöhnlich", english: "unusual", partOfSpeech: "adjective", category: "Opinion", example: "Das ist ein ungewöhnlicher Name.", exampleEn: "That is an unusual name." },
  { german: "gewöhnlich", english: "ordinary, usual", partOfSpeech: "adjective", category: "Opinion", example: "Das ist ein gewöhnlicher Tag.", exampleEn: "That is an ordinary day." },
  { german: "passend", english: "suitable, fitting", partOfSpeech: "adjective", category: "Opinion", example: "Das ist ein passender Zeitpunkt.", exampleEn: "That is a suitable time." },
  { german: "unpassend", english: "inappropriate", partOfSpeech: "adjective", category: "Opinion", example: "Der Kommentar war unpassend.", exampleEn: "The comment was inappropriate." },
  { german: "wunderschön", english: "beautiful, gorgeous", partOfSpeech: "adjective", category: "Opinion", example: "Der Sonnenuntergang ist wunderschön.", exampleEn: "The sunset is beautiful." },
  { german: "furchteinflößend", english: "intimidating, fearsome", partOfSpeech: "adjective", category: "Opinion", example: "Der Hund sieht furchteinflößend aus.", exampleEn: "The dog looks intimidating." },
  { german: "absurd", english: "absurd", partOfSpeech: "adjective", category: "Opinion", example: "Die Idee ist absurd.", exampleEn: "The idea is absurd." },

  // ─── Physical ───────────────────────────────────────────────────
  { german: "stark", english: "strong", partOfSpeech: "adjective", category: "Physical", example: "Er ist sehr stark.", exampleEn: "He is very strong." },
  { german: "schwach", english: "weak", partOfSpeech: "adjective", category: "Physical", example: "Sie fühlt sich schwach nach der Krankheit.", exampleEn: "She feels weak after the illness." },
  { german: "gesund", english: "healthy", partOfSpeech: "adjective", category: "Physical", example: "Er isst gesund.", exampleEn: "He eats healthily." },
  { german: "krank", english: "sick, ill", partOfSpeech: "adjective", category: "Physical", example: "Sie ist seit einer Woche krank.", exampleEn: "She has been sick for a week." },
  { german: "fit", english: "fit", partOfSpeech: "adjective", category: "Physical", example: "Er hält sich fit mit Sport.", exampleEn: "He keeps fit with exercise." },
  { german: "erschöpft", english: "exhausted", partOfSpeech: "adjective", category: "Physical", example: "Nach dem Lauf war ich erschöpft.", exampleEn: "After the run I was exhausted." },
  { german: "wach", english: "awake", partOfSpeech: "adjective", category: "Physical", example: "Ich bin noch nicht richtig wach.", exampleEn: "I am not fully awake yet." },
  { german: "schläfrig", english: "sleepy, drowsy", partOfSpeech: "adjective", category: "Physical", example: "Das Baby ist schläfrig.", exampleEn: "The baby is sleepy." },
  { german: "durstig", english: "thirsty", partOfSpeech: "adjective", category: "Physical", example: "Ich bin durstig nach dem Sport.", exampleEn: "I am thirsty after the exercise." },
  { german: "satt", english: "full (not hungry)", partOfSpeech: "adjective", category: "Physical", example: "Ich bin satt, danke.", exampleEn: "I am full, thank you." },
  { german: "blind", english: "blind", partOfSpeech: "adjective", category: "Physical", example: "Der Mann ist auf einem Auge blind.", exampleEn: "The man is blind in one eye." },
  { german: "taub", english: "deaf", partOfSpeech: "adjective", category: "Physical", example: "Meine Großmutter ist etwas taub.", exampleEn: "My grandmother is a bit deaf." },
  { german: "lebendig", english: "alive, lively", partOfSpeech: "adjective", category: "Physical", example: "Die Stadt ist nachts lebendig.", exampleEn: "The city is lively at night." },
  { german: "tot", english: "dead", partOfSpeech: "adjective", category: "Physical", example: "Die Pflanze ist tot.", exampleEn: "The plant is dead." },
  { german: "verletzt", english: "injured, hurt", partOfSpeech: "adjective", category: "Physical", example: "Der Spieler ist am Knie verletzt.", exampleEn: "The player is injured on the knee." },
  { german: "betrunken", english: "drunk", partOfSpeech: "adjective", category: "Physical", example: "Er war gestern betrunken.", exampleEn: "He was drunk yesterday." },
  { german: "nüchtern", english: "sober", partOfSpeech: "adjective", category: "Physical", example: "Er ist seit einem Jahr nüchtern.", exampleEn: "He has been sober for a year." },
  { german: "schwanger", english: "pregnant", partOfSpeech: "adjective", category: "Physical", example: "Sie ist im dritten Monat schwanger.", exampleEn: "She is three months pregnant." },
  { german: "behindert", english: "disabled", partOfSpeech: "adjective", category: "Physical", example: "Der Parkplatz ist für behinderte Personen.", exampleEn: "The parking spot is for disabled persons." },
  { german: "aktiv", english: "active", partOfSpeech: "adjective", category: "Physical", example: "Mein Großvater ist noch sehr aktiv.", exampleEn: "My grandfather is still very active." },
  { german: "beweglich", english: "flexible, mobile", partOfSpeech: "adjective", category: "Physical", example: "Sie ist trotz ihres Alters beweglich.", exampleEn: "She is flexible despite her age." },
  { german: "steif", english: "stiff", partOfSpeech: "adjective", category: "Physical", example: "Mein Nacken ist steif.", exampleEn: "My neck is stiff." },
  { german: "energisch", english: "energetic", partOfSpeech: "adjective", category: "Physical", example: "Sie ist eine energische Frau.", exampleEn: "She is an energetic woman." },
  { german: "kraftvoll", english: "powerful", partOfSpeech: "adjective", category: "Physical", example: "Der Motor ist kraftvoll.", exampleEn: "The engine is powerful." },
  { german: "schmerzfrei", english: "pain-free", partOfSpeech: "adjective", category: "Physical", example: "Endlich bin ich wieder schmerzfrei.", exampleEn: "Finally I am pain-free again." },
  { german: "allergisch", english: "allergic", partOfSpeech: "adjective", category: "Physical", example: "Ich bin allergisch gegen Nüsse.", exampleEn: "I am allergic to nuts." },
  { german: "fiebrig", english: "feverish", partOfSpeech: "adjective", category: "Physical", example: "Das Kind ist fiebrig.", exampleEn: "The child is feverish." },
  { german: "heiser", english: "hoarse", partOfSpeech: "adjective", category: "Physical", example: "Seine Stimme ist heiser.", exampleEn: "His voice is hoarse." },
  { german: "munter", english: "lively, alert", partOfSpeech: "adjective", category: "Physical", example: "Die Kinder sind munter und spielen.", exampleEn: "The children are lively and playing." },
  { german: "träge", english: "sluggish, lethargic", partOfSpeech: "adjective", category: "Physical", example: "Ich fühle mich heute träge.", exampleEn: "I feel sluggish today." },

  // ─── Additional Quality/General ─────────────────────────────────
  { german: "öffentlich", english: "public", partOfSpeech: "adjective", category: "Quality", example: "Der Park ist öffentlich.", exampleEn: "The park is public." },
  { german: "privat", english: "private", partOfSpeech: "adjective", category: "Quality", example: "Das ist eine private Feier.", exampleEn: "That is a private celebration." },
  { german: "kostenlos", english: "free (of charge)", partOfSpeech: "adjective", category: "Quality", example: "Der Eintritt ist kostenlos.", exampleEn: "Admission is free." },
  { german: "günstig", english: "cheap, favorable", partOfSpeech: "adjective", category: "Quality", example: "Die Wohnung ist günstig.", exampleEn: "The apartment is cheap." },
  { german: "angemessen", english: "appropriate, reasonable", partOfSpeech: "adjective", category: "Quality", example: "Der Preis ist angemessen.", exampleEn: "The price is reasonable." },
  { german: "verfügbar", english: "available", partOfSpeech: "adjective", category: "Quality", example: "Ist das Zimmer noch verfügbar?", exampleEn: "Is the room still available?" },
  { german: "fähig", english: "capable, able", partOfSpeech: "adjective", category: "Quality", example: "Sie ist eine fähige Mitarbeiterin.", exampleEn: "She is a capable employee." },
  { german: "geeignet", english: "suitable, appropriate", partOfSpeech: "adjective", category: "Quality", example: "Das Buch ist für Kinder geeignet.", exampleEn: "The book is suitable for children." },
  { german: "unterschiedlich", english: "different, varying", partOfSpeech: "adjective", category: "Quality", example: "Die Meinungen sind unterschiedlich.", exampleEn: "The opinions are different." },
  { german: "ähnlich", english: "similar", partOfSpeech: "adjective", category: "Quality", example: "Die Schwestern sehen sich ähnlich.", exampleEn: "The sisters look similar." },
  { german: "gleich", english: "same, equal", partOfSpeech: "adjective", category: "Quality", example: "Wir haben das gleiche Auto.", exampleEn: "We have the same car." },
  { german: "verschieden", english: "different, various", partOfSpeech: "adjective", category: "Quality", example: "Es gibt verschiedene Möglichkeiten.", exampleEn: "There are various possibilities." },
  { german: "gemeinsam", english: "common, shared", partOfSpeech: "adjective", category: "Quality", example: "Wir haben gemeinsame Interessen.", exampleEn: "We have shared interests." },
  { german: "getrennt", english: "separate", partOfSpeech: "adjective", category: "Quality", example: "Wir zahlen getrennt.", exampleEn: "We pay separately." },
  { german: "direkt", english: "direct", partOfSpeech: "adjective", category: "Quality", example: "Es gibt einen direkten Flug.", exampleEn: "There is a direct flight." },
  { german: "indirekt", english: "indirect", partOfSpeech: "adjective", category: "Quality", example: "Das war eine indirekte Antwort.", exampleEn: "That was an indirect answer." },
  { german: "offiziell", english: "official", partOfSpeech: "adjective", category: "Quality", example: "Das ist die offizielle Webseite.", exampleEn: "That is the official website." },
  { german: "umfangreich", english: "extensive, comprehensive", partOfSpeech: "adjective", category: "Quality", example: "Die Bibliothek hat eine umfangreiche Sammlung.", exampleEn: "The library has an extensive collection." },
  { german: "gründlich", english: "thorough", partOfSpeech: "adjective", category: "Quality", example: "Die Untersuchung war gründlich.", exampleEn: "The examination was thorough." },
  { german: "oberflächlich", english: "superficial", partOfSpeech: "adjective", category: "Quality", example: "Seine Analyse ist oberflächlich.", exampleEn: "His analysis is superficial." },
  { german: "genau", english: "exact, precise", partOfSpeech: "adjective", category: "Quality", example: "Die Uhr ist sehr genau.", exampleEn: "The clock is very precise." },
  { german: "ungefähr", english: "approximate", partOfSpeech: "adjective", category: "Quality", example: "Das ist ungefähr richtig.", exampleEn: "That is approximately correct." },
  { german: "deutlich", english: "clear, obvious", partOfSpeech: "adjective", category: "Quality", example: "Der Unterschied ist deutlich.", exampleEn: "The difference is clear." },
  { german: "unklar", english: "unclear", partOfSpeech: "adjective", category: "Quality", example: "Die Anweisungen sind unklar.", exampleEn: "The instructions are unclear." },
  { german: "offensichtlich", english: "obvious", partOfSpeech: "adjective", category: "Quality", example: "Der Fehler ist offensichtlich.", exampleEn: "The mistake is obvious." },
  { german: "geheim", english: "secret", partOfSpeech: "adjective", category: "Quality", example: "Das ist eine geheime Information.", exampleEn: "That is secret information." },
  { german: "freiwillig", english: "voluntary", partOfSpeech: "adjective", category: "Quality", example: "Die Teilnahme ist freiwillig.", exampleEn: "Participation is voluntary." },
  { german: "pflichtgemäß", english: "obligatory, dutiful", partOfSpeech: "adjective", category: "Quality", example: "Die Anmeldung ist pflichtgemäß.", exampleEn: "Registration is obligatory." },
  { german: "wirtschaftlich", english: "economic", partOfSpeech: "adjective", category: "Quality", example: "Die wirtschaftliche Lage ist schwierig.", exampleEn: "The economic situation is difficult." },
  { german: "politisch", english: "political", partOfSpeech: "adjective", category: "Quality", example: "Das ist eine politische Entscheidung.", exampleEn: "That is a political decision." },
  { german: "kulturell", english: "cultural", partOfSpeech: "adjective", category: "Quality", example: "Es gibt viele kulturelle Angebote.", exampleEn: "There are many cultural offerings." },
  { german: "wissenschaftlich", english: "scientific", partOfSpeech: "adjective", category: "Quality", example: "Das ist eine wissenschaftliche Studie.", exampleEn: "That is a scientific study." },
  { german: "technisch", english: "technical", partOfSpeech: "adjective", category: "Quality", example: "Es gibt ein technisches Problem.", exampleEn: "There is a technical problem." },
  { german: "digital", english: "digital", partOfSpeech: "adjective", category: "Quality", example: "Wir leben in einer digitalen Welt.", exampleEn: "We live in a digital world." },
  { german: "international", english: "international", partOfSpeech: "adjective", category: "Quality", example: "Das ist ein internationales Unternehmen.", exampleEn: "That is an international company." },
  { german: "lokal", english: "local", partOfSpeech: "adjective", category: "Quality", example: "Wir kaufen lokale Produkte.", exampleEn: "We buy local products." },
  { german: "umweltfreundlich", english: "environmentally friendly", partOfSpeech: "adjective", category: "Quality", example: "Das Auto ist umweltfreundlich.", exampleEn: "The car is environmentally friendly." },
  { german: "nachhaltig", english: "sustainable", partOfSpeech: "adjective", category: "Quality", example: "Wir brauchen nachhaltige Lösungen.", exampleEn: "We need sustainable solutions." },
  { german: "fair", english: "fair", partOfSpeech: "adjective", category: "Quality", example: "Das ist ein fairer Preis.", exampleEn: "That is a fair price." },
  { german: "unfair", english: "unfair", partOfSpeech: "adjective", category: "Quality", example: "Die Entscheidung war unfair.", exampleEn: "The decision was unfair." },
  { german: "relevant", english: "relevant", partOfSpeech: "adjective", category: "Quality", example: "Das ist eine relevante Frage.", exampleEn: "That is a relevant question." },
  { german: "unabhängig", english: "independent", partOfSpeech: "adjective", category: "Quality", example: "Sie ist finanziell unabhängig.", exampleEn: "She is financially independent." },
  { german: "abhängig", english: "dependent", partOfSpeech: "adjective", category: "Quality", example: "Das ist abhängig vom Wetter.", exampleEn: "That depends on the weather." },
  { german: "bewusst", english: "conscious, aware", partOfSpeech: "adjective", category: "Quality", example: "Ich bin mir des Problems bewusst.", exampleEn: "I am aware of the problem." },
  { german: "unbewusst", english: "unconscious", partOfSpeech: "adjective", category: "Quality", example: "Das war eine unbewusste Reaktion.", exampleEn: "That was an unconscious reaction." },
  { german: "logisch", english: "logical", partOfSpeech: "adjective", category: "Quality", example: "Die Erklärung ist logisch.", exampleEn: "The explanation is logical." },
  { german: "vernünftig", english: "reasonable, sensible", partOfSpeech: "adjective", category: "Quality", example: "Das ist ein vernünftiger Vorschlag.", exampleEn: "That is a sensible suggestion." },
  { german: "verrückt", english: "crazy", partOfSpeech: "adjective", category: "Quality", example: "Die Idee klingt verrückt.", exampleEn: "The idea sounds crazy." },
  { german: "gerecht", english: "just, fair", partOfSpeech: "adjective", category: "Quality", example: "Das Urteil war gerecht.", exampleEn: "The verdict was just." },
  { german: "handlich", english: "handy, compact", partOfSpeech: "adjective", category: "Quality", example: "Das Gerät ist handlich.", exampleEn: "The device is compact." },
  { german: "leserlich", english: "legible", partOfSpeech: "adjective", category: "Quality", example: "Seine Handschrift ist kaum leserlich.", exampleEn: "His handwriting is barely legible." },
  { german: "fehlerhaft", english: "faulty, flawed", partOfSpeech: "adjective", category: "Quality", example: "Das Produkt ist fehlerhaft.", exampleEn: "The product is faulty." },
  { german: "einwandfrei", english: "flawless, impeccable", partOfSpeech: "adjective", category: "Quality", example: "Die Qualität ist einwandfrei.", exampleEn: "The quality is flawless." },
  { german: "dicht", english: "dense, tight", partOfSpeech: "adjective", category: "Quality", example: "Der Nebel ist dicht.", exampleEn: "The fog is dense." },
  { german: "locker", english: "loose, relaxed", partOfSpeech: "adjective", category: "Quality", example: "Die Schraube ist locker.", exampleEn: "The screw is loose." },
  { german: "fest", english: "firm, solid", partOfSpeech: "adjective", category: "Quality", example: "Der Handschlag war fest.", exampleEn: "The handshake was firm." },
  { german: "flexibel", english: "flexible", partOfSpeech: "adjective", category: "Quality", example: "Die Arbeitszeiten sind flexibel.", exampleEn: "The working hours are flexible." },
  { german: "starr", english: "rigid", partOfSpeech: "adjective", category: "Quality", example: "Die Regeln sind zu starr.", exampleEn: "The rules are too rigid." },
  { german: "empfindlich", english: "sensitive, delicate", partOfSpeech: "adjective", category: "Quality", example: "Das Gerät ist empfindlich.", exampleEn: "The device is sensitive." },
  { german: "robust", english: "robust, sturdy", partOfSpeech: "adjective", category: "Quality", example: "Der Koffer ist robust.", exampleEn: "The suitcase is sturdy." },
  { german: "lebhaft", english: "lively, vivid", partOfSpeech: "adjective", category: "Quality", example: "Die Farben sind lebhaft.", exampleEn: "The colors are vivid." },
  { german: "wetterfest", english: "weatherproof", partOfSpeech: "adjective", category: "Quality", example: "Die Jacke ist wetterfest.", exampleEn: "The jacket is weatherproof." },
  { german: "wasserdicht", english: "waterproof", partOfSpeech: "adjective", category: "Quality", example: "Die Uhr ist wasserdicht.", exampleEn: "The watch is waterproof." },
  { german: "zeitgemäß", english: "contemporary, up-to-date", partOfSpeech: "adjective", category: "Quality", example: "Das Design ist zeitgemäß.", exampleEn: "The design is contemporary." },
  { german: "vorbildlich", english: "exemplary", partOfSpeech: "adjective", category: "Quality", example: "Sein Verhalten ist vorbildlich.", exampleEn: "His behavior is exemplary." },
  { german: "vielseitig", english: "versatile", partOfSpeech: "adjective", category: "Quality", example: "Sie ist eine vielseitige Sportlerin.", exampleEn: "She is a versatile athlete." },
  { german: "zugänglich", english: "accessible", partOfSpeech: "adjective", category: "Quality", example: "Das Gebäude ist rollstuhlzugänglich.", exampleEn: "The building is wheelchair accessible." },
  { german: "wirksam", english: "effective", partOfSpeech: "adjective", category: "Quality", example: "Das Medikament ist wirksam.", exampleEn: "The medicine is effective." },
  { german: "unwirksam", english: "ineffective", partOfSpeech: "adjective", category: "Quality", example: "Die Behandlung war unwirksam.", exampleEn: "The treatment was ineffective." },
  { german: "anspruchsvoll", english: "demanding, sophisticated", partOfSpeech: "adjective", category: "Quality", example: "Die Aufgabe ist anspruchsvoll.", exampleEn: "The task is demanding." },
  { german: "sparsam", english: "economical, thrifty", partOfSpeech: "adjective", category: "Quality", example: "Das Auto ist sparsam im Verbrauch.", exampleEn: "The car is economical in consumption." },
  { german: "verschwenderisch", english: "wasteful, extravagant", partOfSpeech: "adjective", category: "Quality", example: "Das Fest war verschwenderisch.", exampleEn: "The celebration was extravagant." },

  // ─── Additional Personality ─────────────────────────────────────
  { german: "launisch", english: "moody", partOfSpeech: "adjective", category: "Personality", example: "Er ist heute launisch.", exampleEn: "He is moody today." },
  { german: "redselig", english: "talkative", partOfSpeech: "adjective", category: "Personality", example: "Meine Nachbarin ist sehr redselig.", exampleEn: "My neighbor is very talkative." },
  { german: "schweigsam", english: "silent, taciturn", partOfSpeech: "adjective", category: "Personality", example: "Er ist ein schweigsamer Mensch.", exampleEn: "He is a taciturn person." },
  { german: "rücksichtsvoll", english: "considerate", partOfSpeech: "adjective", category: "Personality", example: "Er ist rücksichtsvoll gegenüber anderen.", exampleEn: "He is considerate toward others." },
  { german: "rücksichtslos", english: "reckless, inconsiderate", partOfSpeech: "adjective", category: "Personality", example: "Der Fahrer war rücksichtslos.", exampleEn: "The driver was reckless." },
  { german: "selbstsüchtig", english: "selfish", partOfSpeech: "adjective", category: "Personality", example: "Er denkt nur an sich, er ist selbstsüchtig.", exampleEn: "He only thinks of himself, he is selfish." },
  { german: "verständnisvoll", english: "understanding, sympathetic", partOfSpeech: "adjective", category: "Personality", example: "Meine Mutter ist sehr verständnisvoll.", exampleEn: "My mother is very understanding." },
  { german: "hartnäckig", english: "persistent, tenacious", partOfSpeech: "adjective", category: "Personality", example: "Sie ist hartnäckig in ihren Zielen.", exampleEn: "She is persistent in her goals." },
  { german: "einfühlsam", english: "empathetic", partOfSpeech: "adjective", category: "Personality", example: "Die Ärztin ist einfühlsam.", exampleEn: "The doctor is empathetic." },
  { german: "oberflächlich", english: "shallow, superficial", partOfSpeech: "adjective", category: "Personality", example: "Er führt nur oberflächliche Gespräche.", exampleEn: "He only has shallow conversations." },
  { german: "aufgeschlossen", english: "open-minded", partOfSpeech: "adjective", category: "Personality", example: "Sie ist aufgeschlossen gegenüber neuen Kulturen.", exampleEn: "She is open-minded toward new cultures." },
  { german: "verschlossen", english: "reserved, closed off", partOfSpeech: "adjective", category: "Personality", example: "Er ist emotional verschlossen.", exampleEn: "He is emotionally closed off." },
  { german: "gutmütig", english: "good-natured", partOfSpeech: "adjective", category: "Personality", example: "Der Hund ist gutmütig.", exampleEn: "The dog is good-natured." },
  { german: "boshaft", english: "malicious, spiteful", partOfSpeech: "adjective", category: "Personality", example: "Das war ein boshafter Kommentar.", exampleEn: "That was a spiteful comment." },
  { german: "sanftmütig", english: "gentle, meek", partOfSpeech: "adjective", category: "Personality", example: "Sie ist ein sanftmütiger Mensch.", exampleEn: "She is a gentle person." },
  { german: "dickköpfig", english: "pigheaded, stubborn", partOfSpeech: "adjective", category: "Personality", example: "Das Kind ist dickköpfig.", exampleEn: "The child is stubborn." },
  { german: "pflichtbewusst", english: "conscientious", partOfSpeech: "adjective", category: "Personality", example: "Er ist ein pflichtbewusster Arbeiter.", exampleEn: "He is a conscientious worker." },

  // ─── Additional Emotion ─────────────────────────────────────────
  { german: "melancholisch", english: "melancholic", partOfSpeech: "adjective", category: "Emotion", example: "Die Musik klingt melancholisch.", exampleEn: "The music sounds melancholic." },
  { german: "sehnsüchtig", english: "yearning, longing", partOfSpeech: "adjective", category: "Emotion", example: "Sie wartet sehnsüchtig auf seine Rückkehr.", exampleEn: "She waits longingly for his return." },
  { german: "überwältigt", english: "overwhelmed", partOfSpeech: "adjective", category: "Emotion", example: "Ich bin von der Schönheit überwältigt.", exampleEn: "I am overwhelmed by the beauty." },
  { german: "zuversichtlich", english: "confident, optimistic", partOfSpeech: "adjective", category: "Emotion", example: "Ich bin zuversichtlich, dass alles gut wird.", exampleEn: "I am confident that everything will be fine." },
  { german: "bestürzt", english: "dismayed, appalled", partOfSpeech: "adjective", category: "Emotion", example: "Wir waren bestürzt über die Nachricht.", exampleEn: "We were dismayed by the news." },
  { german: "empört", english: "outraged, indignant", partOfSpeech: "adjective", category: "Emotion", example: "Die Bürger sind empört.", exampleEn: "The citizens are outraged." },
  { german: "heiter", english: "cheerful, serene", partOfSpeech: "adjective", category: "Emotion", example: "Sie hat eine heitere Stimmung.", exampleEn: "She has a cheerful mood." },
  { german: "niedergeschlagen", english: "dejected, down", partOfSpeech: "adjective", category: "Emotion", example: "Er ist heute niedergeschlagen.", exampleEn: "He is dejected today." },
  { german: "aufgebracht", english: "agitated, upset", partOfSpeech: "adjective", category: "Emotion", example: "Die Menge ist aufgebracht.", exampleEn: "The crowd is agitated." },
  { german: "gereizt", english: "irritated", partOfSpeech: "adjective", category: "Emotion", example: "Er reagiert gereizt.", exampleEn: "He reacts irritably." },

  // ─── Additional Appearance ──────────────────────────────────────
  { german: "bleich", english: "pale, wan", partOfSpeech: "adjective", category: "Appearance", example: "Er sieht bleich aus.", exampleEn: "He looks pale." },
  { german: "sonnengebräunt", english: "suntanned", partOfSpeech: "adjective", category: "Appearance", example: "Sie ist sonnengebräunt vom Urlaub.", exampleEn: "She is suntanned from vacation." },
  { german: "faltig", english: "wrinkled", partOfSpeech: "adjective", category: "Appearance", example: "Sein Hemd ist faltig.", exampleEn: "His shirt is wrinkled." },
  { german: "gestreift", english: "striped", partOfSpeech: "adjective", category: "Appearance", example: "Sie trägt ein gestreiftes Hemd.", exampleEn: "She is wearing a striped shirt." },
  { german: "kariert", english: "checkered, plaid", partOfSpeech: "adjective", category: "Appearance", example: "Er trägt ein kariertes Hemd.", exampleEn: "He is wearing a checkered shirt." },
  { german: "gemustert", english: "patterned", partOfSpeech: "adjective", category: "Appearance", example: "Der Stoff ist gemustert.", exampleEn: "The fabric is patterned." },
  { german: "unifarben", english: "solid-colored", partOfSpeech: "adjective", category: "Appearance", example: "Ich bevorzuge unifarbene Kleidung.", exampleEn: "I prefer solid-colored clothing." },
  { german: "stämmig", english: "stocky, sturdy", partOfSpeech: "adjective", category: "Appearance", example: "Der Mann ist stämmig.", exampleEn: "The man is stocky." },
  { german: "drahtig", english: "wiry", partOfSpeech: "adjective", category: "Appearance", example: "Der Läufer ist drahtig.", exampleEn: "The runner is wiry." },
  { german: "kräftig", english: "strong, sturdy", partOfSpeech: "adjective", category: "Appearance", example: "Er hat kräftige Arme.", exampleEn: "He has strong arms." },

  // ─── Additional Physical ────────────────────────────────────────
  { german: "benommen", english: "dazed, dizzy", partOfSpeech: "adjective", category: "Physical", example: "Nach dem Sturz war er benommen.", exampleEn: "After the fall he was dazed." },
  { german: "übergewichtig", english: "overweight", partOfSpeech: "adjective", category: "Physical", example: "Er ist leicht übergewichtig.", exampleEn: "He is slightly overweight." },
  { german: "untergewichtig", english: "underweight", partOfSpeech: "adjective", category: "Physical", example: "Das Kind ist untergewichtig.", exampleEn: "The child is underweight." },
  { german: "gelähmt", english: "paralyzed", partOfSpeech: "adjective", category: "Physical", example: "Sein Arm ist gelähmt.", exampleEn: "His arm is paralyzed." },
  { german: "empfindungslos", english: "numb", partOfSpeech: "adjective", category: "Physical", example: "Meine Finger sind empfindungslos vor Kälte.", exampleEn: "My fingers are numb from the cold." },
  { german: "ausdauernd", english: "enduring, having stamina", partOfSpeech: "adjective", category: "Physical", example: "Marathonläufer sind ausdauernd.", exampleEn: "Marathon runners have stamina." },
  { german: "gelenkig", english: "flexible, limber", partOfSpeech: "adjective", category: "Physical", example: "Die Turnerin ist sehr gelenkig.", exampleEn: "The gymnast is very flexible." },
  { german: "schwindlig", english: "dizzy", partOfSpeech: "adjective", category: "Physical", example: "Mir ist schwindlig.", exampleEn: "I am dizzy." },
  { german: "übelkeit", english: "nauseous", partOfSpeech: "adjective", category: "Physical", example: "Mir ist übel nach der Fahrt.", exampleEn: "I feel nauseous after the ride." },
  { german: "vital", english: "vital, vigorous", partOfSpeech: "adjective", category: "Physical", example: "Sie ist trotz ihres Alters vital.", exampleEn: "She is vigorous despite her age." },

  // ─── Additional Size & Shape ────────────────────────────────────
  { german: "enorm", english: "enormous", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Baum ist enorm groß.", exampleEn: "The tree is enormously large." },
  { german: "zierlich", english: "delicate, slight", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Tasse ist zierlich.", exampleEn: "The cup is delicate." },
  { german: "ausgedehnt", english: "extensive, sprawling", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Park ist ausgedehnt.", exampleEn: "The park is extensive." },
  { german: "geräumig", english: "spacious", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Wohnung ist geräumig.", exampleEn: "The apartment is spacious." },
  { german: "beengt", english: "cramped", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Büro ist beengt.", exampleEn: "The office is cramped." },
  { german: "unförmig", english: "shapeless, misshapen", partOfSpeech: "adjective", category: "Size & Shape", example: "Der Koffer ist unförmig.", exampleEn: "The suitcase is misshapen." },
  { german: "symmetrisch", english: "symmetrical", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Gebäude ist symmetrisch.", exampleEn: "The building is symmetrical." },
  { german: "gewölbt", english: "curved, arched", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Decke ist gewölbt.", exampleEn: "The ceiling is arched." },
  { german: "abgerundet", english: "rounded", partOfSpeech: "adjective", category: "Size & Shape", example: "Die Ecken sind abgerundet.", exampleEn: "The corners are rounded." },
  { german: "quadratisch", english: "square", partOfSpeech: "adjective", category: "Size & Shape", example: "Das Fenster ist quadratisch.", exampleEn: "The window is square." },

  // ─── Additional Quality ─────────────────────────────────────────
  { german: "hochwertig", english: "high-quality", partOfSpeech: "adjective", category: "Quality", example: "Das Material ist hochwertig.", exampleEn: "The material is high-quality." },
  { german: "minderwertig", english: "inferior, low-quality", partOfSpeech: "adjective", category: "Quality", example: "Das Produkt ist minderwertig.", exampleEn: "The product is low-quality." },
  { german: "langlebig", english: "durable, long-lasting", partOfSpeech: "adjective", category: "Quality", example: "Die Möbel sind langlebig.", exampleEn: "The furniture is durable." },
  { german: "verdächtig", english: "suspicious", partOfSpeech: "adjective", category: "Quality", example: "Der Mann wirkt verdächtig.", exampleEn: "The man seems suspicious." },
  { german: "harmlos", english: "harmless", partOfSpeech: "adjective", category: "Quality", example: "Die Spinne ist harmlos.", exampleEn: "The spider is harmless." },
  { german: "giftig", english: "poisonous, toxic", partOfSpeech: "adjective", category: "Quality", example: "Die Pflanze ist giftig.", exampleEn: "The plant is poisonous." },
  { german: "essbar", english: "edible", partOfSpeech: "adjective", category: "Quality", example: "Sind diese Pilze essbar?", exampleEn: "Are these mushrooms edible?" },
  { german: "haltbar", english: "durable, long-lasting (food)", partOfSpeech: "adjective", category: "Quality", example: "Die Milch ist noch haltbar.", exampleEn: "The milk is still good." },
  { german: "verdorben", english: "spoiled, rotten", partOfSpeech: "adjective", category: "Quality", example: "Das Fleisch ist verdorben.", exampleEn: "The meat is spoiled." },
  { german: "reif", english: "ripe, mature", partOfSpeech: "adjective", category: "Quality", example: "Die Banane ist reif.", exampleEn: "The banana is ripe." },
  { german: "unreif", english: "unripe, immature", partOfSpeech: "adjective", category: "Quality", example: "Die Tomaten sind noch unreif.", exampleEn: "The tomatoes are still unripe." },
  { german: "würzig", english: "savory, spiced", partOfSpeech: "adjective", category: "Quality", example: "Die Soße ist würzig.", exampleEn: "The sauce is savory." },
  { german: "fade", english: "bland, tasteless", partOfSpeech: "adjective", category: "Quality", example: "Das Essen ist fade.", exampleEn: "The food is bland." },
  { german: "cremig", english: "creamy", partOfSpeech: "adjective", category: "Quality", example: "Die Suppe ist cremig.", exampleEn: "The soup is creamy." },
  { german: "knusprig", english: "crispy, crunchy", partOfSpeech: "adjective", category: "Quality", example: "Das Brötchen ist knusprig.", exampleEn: "The bread roll is crispy." },
  { german: "saftig", english: "juicy", partOfSpeech: "adjective", category: "Quality", example: "Der Apfel ist saftig.", exampleEn: "The apple is juicy." },
  { german: "duftend", english: "fragrant", partOfSpeech: "adjective", category: "Quality", example: "Die Rosen sind duftend.", exampleEn: "The roses are fragrant." },
  { german: "stinkend", english: "smelly, stinking", partOfSpeech: "adjective", category: "Quality", example: "Der Müll ist stinkend.", exampleEn: "The trash is smelly." },
  { german: "lebenswert", english: "worth living", partOfSpeech: "adjective", category: "Quality", example: "Diese Stadt ist sehr lebenswert.", exampleEn: "This city is very livable." },
  { german: "sehenswert", english: "worth seeing", partOfSpeech: "adjective", category: "Quality", example: "Das Museum ist sehenswert.", exampleEn: "The museum is worth seeing." },
  { german: "empfehlenswert", english: "recommendable", partOfSpeech: "adjective", category: "Quality", example: "Das Restaurant ist empfehlenswert.", exampleEn: "The restaurant is recommendable." },
  { german: "preiswert", english: "good value, inexpensive", partOfSpeech: "adjective", category: "Quality", example: "Das Essen ist preiswert.", exampleEn: "The food is good value." },
  { german: "handgemacht", english: "handmade", partOfSpeech: "adjective", category: "Quality", example: "Die Schokolade ist handgemacht.", exampleEn: "The chocolate is handmade." },
  { german: "maßgeschneidert", english: "tailor-made, custom", partOfSpeech: "adjective", category: "Quality", example: "Der Anzug ist maßgeschneidert.", exampleEn: "The suit is tailor-made." },
  { german: "glutenfrei", english: "gluten-free", partOfSpeech: "adjective", category: "Quality", example: "Das Brot ist glutenfrei.", exampleEn: "The bread is gluten-free." },
  { german: "biologisch", english: "organic", partOfSpeech: "adjective", category: "Quality", example: "Wir kaufen biologisches Gemüse.", exampleEn: "We buy organic vegetables." },
  { german: "vegetarisch", english: "vegetarian", partOfSpeech: "adjective", category: "Quality", example: "Er isst vegetarisch.", exampleEn: "He eats vegetarian." },
  { german: "vegan", english: "vegan", partOfSpeech: "adjective", category: "Quality", example: "Das Restaurant bietet vegane Gerichte.", exampleEn: "The restaurant offers vegan dishes." },
  { german: "alltäglich", english: "everyday, commonplace", partOfSpeech: "adjective", category: "Quality", example: "Das ist ein alltägliches Problem.", exampleEn: "That is an everyday problem." },
  { german: "außergewöhnlich", english: "extraordinary", partOfSpeech: "adjective", category: "Quality", example: "Sie hat ein außergewöhnliches Talent.", exampleEn: "She has an extraordinary talent." },
  { german: "hervorragend", english: "outstanding, superb", partOfSpeech: "adjective", category: "Quality", example: "Die Qualität ist hervorragend.", exampleEn: "The quality is outstanding." },
  { german: "mittelmäßig", english: "mediocre, average", partOfSpeech: "adjective", category: "Quality", example: "Der Film war mittelmäßig.", exampleEn: "The movie was mediocre." },
  { german: "überlegen", english: "superior", partOfSpeech: "adjective", category: "Quality", example: "Die Mannschaft war klar überlegen.", exampleEn: "The team was clearly superior." },
  { german: "unterlegen", english: "inferior", partOfSpeech: "adjective", category: "Quality", example: "Die Mannschaft war zahlenmäßig unterlegen.", exampleEn: "The team was outnumbered." },
  { german: "vorhersehbar", english: "predictable", partOfSpeech: "adjective", category: "Quality", example: "Das Ende war vorhersehbar.", exampleEn: "The ending was predictable." },
  { german: "unvorhersehbar", english: "unpredictable", partOfSpeech: "adjective", category: "Quality", example: "Das Wetter ist unvorhersehbar.", exampleEn: "The weather is unpredictable." },
];
