import type { VocabWordBase } from "../german-types";

export const EXPANDED_ADVERBS: VocabWordBase[] = [
  // ─── Time ───────────────────────────────────────────────────────
  { german: "jetzt", english: "now", partOfSpeech: "adverb", category: "Time", example: "Ich muss jetzt gehen.", exampleEn: "I have to go now." },
  { german: "heute", english: "today", partOfSpeech: "adverb", category: "Time", example: "Heute ist ein schöner Tag.", exampleEn: "Today is a beautiful day." },
  { german: "gestern", english: "yesterday", partOfSpeech: "adverb", category: "Time", example: "Gestern war ich im Kino.", exampleEn: "Yesterday I was at the cinema." },
  { german: "morgen", english: "tomorrow", partOfSpeech: "adverb", category: "Time", example: "Morgen fahren wir nach Berlin.", exampleEn: "Tomorrow we are going to Berlin." },
  { german: "vorgestern", english: "the day before yesterday", partOfSpeech: "adverb", category: "Time", example: "Vorgestern hat es geregnet.", exampleEn: "The day before yesterday it rained." },
  { german: "übermorgen", english: "the day after tomorrow", partOfSpeech: "adverb", category: "Time", example: "Übermorgen habe ich frei.", exampleEn: "The day after tomorrow I have the day off." },
  { german: "bald", english: "soon", partOfSpeech: "adverb", category: "Time", example: "Wir kommen bald an.", exampleEn: "We will arrive soon." },
  { german: "früher", english: "earlier, in the past", partOfSpeech: "adverb", category: "Time", example: "Früher habe ich in München gewohnt.", exampleEn: "In the past I lived in Munich." },
  { german: "später", english: "later", partOfSpeech: "adverb", category: "Time", example: "Ich rufe dich später an.", exampleEn: "I will call you later." },
  { german: "sofort", english: "immediately", partOfSpeech: "adverb", category: "Time", example: "Komm bitte sofort!", exampleEn: "Please come immediately!" },
  { german: "gerade", english: "just now, right now", partOfSpeech: "adverb", category: "Time", example: "Ich bin gerade angekommen.", exampleEn: "I just arrived." },
  { german: "damals", english: "back then, at that time", partOfSpeech: "adverb", category: "Time", example: "Damals war alles anders.", exampleEn: "Back then everything was different." },
  { german: "zunächst", english: "first, initially", partOfSpeech: "adverb", category: "Time", example: "Zunächst müssen wir planen.", exampleEn: "First we need to plan." },
  { german: "danach", english: "afterwards, after that", partOfSpeech: "adverb", category: "Time", example: "Wir essen und danach gehen wir spazieren.", exampleEn: "We eat and afterwards we go for a walk." },
  { german: "vorher", english: "before, beforehand", partOfSpeech: "adverb", category: "Time", example: "Ruf mich vorher an.", exampleEn: "Call me beforehand." },
  { german: "nachher", english: "afterwards, later", partOfSpeech: "adverb", category: "Time", example: "Wir sprechen nachher darüber.", exampleEn: "We will talk about it later." },
  { german: "inzwischen", english: "meanwhile, in the meantime", partOfSpeech: "adverb", category: "Time", example: "Inzwischen hat sich viel geändert.", exampleEn: "In the meantime a lot has changed." },
  { german: "bereits", english: "already", partOfSpeech: "adverb", category: "Time", example: "Er hat bereits gegessen.", exampleEn: "He has already eaten." },
  { german: "schon", english: "already", partOfSpeech: "adverb", category: "Time", example: "Bist du schon fertig?", exampleEn: "Are you done already?" },
  { german: "noch", english: "still, yet", partOfSpeech: "adverb", category: "Time", example: "Er schläft noch.", exampleEn: "He is still sleeping." },
  { german: "endlich", english: "finally", partOfSpeech: "adverb", category: "Time", example: "Endlich ist der Sommer da!", exampleEn: "Finally summer is here!" },
  { german: "neulich", english: "recently, the other day", partOfSpeech: "adverb", category: "Time", example: "Neulich habe ich ihn getroffen.", exampleEn: "I met him the other day." },
  { german: "kürzlich", english: "recently", partOfSpeech: "adverb", category: "Time", example: "Sie hat kürzlich geheiratet.", exampleEn: "She recently got married." },
  { german: "seitdem", english: "since then", partOfSpeech: "adverb", category: "Time", example: "Seitdem habe ich ihn nicht mehr gesehen.", exampleEn: "Since then I have not seen him again." },
  { german: "mittlerweile", english: "by now, meanwhile", partOfSpeech: "adverb", category: "Time", example: "Mittlerweile spricht sie gut Deutsch.", exampleEn: "By now she speaks German well." },
  { german: "heutzutage", english: "nowadays", partOfSpeech: "adverb", category: "Time", example: "Heutzutage hat jeder ein Smartphone.", exampleEn: "Nowadays everyone has a smartphone." },
  { german: "morgens", english: "in the morning", partOfSpeech: "adverb", category: "Time", example: "Morgens trinke ich Kaffee.", exampleEn: "In the morning I drink coffee." },
  { german: "abends", english: "in the evening", partOfSpeech: "adverb", category: "Time", example: "Abends lese ich gern.", exampleEn: "In the evening I like to read." },
  { german: "mittags", english: "at noon", partOfSpeech: "adverb", category: "Time", example: "Mittags essen wir in der Kantine.", exampleEn: "At noon we eat in the cafeteria." },
  { german: "nachts", english: "at night", partOfSpeech: "adverb", category: "Time", example: "Nachts ist es ruhig.", exampleEn: "At night it is quiet." },
  { german: "tagsüber", english: "during the day", partOfSpeech: "adverb", category: "Time", example: "Tagsüber arbeite ich.", exampleEn: "During the day I work." },
  { german: "stündlich", english: "hourly", partOfSpeech: "adverb", category: "Time", example: "Der Bus fährt stündlich.", exampleEn: "The bus runs hourly." },
  { german: "soeben", english: "just now", partOfSpeech: "adverb", category: "Time", example: "Er ist soeben gegangen.", exampleEn: "He just left." },
  { german: "demnächst", english: "soon, in the near future", partOfSpeech: "adverb", category: "Time", example: "Demnächst eröffnet ein neues Restaurant.", exampleEn: "A new restaurant will open soon." },
  { german: "irgendwann", english: "sometime, someday", partOfSpeech: "adverb", category: "Time", example: "Irgendwann möchte ich nach Japan reisen.", exampleEn: "Someday I would like to travel to Japan." },
  { german: "anfangs", english: "at first, initially", partOfSpeech: "adverb", category: "Time", example: "Anfangs war es schwer.", exampleEn: "At first it was hard." },
  { german: "zuletzt", english: "lastly, most recently", partOfSpeech: "adverb", category: "Time", example: "Zuletzt habe ich ihn im Mai gesehen.", exampleEn: "I last saw him in May." },
  { german: "seither", english: "since then", partOfSpeech: "adverb", category: "Time", example: "Seither hat er sich verändert.", exampleEn: "Since then he has changed." },
  { german: "eben", english: "just (a moment ago)", partOfSpeech: "adverb", category: "Time", example: "Ich habe eben mit ihr gesprochen.", exampleEn: "I just spoke with her." },
  { german: "vorerst", english: "for the time being", partOfSpeech: "adverb", category: "Time", example: "Vorerst bleibt alles beim Alten.", exampleEn: "For the time being everything stays the same." },

  // ─── Frequency ──────────────────────────────────────────────────
  { german: "immer", english: "always", partOfSpeech: "adverb", category: "Frequency", example: "Ich trinke immer Kaffee am Morgen.", exampleEn: "I always drink coffee in the morning." },
  { german: "nie", english: "never", partOfSpeech: "adverb", category: "Frequency", example: "Er ist nie zu spät.", exampleEn: "He is never late." },
  { german: "niemals", english: "never (emphatic)", partOfSpeech: "adverb", category: "Frequency", example: "Das werde ich niemals vergessen.", exampleEn: "I will never forget that." },
  { german: "oft", english: "often", partOfSpeech: "adverb", category: "Frequency", example: "Wir gehen oft spazieren.", exampleEn: "We often go for walks." },
  { german: "häufig", english: "frequently", partOfSpeech: "adverb", category: "Frequency", example: "Sie reist häufig ins Ausland.", exampleEn: "She frequently travels abroad." },
  { german: "selten", english: "rarely, seldom", partOfSpeech: "adverb", category: "Frequency", example: "Er geht selten ins Theater.", exampleEn: "He rarely goes to the theater." },
  { german: "manchmal", english: "sometimes", partOfSpeech: "adverb", category: "Frequency", example: "Manchmal esse ich Pizza.", exampleEn: "Sometimes I eat pizza." },
  { german: "meistens", english: "mostly, usually", partOfSpeech: "adverb", category: "Frequency", example: "Meistens bin ich pünktlich.", exampleEn: "Mostly I am on time." },
  { german: "normalerweise", english: "normally, usually", partOfSpeech: "adverb", category: "Frequency", example: "Normalerweise stehe ich um sieben auf.", exampleEn: "Normally I get up at seven." },
  { german: "gewöhnlich", english: "usually, normally", partOfSpeech: "adverb", category: "Frequency", example: "Gewöhnlich fahre ich mit dem Bus.", exampleEn: "Usually I take the bus." },
  { german: "ab und zu", english: "now and then", partOfSpeech: "adverb", category: "Frequency", example: "Ab und zu gehe ich ins Museum.", exampleEn: "Now and then I go to the museum." },
  { german: "gelegentlich", english: "occasionally", partOfSpeech: "adverb", category: "Frequency", example: "Gelegentlich trinke ich ein Glas Wein.", exampleEn: "Occasionally I drink a glass of wine." },
  { german: "ständig", english: "constantly", partOfSpeech: "adverb", category: "Frequency", example: "Er beschwert sich ständig.", exampleEn: "He constantly complains." },
  { german: "regelmäßig", english: "regularly", partOfSpeech: "adverb", category: "Frequency", example: "Sie trainiert regelmäßig.", exampleEn: "She trains regularly." },
  { german: "kaum", english: "hardly, barely", partOfSpeech: "adverb", category: "Frequency", example: "Ich habe kaum geschlafen.", exampleEn: "I barely slept." },
  { german: "stets", english: "always, constantly", partOfSpeech: "adverb", category: "Frequency", example: "Er ist stets freundlich.", exampleEn: "He is always friendly." },
  { german: "fortwährend", english: "continuously", partOfSpeech: "adverb", category: "Frequency", example: "Es regnet fortwährend.", exampleEn: "It rains continuously." },
  { german: "zeitweise", english: "at times, periodically", partOfSpeech: "adverb", category: "Frequency", example: "Zeitweise scheint die Sonne.", exampleEn: "At times the sun shines." },
  { german: "mehrmals", english: "several times", partOfSpeech: "adverb", category: "Frequency", example: "Ich habe ihn mehrmals angerufen.", exampleEn: "I called him several times." },
  { german: "nochmal", english: "once more, again", partOfSpeech: "adverb", category: "Frequency", example: "Kannst du das nochmal sagen?", exampleEn: "Can you say that once more?" },
  { german: "erneut", english: "again, anew", partOfSpeech: "adverb", category: "Frequency", example: "Der Fehler trat erneut auf.", exampleEn: "The error occurred again." },
  { german: "wiederholt", english: "repeatedly", partOfSpeech: "adverb", category: "Frequency", example: "Er hat wiederholt gelogen.", exampleEn: "He lied repeatedly." },
  { german: "ausnahmsweise", english: "exceptionally, as an exception", partOfSpeech: "adverb", category: "Frequency", example: "Ausnahmsweise darf er länger aufbleiben.", exampleEn: "As an exception, he may stay up longer." },
  { german: "üblicherweise", english: "customarily, usually", partOfSpeech: "adverb", category: "Frequency", example: "Üblicherweise essen wir um zwölf.", exampleEn: "We customarily eat at twelve." },

  // ─── Place ──────────────────────────────────────────────────────
  { german: "hier", english: "here", partOfSpeech: "adverb", category: "Place", example: "Ich wohne hier.", exampleEn: "I live here." },
  { german: "dort", english: "there", partOfSpeech: "adverb", category: "Place", example: "Das Restaurant ist dort drüben.", exampleEn: "The restaurant is over there." },
  { german: "da", english: "there, here", partOfSpeech: "adverb", category: "Place", example: "Da ist mein Schlüssel!", exampleEn: "There is my key!" },
  { german: "oben", english: "above, upstairs", partOfSpeech: "adverb", category: "Place", example: "Das Schlafzimmer ist oben.", exampleEn: "The bedroom is upstairs." },
  { german: "unten", english: "below, downstairs", partOfSpeech: "adverb", category: "Place", example: "Die Küche ist unten.", exampleEn: "The kitchen is downstairs." },
  { german: "draußen", english: "outside", partOfSpeech: "adverb", category: "Place", example: "Die Kinder spielen draußen.", exampleEn: "The children are playing outside." },
  { german: "drinnen", english: "inside", partOfSpeech: "adverb", category: "Place", example: "Es ist warm drinnen.", exampleEn: "It is warm inside." },
  { german: "links", english: "left, on the left", partOfSpeech: "adverb", category: "Place", example: "Die Bank ist links.", exampleEn: "The bank is on the left." },
  { german: "rechts", english: "right, on the right", partOfSpeech: "adverb", category: "Place", example: "Das Café ist rechts.", exampleEn: "The cafe is on the right." },
  { german: "vorne", english: "in front, at the front", partOfSpeech: "adverb", category: "Place", example: "Sitz dich bitte nach vorne.", exampleEn: "Please sit at the front." },
  { german: "hinten", english: "behind, at the back", partOfSpeech: "adverb", category: "Place", example: "Der Garten ist hinten.", exampleEn: "The garden is at the back." },
  { german: "überall", english: "everywhere", partOfSpeech: "adverb", category: "Place", example: "Überall liegen Bücher.", exampleEn: "There are books everywhere." },
  { german: "nirgendwo", english: "nowhere", partOfSpeech: "adverb", category: "Place", example: "Ich kann meinen Schlüssel nirgendwo finden.", exampleEn: "I cannot find my key anywhere." },
  { german: "irgendwo", english: "somewhere", partOfSpeech: "adverb", category: "Place", example: "Mein Portemonnaie muss irgendwo sein.", exampleEn: "My wallet must be somewhere." },
  { german: "nebenan", english: "next door", partOfSpeech: "adverb", category: "Place", example: "Unsere Nachbarn wohnen nebenan.", exampleEn: "Our neighbors live next door." },
  { german: "gegenüber", english: "opposite, across", partOfSpeech: "adverb", category: "Place", example: "Die Apotheke ist gegenüber.", exampleEn: "The pharmacy is across the street." },
  { german: "entlang", english: "along", partOfSpeech: "adverb", category: "Place", example: "Geh den Fluss entlang.", exampleEn: "Walk along the river." },
  { german: "herum", english: "around", partOfSpeech: "adverb", category: "Place", example: "Die Kinder laufen herum.", exampleEn: "The children are running around." },
  { german: "weg", english: "away, gone", partOfSpeech: "adverb", category: "Place", example: "Er ist schon weg.", exampleEn: "He is already gone." },
  { german: "zurück", english: "back", partOfSpeech: "adverb", category: "Place", example: "Wir fahren morgen zurück.", exampleEn: "We are going back tomorrow." },
  { german: "vorwärts", english: "forward", partOfSpeech: "adverb", category: "Place", example: "Geh immer vorwärts.", exampleEn: "Keep going forward." },
  { german: "rückwärts", english: "backward", partOfSpeech: "adverb", category: "Place", example: "Er kann rückwärts einparken.", exampleEn: "He can park in reverse." },
  { german: "aufwärts", english: "upward", partOfSpeech: "adverb", category: "Place", example: "Der Weg führt aufwärts.", exampleEn: "The path leads upward." },
  { german: "abwärts", english: "downward", partOfSpeech: "adverb", category: "Place", example: "Es geht steil abwärts.", exampleEn: "It goes steeply downward." },
  { german: "dazwischen", english: "in between", partOfSpeech: "adverb", category: "Place", example: "Die Pause liegt dazwischen.", exampleEn: "The break is in between." },
  { german: "seitwärts", english: "sideways", partOfSpeech: "adverb", category: "Place", example: "Die Krabbe bewegt sich seitwärts.", exampleEn: "The crab moves sideways." },
  { german: "anderswo", english: "elsewhere", partOfSpeech: "adverb", category: "Place", example: "Lass uns anderswo essen.", exampleEn: "Let's eat elsewhere." },
  { german: "daheim", english: "at home", partOfSpeech: "adverb", category: "Place", example: "Ich bleibe heute daheim.", exampleEn: "I am staying at home today." },
  { german: "drüben", english: "over there", partOfSpeech: "adverb", category: "Place", example: "Das Geschäft ist drüben.", exampleEn: "The shop is over there." },
  { german: "mittendrin", english: "right in the middle", partOfSpeech: "adverb", category: "Place", example: "Wir standen mittendrin.", exampleEn: "We stood right in the middle." },
  { german: "rundum", english: "all around", partOfSpeech: "adverb", category: "Place", example: "Rundum war alles grün.", exampleEn: "All around everything was green." },
  { german: "herein", english: "in (toward speaker)", partOfSpeech: "adverb", category: "Place", example: "Kommen Sie bitte herein!", exampleEn: "Please come in!" },
  { german: "heraus", english: "out (toward speaker)", partOfSpeech: "adverb", category: "Place", example: "Komm heraus aus dem Haus!", exampleEn: "Come out of the house!" },
  { german: "hinauf", english: "up (away from speaker)", partOfSpeech: "adverb", category: "Place", example: "Wir gehen den Berg hinauf.", exampleEn: "We are going up the mountain." },
  { german: "hinunter", english: "down (away from speaker)", partOfSpeech: "adverb", category: "Place", example: "Sie ging die Treppe hinunter.", exampleEn: "She went down the stairs." },

  // ─── Manner ─────────────────────────────────────────────────────
  { german: "gern", english: "gladly, with pleasure", partOfSpeech: "adverb", category: "Manner", example: "Ich lese gern.", exampleEn: "I like to read." },
  { german: "lieber", english: "rather, preferably", partOfSpeech: "adverb", category: "Manner", example: "Ich trinke lieber Tee als Kaffee.", exampleEn: "I prefer tea over coffee." },
  { german: "am liebsten", english: "most of all, most preferably", partOfSpeech: "adverb", category: "Manner", example: "Am liebsten esse ich Pizza.", exampleEn: "Most of all I like to eat pizza." },
  { german: "langsam", english: "slowly", partOfSpeech: "adverb", category: "Manner", example: "Bitte sprechen Sie langsam.", exampleEn: "Please speak slowly." },
  { german: "schnell", english: "quickly", partOfSpeech: "adverb", category: "Manner", example: "Er läuft schnell.", exampleEn: "He runs quickly." },
  { german: "leise", english: "quietly", partOfSpeech: "adverb", category: "Manner", example: "Bitte sprich leise.", exampleEn: "Please speak quietly." },
  { german: "laut", english: "loudly", partOfSpeech: "adverb", category: "Manner", example: "Die Kinder lachen laut.", exampleEn: "The children laugh loudly." },
  { german: "gut", english: "well", partOfSpeech: "adverb", category: "Manner", example: "Sie spricht gut Deutsch.", exampleEn: "She speaks German well." },
  { german: "schlecht", english: "badly", partOfSpeech: "adverb", category: "Manner", example: "Ich habe schlecht geschlafen.", exampleEn: "I slept badly." },
  { german: "zusammen", english: "together", partOfSpeech: "adverb", category: "Manner", example: "Wir arbeiten zusammen.", exampleEn: "We work together." },
  { german: "allein", english: "alone", partOfSpeech: "adverb", category: "Manner", example: "Sie lebt allein.", exampleEn: "She lives alone." },
  { german: "gemeinsam", english: "together, jointly", partOfSpeech: "adverb", category: "Manner", example: "Wir haben das gemeinsam geschafft.", exampleEn: "We managed that together." },
  { german: "absichtlich", english: "on purpose, deliberately", partOfSpeech: "adverb", category: "Manner", example: "Er hat es absichtlich getan.", exampleEn: "He did it on purpose." },
  { german: "versehentlich", english: "accidentally", partOfSpeech: "adverb", category: "Manner", example: "Ich habe versehentlich dein Glas umgeworfen.", exampleEn: "I accidentally knocked over your glass." },
  { german: "heimlich", english: "secretly", partOfSpeech: "adverb", category: "Manner", example: "Sie hat heimlich geweint.", exampleEn: "She secretly cried." },
  { german: "freiwillig", english: "voluntarily", partOfSpeech: "adverb", category: "Manner", example: "Er hat freiwillig geholfen.", exampleEn: "He helped voluntarily." },
  { german: "umsonst", english: "in vain, for free", partOfSpeech: "adverb", category: "Manner", example: "Die Mühe war umsonst.", exampleEn: "The effort was in vain." },
  { german: "vergeblich", english: "in vain, futilely", partOfSpeech: "adverb", category: "Manner", example: "Er hat vergeblich gewartet.", exampleEn: "He waited in vain." },
  { german: "sorgfältig", english: "carefully", partOfSpeech: "adverb", category: "Manner", example: "Sie hat sorgfältig gearbeitet.", exampleEn: "She worked carefully." },
  { german: "eilig", english: "hurriedly", partOfSpeech: "adverb", category: "Manner", example: "Er hat es eilig.", exampleEn: "He is in a hurry." },
  { german: "richtig", english: "correctly, properly", partOfSpeech: "adverb", category: "Manner", example: "Du hast richtig geantwortet.", exampleEn: "You answered correctly." },
  { german: "falsch", english: "wrongly, incorrectly", partOfSpeech: "adverb", category: "Manner", example: "Du hast falsch abgebogen.", exampleEn: "You turned the wrong way." },
  { german: "anders", english: "differently", partOfSpeech: "adverb", category: "Manner", example: "Ich sehe das anders.", exampleEn: "I see that differently." },
  { german: "genauso", english: "just as, equally", partOfSpeech: "adverb", category: "Manner", example: "Er ist genauso groß wie ich.", exampleEn: "He is just as tall as I am." },
  { german: "irgendwie", english: "somehow", partOfSpeech: "adverb", category: "Manner", example: "Irgendwie schaffen wir das.", exampleEn: "Somehow we will manage." },
  { german: "automatisch", english: "automatically", partOfSpeech: "adverb", category: "Manner", example: "Die Tür öffnet sich automatisch.", exampleEn: "The door opens automatically." },
  { german: "vergebens", english: "in vain", partOfSpeech: "adverb", category: "Manner", example: "Er suchte vergebens.", exampleEn: "He searched in vain." },
  { german: "auswendig", english: "by heart", partOfSpeech: "adverb", category: "Manner", example: "Ich kenne das Gedicht auswendig.", exampleEn: "I know the poem by heart." },
  { german: "gleichzeitig", english: "simultaneously", partOfSpeech: "adverb", category: "Manner", example: "Er kann gleichzeitig lesen und Musik hören.", exampleEn: "He can read and listen to music simultaneously." },
  { german: "getrennt", english: "separately", partOfSpeech: "adverb", category: "Manner", example: "Wir zahlen getrennt, bitte.", exampleEn: "We pay separately, please." },
  { german: "nacheinander", english: "one after another", partOfSpeech: "adverb", category: "Manner", example: "Die Schüler kommen nacheinander.", exampleEn: "The students come one after another." },
  { german: "nebeneinander", english: "side by side", partOfSpeech: "adverb", category: "Manner", example: "Sie sitzen nebeneinander.", exampleEn: "They sit side by side." },
  { german: "durcheinander", english: "in a mess, mixed up", partOfSpeech: "adverb", category: "Manner", example: "Alles ist durcheinander.", exampleEn: "Everything is mixed up." },
  { german: "hintereinander", english: "one behind another, in a row", partOfSpeech: "adverb", category: "Manner", example: "Sie stehen hintereinander.", exampleEn: "They stand one behind another." },
  { german: "gegenseitig", english: "mutually", partOfSpeech: "adverb", category: "Manner", example: "Wir helfen uns gegenseitig.", exampleEn: "We help each other mutually." },
  { german: "unerwartet", english: "unexpectedly", partOfSpeech: "adverb", category: "Manner", example: "Er kam unerwartet vorbei.", exampleEn: "He stopped by unexpectedly." },
  { german: "bereitwillig", english: "willingly", partOfSpeech: "adverb", category: "Manner", example: "Sie hat bereitwillig geholfen.", exampleEn: "She helped willingly." },
  { german: "kopfüber", english: "headfirst", partOfSpeech: "adverb", category: "Manner", example: "Er sprang kopfüber ins Wasser.", exampleEn: "He jumped headfirst into the water." },
  { german: "barfuß", english: "barefoot", partOfSpeech: "adverb", category: "Manner", example: "Die Kinder laufen barfuß.", exampleEn: "The children walk barefoot." },

  // ─── Degree ─────────────────────────────────────────────────────
  { german: "sehr", english: "very", partOfSpeech: "adverb", category: "Degree", example: "Das Essen ist sehr gut.", exampleEn: "The food is very good." },
  { german: "ziemlich", english: "quite, fairly", partOfSpeech: "adverb", category: "Degree", example: "Das ist ziemlich teuer.", exampleEn: "That is quite expensive." },
  { german: "besonders", english: "especially, particularly", partOfSpeech: "adverb", category: "Degree", example: "Das Dessert ist besonders lecker.", exampleEn: "The dessert is especially delicious." },
  { german: "total", english: "totally", partOfSpeech: "adverb", category: "Degree", example: "Ich bin total müde.", exampleEn: "I am totally tired." },
  { german: "völlig", english: "completely, totally", partOfSpeech: "adverb", category: "Degree", example: "Das ist völlig egal.", exampleEn: "That is completely irrelevant." },
  { german: "wirklich", english: "really", partOfSpeech: "adverb", category: "Degree", example: "Das ist wirklich schön.", exampleEn: "That is really beautiful." },
  { german: "absolut", english: "absolutely", partOfSpeech: "adverb", category: "Degree", example: "Du hast absolut recht.", exampleEn: "You are absolutely right." },
  { german: "etwas", english: "somewhat, a little", partOfSpeech: "adverb", category: "Degree", example: "Das Wasser ist etwas kalt.", exampleEn: "The water is a little cold." },
  { german: "ein bisschen", english: "a little bit", partOfSpeech: "adverb", category: "Degree", example: "Ich bin ein bisschen nervös.", exampleEn: "I am a little bit nervous." },
  { german: "kaum", english: "hardly, scarcely", partOfSpeech: "adverb", category: "Degree", example: "Ich kann es kaum glauben.", exampleEn: "I can hardly believe it." },
  { german: "fast", english: "almost, nearly", partOfSpeech: "adverb", category: "Degree", example: "Wir sind fast da.", exampleEn: "We are almost there." },
  { german: "ungefähr", english: "approximately", partOfSpeech: "adverb", category: "Degree", example: "Es dauert ungefähr eine Stunde.", exampleEn: "It takes approximately one hour." },
  { german: "mindestens", english: "at least", partOfSpeech: "adverb", category: "Degree", example: "Es dauert mindestens zwei Stunden.", exampleEn: "It takes at least two hours." },
  { german: "höchstens", english: "at most", partOfSpeech: "adverb", category: "Degree", example: "Es kostet höchstens zehn Euro.", exampleEn: "It costs at most ten euros." },
  { german: "genug", english: "enough", partOfSpeech: "adverb", category: "Degree", example: "Hast du genug gegessen?", exampleEn: "Have you eaten enough?" },
  { german: "zu", english: "too (excessive)", partOfSpeech: "adverb", category: "Degree", example: "Das ist zu teuer.", exampleEn: "That is too expensive." },
  { german: "viel", english: "much, a lot", partOfSpeech: "adverb", category: "Degree", example: "Er arbeitet viel.", exampleEn: "He works a lot." },
  { german: "wenig", english: "little", partOfSpeech: "adverb", category: "Degree", example: "Sie schläft wenig.", exampleEn: "She sleeps little." },
  { german: "mehr", english: "more", partOfSpeech: "adverb", category: "Degree", example: "Ich möchte mehr erfahren.", exampleEn: "I would like to learn more." },
  { german: "weniger", english: "less", partOfSpeech: "adverb", category: "Degree", example: "Du solltest weniger Zucker essen.", exampleEn: "You should eat less sugar." },
  { german: "am meisten", english: "the most", partOfSpeech: "adverb", category: "Degree", example: "Das hat mich am meisten überrascht.", exampleEn: "That surprised me the most." },
  { german: "am wenigsten", english: "the least", partOfSpeech: "adverb", category: "Degree", example: "Das gefällt mir am wenigsten.", exampleEn: "I like that the least." },
  { german: "erheblich", english: "considerably", partOfSpeech: "adverb", category: "Degree", example: "Die Preise sind erheblich gestiegen.", exampleEn: "The prices have risen considerably." },
  { german: "äußerst", english: "extremely", partOfSpeech: "adverb", category: "Degree", example: "Das ist äußerst wichtig.", exampleEn: "That is extremely important." },
  { german: "halbwegs", english: "halfway, reasonably", partOfSpeech: "adverb", category: "Degree", example: "Der Film war halbwegs gut.", exampleEn: "The movie was reasonably good." },
  { german: "enorm", english: "enormously", partOfSpeech: "adverb", category: "Degree", example: "Die Kosten sind enorm gestiegen.", exampleEn: "The costs have risen enormously." },
  { german: "unglaublich", english: "incredibly", partOfSpeech: "adverb", category: "Degree", example: "Sie ist unglaublich schnell.", exampleEn: "She is incredibly fast." },
  { german: "extrem", english: "extremely", partOfSpeech: "adverb", category: "Degree", example: "Das Wetter ist extrem heiß.", exampleEn: "The weather is extremely hot." },
  { german: "übermäßig", english: "excessively", partOfSpeech: "adverb", category: "Degree", example: "Er isst übermäßig viel.", exampleEn: "He eats excessively much." },
  { german: "ausreichend", english: "sufficiently", partOfSpeech: "adverb", category: "Degree", example: "Hast du ausreichend getrunken?", exampleEn: "Did you drink sufficiently?" },
  { german: "einigermaßen", english: "to some extent, fairly", partOfSpeech: "adverb", category: "Degree", example: "Ich verstehe es einigermaßen.", exampleEn: "I understand it to some extent." },
  { german: "weitgehend", english: "largely, to a great extent", partOfSpeech: "adverb", category: "Degree", example: "Das Projekt ist weitgehend fertig.", exampleEn: "The project is largely finished." },
  { german: "bei weitem", english: "by far", partOfSpeech: "adverb", category: "Degree", example: "Das ist bei weitem das Beste.", exampleEn: "That is by far the best." },
  { german: "eher", english: "rather, more likely", partOfSpeech: "adverb", category: "Degree", example: "Das ist eher unwahrscheinlich.", exampleEn: "That is rather unlikely." },
  { german: "durchaus", english: "quite, certainly", partOfSpeech: "adverb", category: "Degree", example: "Das ist durchaus möglich.", exampleEn: "That is quite possible." },

  // ─── Negation ───────────────────────────────────────────────────
  { german: "nicht", english: "not", partOfSpeech: "adverb", category: "Negation", example: "Ich bin nicht müde.", exampleEn: "I am not tired." },
  { german: "gar nicht", english: "not at all", partOfSpeech: "adverb", category: "Negation", example: "Das gefällt mir gar nicht.", exampleEn: "I do not like that at all." },
  { german: "überhaupt nicht", english: "not at all (emphatic)", partOfSpeech: "adverb", category: "Negation", example: "Ich bin überhaupt nicht überrascht.", exampleEn: "I am not surprised at all." },
  { german: "nicht mehr", english: "no longer, not anymore", partOfSpeech: "adverb", category: "Negation", example: "Er wohnt nicht mehr hier.", exampleEn: "He no longer lives here." },
  { german: "noch nicht", english: "not yet", partOfSpeech: "adverb", category: "Negation", example: "Ich habe noch nicht gegessen.", exampleEn: "I have not eaten yet." },
  { german: "keinesfalls", english: "by no means, in no case", partOfSpeech: "adverb", category: "Negation", example: "Das darf keinesfalls passieren.", exampleEn: "That must by no means happen." },
  { german: "keineswegs", english: "by no means, not at all", partOfSpeech: "adverb", category: "Negation", example: "Das ist keineswegs einfach.", exampleEn: "That is by no means easy." },
  { german: "nirgends", english: "nowhere", partOfSpeech: "adverb", category: "Negation", example: "Er ist nirgends zu finden.", exampleEn: "He is nowhere to be found." },
  { german: "weder ... noch", english: "neither ... nor", partOfSpeech: "adverb", category: "Negation", example: "Er trinkt weder Kaffee noch Tee.", exampleEn: "He drinks neither coffee nor tea." },
  { german: "kaum", english: "barely, hardly", partOfSpeech: "adverb", category: "Negation", example: "Ich konnte ihn kaum verstehen.", exampleEn: "I could barely understand him." },

  // ─── Question ───────────────────────────────────────────────────
  { german: "wo", english: "where", partOfSpeech: "adverb", category: "Question", example: "Wo wohnst du?", exampleEn: "Where do you live?" },
  { german: "wann", english: "when", partOfSpeech: "adverb", category: "Question", example: "Wann kommst du?", exampleEn: "When are you coming?" },
  { german: "wie", english: "how", partOfSpeech: "adverb", category: "Question", example: "Wie geht es dir?", exampleEn: "How are you?" },
  { german: "warum", english: "why", partOfSpeech: "adverb", category: "Question", example: "Warum bist du traurig?", exampleEn: "Why are you sad?" },
  { german: "wieso", english: "why, how come", partOfSpeech: "adverb", category: "Question", example: "Wieso bist du so spät?", exampleEn: "How come you are so late?" },
  { german: "weshalb", english: "why, for what reason", partOfSpeech: "adverb", category: "Question", example: "Weshalb hast du das gemacht?", exampleEn: "Why did you do that?" },
  { german: "woher", english: "from where", partOfSpeech: "adverb", category: "Question", example: "Woher kommst du?", exampleEn: "Where do you come from?" },
  { german: "wohin", english: "where to", partOfSpeech: "adverb", category: "Question", example: "Wohin fährst du im Urlaub?", exampleEn: "Where are you going on vacation?" },
  { german: "wie lange", english: "how long", partOfSpeech: "adverb", category: "Question", example: "Wie lange dauert die Fahrt?", exampleEn: "How long does the trip take?" },
  { german: "wie oft", english: "how often", partOfSpeech: "adverb", category: "Question", example: "Wie oft gehst du ins Fitnessstudio?", exampleEn: "How often do you go to the gym?" },
  { german: "wie viel", english: "how much", partOfSpeech: "adverb", category: "Question", example: "Wie viel kostet das?", exampleEn: "How much does that cost?" },
  { german: "wie weit", english: "how far", partOfSpeech: "adverb", category: "Question", example: "Wie weit ist es bis München?", exampleEn: "How far is it to Munich?" },
  { german: "wievielmal", english: "how many times", partOfSpeech: "adverb", category: "Question", example: "Wievielmal warst du schon dort?", exampleEn: "How many times have you been there?" },
  { german: "wobei", english: "whereby, in what", partOfSpeech: "adverb", category: "Question", example: "Wobei kann ich dir helfen?", exampleEn: "How can I help you?" },
  { german: "worüber", english: "about what", partOfSpeech: "adverb", category: "Question", example: "Worüber sprecht ihr?", exampleEn: "What are you talking about?" },
  { german: "wofür", english: "for what, what for", partOfSpeech: "adverb", category: "Question", example: "Wofür brauchst du das?", exampleEn: "What do you need that for?" },
  { german: "womit", english: "with what", partOfSpeech: "adverb", category: "Question", example: "Womit hast du das gemacht?", exampleEn: "What did you do that with?" },
  { german: "wozu", english: "what for, to what purpose", partOfSpeech: "adverb", category: "Question", example: "Wozu brauchst du so viel Geld?", exampleEn: "What do you need so much money for?" },

  // ─── Sentence ───────────────────────────────────────────────────
  { german: "also", english: "so, therefore", partOfSpeech: "adverb", category: "Sentence", example: "Also, was machen wir jetzt?", exampleEn: "So, what do we do now?" },
  { german: "außerdem", english: "besides, moreover", partOfSpeech: "adverb", category: "Sentence", example: "Außerdem habe ich keine Zeit.", exampleEn: "Besides, I have no time." },
  { german: "trotzdem", english: "nevertheless, anyway", partOfSpeech: "adverb", category: "Sentence", example: "Es regnet, trotzdem gehe ich spazieren.", exampleEn: "It is raining, nevertheless I am going for a walk." },
  { german: "deshalb", english: "therefore, that's why", partOfSpeech: "adverb", category: "Sentence", example: "Er ist krank, deshalb bleibt er zu Hause.", exampleEn: "He is sick, therefore he stays at home." },
  { german: "deswegen", english: "for that reason, because of that", partOfSpeech: "adverb", category: "Sentence", example: "Deswegen habe ich angerufen.", exampleEn: "That's why I called." },
  { german: "daher", english: "therefore, hence", partOfSpeech: "adverb", category: "Sentence", example: "Ich bin müde, daher gehe ich früh ins Bett.", exampleEn: "I am tired, therefore I go to bed early." },
  { german: "allerdings", english: "however, though", partOfSpeech: "adverb", category: "Sentence", example: "Das Restaurant ist gut, allerdings teuer.", exampleEn: "The restaurant is good, however expensive." },
  { german: "schließlich", english: "finally, after all", partOfSpeech: "adverb", category: "Sentence", example: "Schließlich hat er zugestimmt.", exampleEn: "Finally he agreed." },
  { german: "wahrscheinlich", english: "probably", partOfSpeech: "adverb", category: "Sentence", example: "Er kommt wahrscheinlich morgen.", exampleEn: "He is probably coming tomorrow." },
  { german: "vielleicht", english: "maybe, perhaps", partOfSpeech: "adverb", category: "Sentence", example: "Vielleicht regnet es morgen.", exampleEn: "Maybe it will rain tomorrow." },
  { german: "bestimmt", english: "certainly, definitely", partOfSpeech: "adverb", category: "Sentence", example: "Er kommt bestimmt.", exampleEn: "He will definitely come." },
  { german: "sicher", english: "certainly, surely", partOfSpeech: "adverb", category: "Sentence", example: "Das ist sicher richtig.", exampleEn: "That is surely correct." },
  { german: "natürlich", english: "of course, naturally", partOfSpeech: "adverb", category: "Sentence", example: "Natürlich helfe ich dir.", exampleEn: "Of course I will help you." },
  { german: "selbstverständlich", english: "of course, naturally", partOfSpeech: "adverb", category: "Sentence", example: "Selbstverständlich können Sie kommen.", exampleEn: "Of course you may come." },
  { german: "tatsächlich", english: "actually, in fact", partOfSpeech: "adverb", category: "Sentence", example: "Er hat es tatsächlich geschafft.", exampleEn: "He actually managed it." },
  { german: "eigentlich", english: "actually, really", partOfSpeech: "adverb", category: "Sentence", example: "Eigentlich wollte ich zu Hause bleiben.", exampleEn: "Actually I wanted to stay at home." },
  { german: "übrigens", english: "by the way", partOfSpeech: "adverb", category: "Sentence", example: "Übrigens, hast du morgen Zeit?", exampleEn: "By the way, do you have time tomorrow?" },
  { german: "jedenfalls", english: "in any case, anyway", partOfSpeech: "adverb", category: "Sentence", example: "Jedenfalls bin ich froh.", exampleEn: "In any case I am glad." },
  { german: "sozusagen", english: "so to speak", partOfSpeech: "adverb", category: "Sentence", example: "Er ist sozusagen der Chef.", exampleEn: "He is the boss, so to speak." },
  { german: "angeblich", english: "allegedly, supposedly", partOfSpeech: "adverb", category: "Sentence", example: "Er ist angeblich krank.", exampleEn: "He is allegedly sick." },
  { german: "offenbar", english: "apparently, evidently", partOfSpeech: "adverb", category: "Sentence", example: "Er hat offenbar keine Lust.", exampleEn: "Apparently he has no desire." },
  { german: "anscheinend", english: "apparently", partOfSpeech: "adverb", category: "Sentence", example: "Anscheinend hat er keine Zeit.", exampleEn: "Apparently he has no time." },
  { german: "vermutlich", english: "presumably, probably", partOfSpeech: "adverb", category: "Sentence", example: "Er ist vermutlich schon weg.", exampleEn: "He is presumably already gone." },
  { german: "leider", english: "unfortunately", partOfSpeech: "adverb", category: "Sentence", example: "Leider kann ich nicht kommen.", exampleEn: "Unfortunately I cannot come." },
  { german: "glücklicherweise", english: "fortunately", partOfSpeech: "adverb", category: "Sentence", example: "Glücklicherweise war niemand verletzt.", exampleEn: "Fortunately no one was injured." },
  { german: "hoffentlich", english: "hopefully", partOfSpeech: "adverb", category: "Sentence", example: "Hoffentlich scheint morgen die Sonne.", exampleEn: "Hopefully the sun will shine tomorrow." },
  { german: "offensichtlich", english: "obviously", partOfSpeech: "adverb", category: "Sentence", example: "Er ist offensichtlich zufrieden.", exampleEn: "He is obviously satisfied." },
  { german: "selbst", english: "oneself, even", partOfSpeech: "adverb", category: "Sentence", example: "Selbst er war überrascht.", exampleEn: "Even he was surprised." },
  { german: "sogar", english: "even", partOfSpeech: "adverb", category: "Sentence", example: "Sogar die Kinder haben geholfen.", exampleEn: "Even the children helped." },
  { german: "jedoch", english: "however", partOfSpeech: "adverb", category: "Sentence", example: "Er wollte kommen, jedoch war er krank.", exampleEn: "He wanted to come, however he was sick." },
  { german: "dennoch", english: "nevertheless, still", partOfSpeech: "adverb", category: "Sentence", example: "Es war schwer, dennoch haben wir es geschafft.", exampleEn: "It was hard, nevertheless we managed." },
  { german: "hingegen", english: "on the other hand", partOfSpeech: "adverb", category: "Sentence", example: "Er ist groß, sie hingegen ist klein.", exampleEn: "He is tall, she on the other hand is small." },
  { german: "stattdessen", english: "instead", partOfSpeech: "adverb", category: "Sentence", example: "Wir fahren nicht nach Italien, stattdessen bleiben wir zu Hause.", exampleEn: "We are not going to Italy, instead we are staying home." },
  { german: "beispielsweise", english: "for example", partOfSpeech: "adverb", category: "Sentence", example: "Man kann beispielsweise den Bus nehmen.", exampleEn: "For example, one can take the bus." },
  { german: "insgesamt", english: "overall, altogether", partOfSpeech: "adverb", category: "Sentence", example: "Insgesamt war es ein guter Tag.", exampleEn: "Overall it was a good day." },
  { german: "grundsätzlich", english: "fundamentally, in principle", partOfSpeech: "adverb", category: "Sentence", example: "Grundsätzlich stimme ich zu.", exampleEn: "In principle I agree." },
  { german: "folglich", english: "consequently", partOfSpeech: "adverb", category: "Sentence", example: "Er hat nicht gelernt, folglich hat er die Prüfung nicht bestanden.", exampleEn: "He did not study, consequently he did not pass the exam." },
  { german: "demzufolge", english: "accordingly, therefore", partOfSpeech: "adverb", category: "Sentence", example: "Demzufolge müssen wir den Plan ändern.", exampleEn: "Accordingly we must change the plan." },
  { german: "zweifellos", english: "undoubtedly", partOfSpeech: "adverb", category: "Sentence", example: "Er ist zweifellos ein guter Arzt.", exampleEn: "He is undoubtedly a good doctor." },
  { german: "zugegebenermaßen", english: "admittedly", partOfSpeech: "adverb", category: "Sentence", example: "Zugegebenermaßen war es mein Fehler.", exampleEn: "Admittedly it was my mistake." },
  { german: "gewissermaßen", english: "in a way, to a certain extent", partOfSpeech: "adverb", category: "Sentence", example: "Er hat gewissermaßen recht.", exampleEn: "He is right in a way." },
  { german: "kurz gesagt", english: "in short", partOfSpeech: "adverb", category: "Sentence", example: "Kurz gesagt, wir brauchen mehr Geld.", exampleEn: "In short, we need more money." },
  { german: "im Grunde", english: "basically", partOfSpeech: "adverb", category: "Sentence", example: "Im Grunde hast du recht.", exampleEn: "Basically you are right." },
  { german: "bekanntlich", english: "as is well known", partOfSpeech: "adverb", category: "Sentence", example: "Bekanntlich ist Berlin die Hauptstadt.", exampleEn: "As is well known, Berlin is the capital." },
  { german: "nämlich", english: "namely, you see", partOfSpeech: "adverb", category: "Sentence", example: "Ich komme nicht, ich bin nämlich krank.", exampleEn: "I am not coming, you see I am sick." },
  { german: "freilich", english: "of course, admittedly", partOfSpeech: "adverb", category: "Sentence", example: "Freilich hat er recht.", exampleEn: "Of course he is right." },
  { german: "immerhin", english: "at least, after all", partOfSpeech: "adverb", category: "Sentence", example: "Immerhin hat er sich entschuldigt.", exampleEn: "At least he apologized." },
  { german: "dafür", english: "for that, in return", partOfSpeech: "adverb", category: "Sentence", example: "Das Hotel ist klein, dafür aber günstig.", exampleEn: "The hotel is small, but cheap in return." },
  { german: "dagegen", english: "against that, on the other hand", partOfSpeech: "adverb", category: "Sentence", example: "Ich habe nichts dagegen.", exampleEn: "I have nothing against that." },
  { german: "darüber hinaus", english: "moreover, furthermore", partOfSpeech: "adverb", category: "Sentence", example: "Darüber hinaus gibt es noch andere Probleme.", exampleEn: "Moreover there are other problems." },
  { german: "letzten Endes", english: "ultimately, in the end", partOfSpeech: "adverb", category: "Sentence", example: "Letzten Endes hat er sich entschieden.", exampleEn: "Ultimately he made up his mind." },
  { german: "im Gegenteil", english: "on the contrary", partOfSpeech: "adverb", category: "Sentence", example: "Nein, im Gegenteil, ich finde es toll.", exampleEn: "No, on the contrary, I think it's great." },
  { german: "im Allgemeinen", english: "in general, generally", partOfSpeech: "adverb", category: "Sentence", example: "Im Allgemeinen bin ich zufrieden.", exampleEn: "In general I am satisfied." },
  { german: "hauptsächlich", english: "mainly, primarily", partOfSpeech: "adverb", category: "Sentence", example: "Ich esse hauptsächlich vegetarisch.", exampleEn: "I eat mainly vegetarian." },
  { german: "nebenbei", english: "on the side, incidentally", partOfSpeech: "adverb", category: "Sentence", example: "Nebenbei bemerkt, das Essen war gut.", exampleEn: "Incidentally, the food was good." },
  { german: "abgesehen davon", english: "apart from that", partOfSpeech: "adverb", category: "Sentence", example: "Abgesehen davon war alles in Ordnung.", exampleEn: "Apart from that, everything was fine." },
  { german: "kurzum", english: "in short, in a word", partOfSpeech: "adverb", category: "Sentence", example: "Kurzum, es war ein guter Tag.", exampleEn: "In short, it was a good day." },
  { german: "zusammenfassend", english: "in summary", partOfSpeech: "adverb", category: "Sentence", example: "Zusammenfassend war das Projekt erfolgreich.", exampleEn: "In summary, the project was successful." },

  // ─── Additional Manner ──────────────────────────────────────────
  { german: "blindlings", english: "blindly", partOfSpeech: "adverb", category: "Manner", example: "Er folgte ihr blindlings.", exampleEn: "He followed her blindly." },
  { german: "hastig", english: "hastily", partOfSpeech: "adverb", category: "Manner", example: "Er aß hastig sein Frühstück.", exampleEn: "He hastily ate his breakfast." },
  { german: "gründlich", english: "thoroughly", partOfSpeech: "adverb", category: "Manner", example: "Er hat gründlich geputzt.", exampleEn: "He cleaned thoroughly." },
  { german: "mühsam", english: "laboriously, with difficulty", partOfSpeech: "adverb", category: "Manner", example: "Er kletterte mühsam den Berg hinauf.", exampleEn: "He laboriously climbed up the mountain." },
  { german: "mühelos", english: "effortlessly", partOfSpeech: "adverb", category: "Manner", example: "Sie hat die Prüfung mühelos bestanden.", exampleEn: "She passed the exam effortlessly." },
  { german: "aufmerksam", english: "attentively", partOfSpeech: "adverb", category: "Manner", example: "Sie hörte aufmerksam zu.", exampleEn: "She listened attentively." },
  { german: "widerwillig", english: "reluctantly", partOfSpeech: "adverb", category: "Manner", example: "Er stimmte widerwillig zu.", exampleEn: "He reluctantly agreed." },
  { german: "behutsam", english: "cautiously, gently", partOfSpeech: "adverb", category: "Manner", example: "Sie nahm das Baby behutsam auf den Arm.", exampleEn: "She carefully picked up the baby." },
  { german: "ruhig", english: "calmly", partOfSpeech: "adverb", category: "Manner", example: "Bitte bleib ruhig.", exampleEn: "Please stay calm." },
  { german: "heftig", english: "violently, intensely", partOfSpeech: "adverb", category: "Manner", example: "Es hat heftig geregnet.", exampleEn: "It rained heavily." },
  { german: "fließend", english: "fluently", partOfSpeech: "adverb", category: "Manner", example: "Sie spricht fließend Französisch.", exampleEn: "She speaks French fluently." },
  { german: "verständlich", english: "understandably", partOfSpeech: "adverb", category: "Manner", example: "Er war verständlich aufgeregt.", exampleEn: "He was understandably excited." },
  { german: "unauffällig", english: "inconspicuously", partOfSpeech: "adverb", category: "Manner", example: "Er verließ unauffällig den Raum.", exampleEn: "He inconspicuously left the room." },
  { german: "planmäßig", english: "according to plan, on schedule", partOfSpeech: "adverb", category: "Manner", example: "Der Zug fährt planmäßig.", exampleEn: "The train runs on schedule." },
  { german: "zufällig", english: "by chance, accidentally", partOfSpeech: "adverb", category: "Manner", example: "Wir haben uns zufällig getroffen.", exampleEn: "We met by chance." },
  { german: "ausdrücklich", english: "explicitly, expressly", partOfSpeech: "adverb", category: "Manner", example: "Er hat es ausdrücklich verboten.", exampleEn: "He explicitly forbade it." },
  { german: "stillschweigend", english: "silently, tacitly", partOfSpeech: "adverb", category: "Manner", example: "Sie hat es stillschweigend akzeptiert.", exampleEn: "She tacitly accepted it." },
  { german: "schrittweise", english: "step by step, gradually", partOfSpeech: "adverb", category: "Manner", example: "Wir gehen schrittweise vor.", exampleEn: "We proceed step by step." },

  // ─── Additional Time ────────────────────────────────────────────
  { german: "währenddessen", english: "meanwhile, in the meantime", partOfSpeech: "adverb", category: "Time", example: "Währenddessen kochte sie das Essen.", exampleEn: "Meanwhile she cooked the food." },
  { german: "hinterher", english: "afterwards", partOfSpeech: "adverb", category: "Time", example: "Hinterher sind wir ins Kino gegangen.", exampleEn: "Afterwards we went to the cinema." },
  { german: "zwischendurch", english: "in between, now and then", partOfSpeech: "adverb", category: "Time", example: "Zwischendurch mache ich eine Pause.", exampleEn: "In between I take a break." },
  { german: "unterdessen", english: "in the meantime", partOfSpeech: "adverb", category: "Time", example: "Unterdessen warteten wir im Auto.", exampleEn: "In the meantime we waited in the car." },
  { german: "unverzüglich", english: "immediately, without delay", partOfSpeech: "adverb", category: "Time", example: "Bitte antworten Sie unverzüglich.", exampleEn: "Please reply immediately." },
  { german: "längst", english: "long since, long ago", partOfSpeech: "adverb", category: "Time", example: "Das hätte längst erledigt sein müssen.", exampleEn: "That should have been done long ago." },

  // ─── Additional Degree ──────────────────────────────────────────
  { german: "überaus", english: "exceedingly, highly", partOfSpeech: "adverb", category: "Degree", example: "Sie ist überaus talentiert.", exampleEn: "She is exceedingly talented." },
  { german: "geradezu", english: "virtually, practically", partOfSpeech: "adverb", category: "Degree", example: "Das ist geradezu unmöglich.", exampleEn: "That is virtually impossible." },
  { german: "nahezu", english: "nearly, almost", partOfSpeech: "adverb", category: "Degree", example: "Nahezu alle waren anwesend.", exampleEn: "Nearly everyone was present." },
  { german: "beinahe", english: "almost, nearly", partOfSpeech: "adverb", category: "Degree", example: "Ich hätte beinahe den Bus verpasst.", exampleEn: "I almost missed the bus." },
  { german: "restlos", english: "completely, without remainder", partOfSpeech: "adverb", category: "Degree", example: "Ich bin restlos begeistert.", exampleEn: "I am completely thrilled." },
  { german: "teilweise", english: "partially, partly", partOfSpeech: "adverb", category: "Degree", example: "Das Gebäude wurde teilweise zerstört.", exampleEn: "The building was partially destroyed." },
  { german: "größtenteils", english: "for the most part", partOfSpeech: "adverb", category: "Degree", example: "Die Arbeit ist größtenteils erledigt.", exampleEn: "The work is done for the most part." },
  { german: "wesentlich", english: "considerably, significantly", partOfSpeech: "adverb", category: "Degree", example: "Das ist wesentlich besser.", exampleEn: "That is considerably better." },
  { german: "annähernd", english: "approximately, nearly", partOfSpeech: "adverb", category: "Degree", example: "Es waren annähernd hundert Leute da.", exampleEn: "There were approximately a hundred people there." },

  // ─── Additional Place ───────────────────────────────────────────
  { german: "hierzulande", english: "in this country, here", partOfSpeech: "adverb", category: "Place", example: "Hierzulande ist das Wetter mild.", exampleEn: "In this country the weather is mild." },
  { german: "bergauf", english: "uphill", partOfSpeech: "adverb", category: "Place", example: "Der Weg geht bergauf.", exampleEn: "The path goes uphill." },
  { german: "bergab", english: "downhill", partOfSpeech: "adverb", category: "Place", example: "Es geht bergab zum See.", exampleEn: "It goes downhill to the lake." },
  { german: "stromaufwärts", english: "upstream", partOfSpeech: "adverb", category: "Place", example: "Das Boot fuhr stromaufwärts.", exampleEn: "The boat went upstream." },
  { german: "stromabwärts", english: "downstream", partOfSpeech: "adverb", category: "Place", example: "Wir schwammen stromabwärts.", exampleEn: "We swam downstream." },
  { german: "landeinwärts", english: "inland", partOfSpeech: "adverb", category: "Place", example: "Das Dorf liegt landeinwärts.", exampleEn: "The village is inland." },
  { german: "beiseite", english: "aside", partOfSpeech: "adverb", category: "Place", example: "Er legte das Buch beiseite.", exampleEn: "He put the book aside." },
  { german: "ringsum", english: "all around", partOfSpeech: "adverb", category: "Place", example: "Ringsum standen Bäume.", exampleEn: "All around stood trees." },
];
