import type { VocabWordBase } from "../german-types";

export const EXPANDED_CONJUNCTIONS: VocabWordBase[] = [
  // ─── Coordinating (Konjunktionen) ──────────────────────────────
  {
    german: "und",
    english: "and",
    partOfSpeech: "conjunction",
    category: "Coordinating",
    example: "Ich lese und er schreibt.",
    exampleEn: "I read and he writes.",
  },
  {
    german: "oder",
    english: "or",
    partOfSpeech: "conjunction",
    category: "Coordinating",
    example: "Möchtest du Tee oder Kaffee?",
    exampleEn: "Would you like tea or coffee?",
  },
  {
    german: "aber",
    english: "but",
    partOfSpeech: "conjunction",
    category: "Coordinating",
    example: "Ich bin müde, aber ich muss noch arbeiten.",
    exampleEn: "I am tired, but I still have to work.",
  },
  {
    german: "denn",
    english: "because; for",
    partOfSpeech: "conjunction",
    category: "Coordinating",
    example: "Ich bleibe zu Hause, denn es regnet.",
    exampleEn: "I stay at home because it is raining.",
  },
  {
    german: "sondern",
    english: "but rather; but instead",
    partOfSpeech: "conjunction",
    category: "Coordinating",
    example: "Er ist nicht krank, sondern nur müde.",
    exampleEn: "He is not sick, but rather just tired.",
  },
  {
    german: "doch",
    english: "but; however; yet",
    partOfSpeech: "conjunction",
    category: "Coordinating",
    example: "Er wollte kommen, doch er hatte keine Zeit.",
    exampleEn: "He wanted to come, but he had no time.",
  },
  {
    german: "jedoch",
    english: "however; yet",
    partOfSpeech: "conjunction",
    category: "Coordinating",
    example: "Das Essen war teuer, jedoch sehr gut.",
    exampleEn: "The food was expensive, yet very good.",
  },

  // ─── Subordinating (Subjunktionen) ─────────────────────────────
  {
    german: "weil",
    english: "because",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Ich lerne Deutsch, weil ich in Berlin wohne.",
    exampleEn: "I learn German because I live in Berlin.",
  },
  {
    german: "dass",
    english: "that",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Ich weiß, dass du Recht hast.",
    exampleEn: "I know that you are right.",
  },
  {
    german: "wenn",
    english: "if; when (present/future)",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Wenn es regnet, bleibe ich zu Hause.",
    exampleEn: "If it rains, I stay at home.",
  },
  {
    german: "als",
    english: "when (past, single event)",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Als ich klein war, lebte ich auf dem Land.",
    exampleEn: "When I was little, I lived in the countryside.",
  },
  {
    german: "ob",
    english: "whether; if",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Ich frage mich, ob er kommt.",
    exampleEn: "I wonder whether he is coming.",
  },
  {
    german: "obwohl",
    english: "although; even though",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Obwohl es kalt ist, gehe ich joggen.",
    exampleEn: "Although it is cold, I go jogging.",
  },
  {
    german: "damit",
    english: "so that; in order that",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Ich spare Geld, damit ich reisen kann.",
    exampleEn: "I save money so that I can travel.",
  },
  {
    german: "bevor",
    english: "before",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Bevor ich esse, wasche ich mir die Hände.",
    exampleEn: "Before I eat, I wash my hands.",
  },
  {
    german: "nachdem",
    english: "after",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Nachdem ich gegessen habe, gehe ich spazieren.",
    exampleEn: "After I have eaten, I go for a walk.",
  },
  {
    german: "während",
    english: "while; during",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Während ich koche, hört er Musik.",
    exampleEn: "While I cook, he listens to music.",
  },
  {
    german: "bis",
    english: "until",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Warte hier, bis ich zurückkomme.",
    exampleEn: "Wait here until I come back.",
  },
  {
    german: "seit/seitdem",
    english: "since (time)",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Seitdem ich hier wohne, fühle ich mich wohl.",
    exampleEn: "Since I have lived here, I feel comfortable.",
  },
  {
    german: "falls",
    english: "in case; if",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Falls du Hilfe brauchst, ruf mich an.",
    exampleEn: "In case you need help, call me.",
  },
  {
    german: "sobald",
    english: "as soon as",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Sobald ich fertig bin, komme ich zu dir.",
    exampleEn: "As soon as I am done, I will come to you.",
  },
  {
    german: "solange",
    english: "as long as",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Solange du lernst, darfst du hier bleiben.",
    exampleEn: "As long as you study, you may stay here.",
  },
  {
    german: "obgleich",
    english: "although; even though",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Obgleich er müde war, arbeitete er weiter.",
    exampleEn: "Although he was tired, he kept working.",
  },
  {
    german: "indem",
    english: "by (doing something)",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Man lernt, indem man Fehler macht.",
    exampleEn: "You learn by making mistakes.",
  },
  {
    german: "sodass",
    english: "so that (result)",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Er sprach laut, sodass alle ihn hören konnten.",
    exampleEn: "He spoke loudly so that everyone could hear him.",
  },
  {
    german: "ehe",
    english: "before",
    partOfSpeech: "conjunction",
    category: "Subordinating",
    example: "Ehe du gehst, sag mir Bescheid.",
    exampleEn: "Before you leave, let me know.",
  },

  // ─── Correlative (Doppelkonjunktionen) ─────────────────────────
  {
    german: "entweder...oder",
    english: "either...or",
    partOfSpeech: "conjunction",
    category: "Correlative",
    example: "Entweder kommst du mit oder du bleibst hier.",
    exampleEn: "Either you come along or you stay here.",
  },
  {
    german: "weder...noch",
    english: "neither...nor",
    partOfSpeech: "conjunction",
    category: "Correlative",
    example: "Er trinkt weder Kaffee noch Tee.",
    exampleEn: "He drinks neither coffee nor tea.",
  },
  {
    german: "sowohl...als auch",
    english: "both...and",
    partOfSpeech: "conjunction",
    category: "Correlative",
    example: "Sie spricht sowohl Deutsch als auch Englisch.",
    exampleEn: "She speaks both German and English.",
  },
  {
    german: "nicht nur...sondern auch",
    english: "not only...but also",
    partOfSpeech: "conjunction",
    category: "Correlative",
    example: "Er ist nicht nur klug, sondern auch fleißig.",
    exampleEn: "He is not only smart but also hardworking.",
  },
  {
    german: "je...desto",
    english: "the...the (comparative)",
    partOfSpeech: "conjunction",
    category: "Correlative",
    example: "Je mehr ich lerne, desto besser verstehe ich es.",
    exampleEn: "The more I learn, the better I understand it.",
  },
  {
    german: "zwar...aber",
    english: "indeed...but; it's true...but",
    partOfSpeech: "conjunction",
    category: "Correlative",
    example: "Er ist zwar jung, aber sehr erfahren.",
    exampleEn: "He is indeed young, but very experienced.",
  },
];
