import type { VocabWordBase } from "../german-types";

export const EXPANDED_NOUNS: VocabWordBase[] = [
  // ─── People ───────────────────────────────────────────────────────
  { german: "Lehrer", english: "teacher (male)", article: "der", partOfSpeech: "noun", category: "People", example: "Der Lehrer erklärt die Aufgabe.", exampleEn: "The teacher explains the task." },
  { german: "Lehrerin", english: "teacher (female)", article: "die", partOfSpeech: "noun", category: "People", example: "Die Lehrerin ist sehr geduldig.", exampleEn: "The teacher is very patient." },
  { german: "Arzt", english: "doctor (male)", article: "der", partOfSpeech: "noun", category: "People", example: "Der Arzt untersucht den Patienten.", exampleEn: "The doctor examines the patient." },
  { german: "Ärztin", english: "doctor (female)", article: "die", partOfSpeech: "noun", category: "People", example: "Die Ärztin arbeitet im Krankenhaus.", exampleEn: "The doctor works in the hospital." },
  { german: "Nachbar", english: "neighbor (male)", article: "der", partOfSpeech: "noun", category: "People", weakNoun: true, example: "Mein Nachbar ist sehr freundlich.", exampleEn: "My neighbor is very friendly." },
  { german: "Nachbarin", english: "neighbor (female)", article: "die", partOfSpeech: "noun", category: "People", example: "Die Nachbarin hat einen Hund.", exampleEn: "The neighbor has a dog." },
  { german: "Mensch", english: "person / human", article: "der", partOfSpeech: "noun", category: "People", weakNoun: true, example: "Jeder Mensch ist anders.", exampleEn: "Every person is different." },
  { german: "Leute", english: "people", article: "die", partOfSpeech: "noun", category: "People", example: "Viele Leute warten an der Haltestelle.", exampleEn: "Many people are waiting at the stop." },
  { german: "Gast", english: "guest", article: "der", partOfSpeech: "noun", category: "People", example: "Der Gast kommt um acht Uhr.", exampleEn: "The guest arrives at eight o'clock." },
  { german: "Chef", english: "boss", article: "der", partOfSpeech: "noun", category: "People", example: "Der Chef hat eine Besprechung.", exampleEn: "The boss has a meeting." },
  { german: "Kollege", english: "colleague (male)", article: "der", partOfSpeech: "noun", category: "People", weakNoun: true, example: "Mein Kollege hilft mir oft.", exampleEn: "My colleague often helps me." },
  { german: "Kollegin", english: "colleague (female)", article: "die", partOfSpeech: "noun", category: "People", example: "Die Kollegin bringt Kuchen mit.", exampleEn: "The colleague is bringing cake." },
  { german: "Kunde", english: "customer (male)", article: "der", partOfSpeech: "noun", category: "People", weakNoun: true, example: "Der Kunde möchte bezahlen.", exampleEn: "The customer would like to pay." },
  { german: "Kundin", english: "customer (female)", article: "die", partOfSpeech: "noun", category: "People", example: "Die Kundin sucht ein Geschenk.", exampleEn: "The customer is looking for a gift." },
  { german: "Polizist", english: "police officer (male)", article: "der", partOfSpeech: "noun", category: "People", weakNoun: true, example: "Der Polizist regelt den Verkehr.", exampleEn: "The police officer directs traffic." },
  { german: "Spieler", english: "player", article: "der", partOfSpeech: "noun", category: "People", example: "Der Spieler schießt ein Tor.", exampleEn: "The player scores a goal." },
  { german: "Besucher", english: "visitor", article: "der", partOfSpeech: "noun", category: "People", example: "Der Besucher schaut sich das Museum an.", exampleEn: "The visitor is looking at the museum." },
  { german: "Teilnehmer", english: "participant", article: "der", partOfSpeech: "noun", category: "People", example: "Alle Teilnehmer bekommen ein Zertifikat.", exampleEn: "All participants receive a certificate." },
  { german: "Fahrer", english: "driver", article: "der", partOfSpeech: "noun", category: "People", example: "Der Fahrer wartet im Auto.", exampleEn: "The driver is waiting in the car." },
  { german: "Schüler", english: "student (school, male)", article: "der", partOfSpeech: "noun", category: "People", example: "Der Schüler macht seine Hausaufgaben.", exampleEn: "The student does his homework." },
  { german: "Schülerin", english: "student (school, female)", article: "die", partOfSpeech: "noun", category: "People", example: "Die Schülerin liest ein Buch.", exampleEn: "The student is reading a book." },

  // ─── Family ───────────────────────────────────────────────────────
  { german: "Eltern", english: "parents", article: "die", partOfSpeech: "noun", category: "Family", example: "Meine Eltern leben in Berlin.", exampleEn: "My parents live in Berlin." },
  { german: "Großvater", english: "grandfather", article: "der", partOfSpeech: "noun", category: "Family", example: "Mein Großvater erzählt gerne Geschichten.", exampleEn: "My grandfather likes to tell stories." },
  { german: "Großmutter", english: "grandmother", article: "die", partOfSpeech: "noun", category: "Family", example: "Meine Großmutter kocht sehr gut.", exampleEn: "My grandmother cooks very well." },
  { german: "Enkel", english: "grandchild / grandson", article: "der", partOfSpeech: "noun", category: "Family", example: "Der Enkel besucht seine Oma.", exampleEn: "The grandchild visits his grandma." },
  { german: "Onkel", english: "uncle", article: "der", partOfSpeech: "noun", category: "Family", example: "Mein Onkel wohnt in Hamburg.", exampleEn: "My uncle lives in Hamburg." },
  { german: "Tante", english: "aunt", article: "die", partOfSpeech: "noun", category: "Family", example: "Meine Tante hat drei Kinder.", exampleEn: "My aunt has three children." },
  { german: "Cousin", english: "cousin (male)", article: "der", partOfSpeech: "noun", category: "Family", example: "Mein Cousin studiert Medizin.", exampleEn: "My cousin is studying medicine." },
  { german: "Cousine", english: "cousin (female)", article: "die", partOfSpeech: "noun", category: "Family", example: "Meine Cousine lebt in Wien.", exampleEn: "My cousin lives in Vienna." },
  { german: "Ehemann", english: "husband", article: "der", partOfSpeech: "noun", category: "Family", example: "Ihr Ehemann arbeitet als Ingenieur.", exampleEn: "Her husband works as an engineer." },
  { german: "Ehefrau", english: "wife", article: "die", partOfSpeech: "noun", category: "Family", example: "Seine Ehefrau ist Lehrerin.", exampleEn: "His wife is a teacher." },
  { german: "Sohn", english: "son", article: "der", partOfSpeech: "noun", category: "Family", example: "Unser Sohn geht in die Schule.", exampleEn: "Our son goes to school." },
  { german: "Tochter", english: "daughter", article: "die", partOfSpeech: "noun", category: "Family", example: "Unsere Tochter spielt Klavier.", exampleEn: "Our daughter plays piano." },
  { german: "Baby", english: "baby", article: "das", partOfSpeech: "noun", category: "Family", example: "Das Baby schläft gerade.", exampleEn: "The baby is sleeping right now." },
  { german: "Hochzeit", english: "wedding", article: "die", partOfSpeech: "noun", category: "Family", example: "Die Hochzeit ist im Juni.", exampleEn: "The wedding is in June." },
  { german: "Paar", english: "couple / pair", article: "das", partOfSpeech: "noun", category: "Family", example: "Das Paar tanzt zusammen.", exampleEn: "The couple dances together." },

  // ─── Food & Drink ─────────────────────────────────────────────────
  { german: "Tee", english: "tea", article: "der", partOfSpeech: "noun", category: "Food & Drink", example: "Ich trinke gerne grünen Tee.", exampleEn: "I like to drink green tea." },
  { german: "Saft", english: "juice", article: "der", partOfSpeech: "noun", category: "Food & Drink", example: "Möchtest du Orangensaft?", exampleEn: "Would you like orange juice?" },
  { german: "Wein", english: "wine", article: "der", partOfSpeech: "noun", category: "Food & Drink", example: "Der Wein kommt aus Frankreich.", exampleEn: "The wine comes from France." },
  { german: "Suppe", english: "soup", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Die Suppe ist noch heiß.", exampleEn: "The soup is still hot." },
  { german: "Salat", english: "salad", article: "der", partOfSpeech: "noun", category: "Food & Drink", example: "Ich bestelle einen Salat.", exampleEn: "I'm ordering a salad." },
  { german: "Reis", english: "rice", article: "der", partOfSpeech: "noun", category: "Food & Drink", example: "Reis passt gut zu Gemüse.", exampleEn: "Rice goes well with vegetables." },
  { german: "Nudel", english: "noodle / pasta", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Die Nudeln sind fertig.", exampleEn: "The noodles are ready." },
  { german: "Kartoffel", english: "potato", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Kartoffeln sind sehr beliebt in Deutschland.", exampleEn: "Potatoes are very popular in Germany." },
  { german: "Gemüse", english: "vegetables", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Das Gemüse ist frisch vom Markt.", exampleEn: "The vegetables are fresh from the market." },
  { german: "Obst", english: "fruit", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Obst ist gesund und lecker.", exampleEn: "Fruit is healthy and delicious." },
  { german: "Zucker", english: "sugar", article: "der", partOfSpeech: "noun", category: "Food & Drink", example: "Nimmst du Zucker in den Kaffee?", exampleEn: "Do you take sugar in your coffee?" },
  { german: "Salz", english: "salt", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Die Suppe braucht mehr Salz.", exampleEn: "The soup needs more salt." },
  { german: "Butter", english: "butter", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Ich brauche Butter für das Brot.", exampleEn: "I need butter for the bread." },
  { german: "Schokolade", english: "chocolate", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Magst du Schokolade?", exampleEn: "Do you like chocolate?" },
  { german: "Essen", english: "food / meal", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Das Essen schmeckt wunderbar.", exampleEn: "The food tastes wonderful." },
  { german: "Getränk", english: "drink / beverage", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Welches Getränk möchten Sie?", exampleEn: "Which drink would you like?" },
  { german: "Frühstück", english: "breakfast", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Das Frühstück beginnt um sieben.", exampleEn: "Breakfast starts at seven." },
  { german: "Mittagessen", english: "lunch", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Wir essen das Mittagessen in der Kantine.", exampleEn: "We eat lunch in the cafeteria." },
  { german: "Abendessen", english: "dinner", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Um wie viel Uhr ist das Abendessen?", exampleEn: "What time is dinner?" },
  { german: "Gabel", english: "fork", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Ich brauche eine Gabel.", exampleEn: "I need a fork." },
  { german: "Messer", english: "knife", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Das Messer ist sehr scharf.", exampleEn: "The knife is very sharp." },
  { german: "Löffel", english: "spoon", article: "der", partOfSpeech: "noun", category: "Food & Drink", example: "Gib mir bitte einen Löffel.", exampleEn: "Please give me a spoon." },
  { german: "Teller", english: "plate", article: "der", partOfSpeech: "noun", category: "Food & Drink", example: "Der Teller ist leer.", exampleEn: "The plate is empty." },
  { german: "Tasse", english: "cup", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Möchtest du eine Tasse Tee?", exampleEn: "Would you like a cup of tea?" },
  { german: "Glas", english: "glass", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Ein Glas Wasser, bitte.", exampleEn: "A glass of water, please." },
  { german: "Flasche", english: "bottle", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Die Flasche ist fast leer.", exampleEn: "The bottle is almost empty." },
  { german: "Fisch", english: "fish", article: "der", partOfSpeech: "noun", category: "Food & Drink", example: "Der Fisch ist sehr frisch.", exampleEn: "The fish is very fresh." },
  { german: "Hähnchen", english: "chicken", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Ich nehme das Hähnchen mit Reis.", exampleEn: "I'll have the chicken with rice." },
  { german: "Tomate", english: "tomato", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Die Tomaten sind rot und reif.", exampleEn: "The tomatoes are red and ripe." },
  { german: "Zwiebel", english: "onion", article: "die", partOfSpeech: "noun", category: "Food & Drink", example: "Schneid bitte die Zwiebel.", exampleEn: "Please cut the onion." },
  { german: "Rezept", english: "recipe", article: "das", partOfSpeech: "noun", category: "Food & Drink", example: "Hast du ein gutes Rezept für Suppe?", exampleEn: "Do you have a good recipe for soup?" },

  // ─── Home ─────────────────────────────────────────────────────────
  { german: "Wohnung", english: "apartment", article: "die", partOfSpeech: "noun", category: "Home", example: "Die Wohnung hat drei Zimmer.", exampleEn: "The apartment has three rooms." },
  { german: "Zimmer", english: "room", article: "das", partOfSpeech: "noun", category: "Home", example: "Das Zimmer ist hell und groß.", exampleEn: "The room is bright and large." },
  { german: "Küche", english: "kitchen", article: "die", partOfSpeech: "noun", category: "Home", example: "Wir kochen in der Küche.", exampleEn: "We cook in the kitchen." },
  { german: "Badezimmer", english: "bathroom", article: "das", partOfSpeech: "noun", category: "Home", example: "Das Badezimmer ist im ersten Stock.", exampleEn: "The bathroom is on the first floor." },
  { german: "Schlafzimmer", english: "bedroom", article: "das", partOfSpeech: "noun", category: "Home", example: "Das Schlafzimmer ist sehr ruhig.", exampleEn: "The bedroom is very quiet." },
  { german: "Wohnzimmer", english: "living room", article: "das", partOfSpeech: "noun", category: "Home", example: "Wir sitzen im Wohnzimmer.", exampleEn: "We are sitting in the living room." },
  { german: "Garten", english: "garden", article: "der", partOfSpeech: "noun", category: "Home", example: "Die Kinder spielen im Garten.", exampleEn: "The children are playing in the garden." },
  { german: "Treppe", english: "stairs", article: "die", partOfSpeech: "noun", category: "Home", example: "Sei vorsichtig auf der Treppe.", exampleEn: "Be careful on the stairs." },
  { german: "Dach", english: "roof", article: "das", partOfSpeech: "noun", category: "Home", example: "Die Katze sitzt auf dem Dach.", exampleEn: "The cat is sitting on the roof." },
  { german: "Wand", english: "wall", article: "die", partOfSpeech: "noun", category: "Home", example: "An der Wand hängt ein Bild.", exampleEn: "A picture hangs on the wall." },
  { german: "Boden", english: "floor / ground", article: "der", partOfSpeech: "noun", category: "Home", example: "Der Boden ist aus Holz.", exampleEn: "The floor is made of wood." },
  { german: "Bett", english: "bed", article: "das", partOfSpeech: "noun", category: "Home", example: "Ich gehe jetzt ins Bett.", exampleEn: "I'm going to bed now." },
  { german: "Sofa", english: "sofa / couch", article: "das", partOfSpeech: "noun", category: "Home", example: "Das Sofa ist sehr bequem.", exampleEn: "The sofa is very comfortable." },
  { german: "Schrank", english: "wardrobe / cabinet", article: "der", partOfSpeech: "noun", category: "Home", example: "Die Kleider hängen im Schrank.", exampleEn: "The clothes hang in the wardrobe." },
  { german: "Regal", english: "shelf", article: "das", partOfSpeech: "noun", category: "Home", example: "Die Bücher stehen im Regal.", exampleEn: "The books are on the shelf." },
  { german: "Lampe", english: "lamp", article: "die", partOfSpeech: "noun", category: "Home", example: "Mach bitte die Lampe an.", exampleEn: "Please turn on the lamp." },
  { german: "Spiegel", english: "mirror", article: "der", partOfSpeech: "noun", category: "Home", example: "Ich schaue in den Spiegel.", exampleEn: "I look in the mirror." },
  { german: "Kühlschrank", english: "refrigerator", article: "der", partOfSpeech: "noun", category: "Home", example: "Die Milch ist im Kühlschrank.", exampleEn: "The milk is in the refrigerator." },
  { german: "Herd", english: "stove", article: "der", partOfSpeech: "noun", category: "Home", example: "Pass auf, der Herd ist heiß.", exampleEn: "Watch out, the stove is hot." },
  { german: "Waschmaschine", english: "washing machine", article: "die", partOfSpeech: "noun", category: "Home", example: "Die Waschmaschine läuft gerade.", exampleEn: "The washing machine is running." },
  { german: "Teppich", english: "carpet / rug", article: "der", partOfSpeech: "noun", category: "Home", example: "Der Teppich ist sehr weich.", exampleEn: "The carpet is very soft." },
  { german: "Miete", english: "rent", article: "die", partOfSpeech: "noun", category: "Home", example: "Die Miete ist zu hoch.", exampleEn: "The rent is too high." },
  { german: "Keller", english: "basement / cellar", article: "der", partOfSpeech: "noun", category: "Home", example: "Der Wein steht im Keller.", exampleEn: "The wine is in the cellar." },
  { german: "Balkon", english: "balcony", article: "der", partOfSpeech: "noun", category: "Home", example: "Wir sitzen auf dem Balkon.", exampleEn: "We are sitting on the balcony." },
  { german: "Decke", english: "blanket / ceiling", article: "die", partOfSpeech: "noun", category: "Home", example: "Die Decke ist sehr warm.", exampleEn: "The blanket is very warm." },
  { german: "Kissen", english: "pillow / cushion", article: "das", partOfSpeech: "noun", category: "Home", example: "Das Kissen ist zu hart.", exampleEn: "The pillow is too hard." },

  // ─── Clothing ─────────────────────────────────────────────────────
  { german: "Hemd", english: "shirt", article: "das", partOfSpeech: "noun", category: "Clothing", example: "Das Hemd ist frisch gebügelt.", exampleEn: "The shirt is freshly ironed." },
  { german: "Hose", english: "pants / trousers", article: "die", partOfSpeech: "noun", category: "Clothing", example: "Die Hose passt mir nicht mehr.", exampleEn: "The pants don't fit me anymore." },
  { german: "Kleid", english: "dress", article: "das", partOfSpeech: "noun", category: "Clothing", example: "Das Kleid ist wunderschön.", exampleEn: "The dress is beautiful." },
  { german: "Rock", english: "skirt", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Der Rock ist zu kurz.", exampleEn: "The skirt is too short." },
  { german: "Jacke", english: "jacket", article: "die", partOfSpeech: "noun", category: "Clothing", example: "Nimm deine Jacke mit, es ist kalt.", exampleEn: "Take your jacket, it's cold." },
  { german: "Mantel", english: "coat", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Im Winter trage ich einen Mantel.", exampleEn: "In winter I wear a coat." },
  { german: "Schuh", english: "shoe", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Diese Schuhe sind sehr bequem.", exampleEn: "These shoes are very comfortable." },
  { german: "Stiefel", english: "boot", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Im Winter brauche ich Stiefel.", exampleEn: "In winter I need boots." },
  { german: "Socke", english: "sock", article: "die", partOfSpeech: "noun", category: "Clothing", example: "Ich kann meine Socken nicht finden.", exampleEn: "I can't find my socks." },
  { german: "Mütze", english: "hat / beanie", article: "die", partOfSpeech: "noun", category: "Clothing", example: "Setz eine Mütze auf, es ist kalt!", exampleEn: "Put on a hat, it's cold!" },
  { german: "Handschuh", english: "glove", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Ich habe meine Handschuhe vergessen.", exampleEn: "I forgot my gloves." },
  { german: "Schal", english: "scarf", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Der Schal hält mich warm.", exampleEn: "The scarf keeps me warm." },
  { german: "Tasche", english: "bag / pocket", article: "die", partOfSpeech: "noun", category: "Clothing", example: "Meine Tasche ist sehr schwer.", exampleEn: "My bag is very heavy." },
  { german: "Brille", english: "glasses", article: "die", partOfSpeech: "noun", category: "Clothing", example: "Ich brauche eine neue Brille.", exampleEn: "I need new glasses." },
  { german: "Anzug", english: "suit", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Er trägt einen Anzug zur Arbeit.", exampleEn: "He wears a suit to work." },
  { german: "Pullover", english: "sweater / pullover", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Der Pullover ist aus Wolle.", exampleEn: "The sweater is made of wool." },
  { german: "T-Shirt", english: "t-shirt", article: "das", partOfSpeech: "noun", category: "Clothing", example: "Im Sommer trage ich ein T-Shirt.", exampleEn: "In summer I wear a t-shirt." },
  { german: "Gürtel", english: "belt", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Der Gürtel ist aus Leder.", exampleEn: "The belt is made of leather." },
  { german: "Schmuck", english: "jewelry", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Sie trägt schönen Schmuck.", exampleEn: "She wears beautiful jewelry." },
  { german: "Ring", english: "ring", article: "der", partOfSpeech: "noun", category: "Clothing", example: "Der Ring ist aus Gold.", exampleEn: "The ring is made of gold." },

  // ─── Body ─────────────────────────────────────────────────────────
  { german: "Körper", english: "body", article: "der", partOfSpeech: "noun", category: "Body", example: "Sport ist gut für den Körper.", exampleEn: "Exercise is good for the body." },
  { german: "Haar", english: "hair", article: "das", partOfSpeech: "noun", category: "Body", example: "Sie hat lange blonde Haare.", exampleEn: "She has long blonde hair." },
  { german: "Gesicht", english: "face", article: "das", partOfSpeech: "noun", category: "Body", example: "Wasch dir das Gesicht.", exampleEn: "Wash your face." },
  { german: "Nase", english: "nose", article: "die", partOfSpeech: "noun", category: "Body", example: "Meine Nase ist kalt.", exampleEn: "My nose is cold." },
  { german: "Mund", english: "mouth", article: "der", partOfSpeech: "noun", category: "Body", example: "Mach den Mund auf.", exampleEn: "Open your mouth." },
  { german: "Ohr", english: "ear", article: "das", partOfSpeech: "noun", category: "Body", example: "Mir tut das Ohr weh.", exampleEn: "My ear hurts." },
  { german: "Zahn", english: "tooth", article: "der", partOfSpeech: "noun", category: "Body", example: "Ich putze mir die Zähne.", exampleEn: "I brush my teeth." },
  { german: "Hals", english: "neck / throat", article: "der", partOfSpeech: "noun", category: "Body", example: "Ich habe Halsschmerzen.", exampleEn: "I have a sore throat." },
  { german: "Schulter", english: "shoulder", article: "die", partOfSpeech: "noun", category: "Body", example: "Meine Schulter tut weh.", exampleEn: "My shoulder hurts." },
  { german: "Arm", english: "arm", article: "der", partOfSpeech: "noun", category: "Body", example: "Er hat sich den Arm gebrochen.", exampleEn: "He broke his arm." },
  { german: "Finger", english: "finger", article: "der", partOfSpeech: "noun", category: "Body", example: "Ich habe mir in den Finger geschnitten.", exampleEn: "I cut my finger." },
  { german: "Bein", english: "leg", article: "das", partOfSpeech: "noun", category: "Body", example: "Mein Bein ist eingeschlafen.", exampleEn: "My leg fell asleep." },
  { german: "Fuß", english: "foot", article: "der", partOfSpeech: "noun", category: "Body", example: "Mein Fuß tut weh.", exampleEn: "My foot hurts." },
  { german: "Knie", english: "knee", article: "das", partOfSpeech: "noun", category: "Body", example: "Das Knie ist geschwollen.", exampleEn: "The knee is swollen." },
  { german: "Rücken", english: "back", article: "der", partOfSpeech: "noun", category: "Body", example: "Ich habe Rückenschmerzen.", exampleEn: "I have back pain." },
  { german: "Bauch", english: "belly / stomach", article: "der", partOfSpeech: "noun", category: "Body", example: "Mir tut der Bauch weh.", exampleEn: "My stomach hurts." },
  { german: "Haut", english: "skin", article: "die", partOfSpeech: "noun", category: "Body", example: "Die Sonne ist schlecht für die Haut.", exampleEn: "The sun is bad for the skin." },
  { german: "Blut", english: "blood", article: "das", partOfSpeech: "noun", category: "Body", example: "Die Ärztin nimmt Blut ab.", exampleEn: "The doctor takes blood." },
  { german: "Stimme", english: "voice", article: "die", partOfSpeech: "noun", category: "Body", example: "Sie hat eine schöne Stimme.", exampleEn: "She has a beautiful voice." },

  // ─── Health ───────────────────────────────────────────────────────
  { german: "Gesundheit", english: "health", article: "die", partOfSpeech: "noun", category: "Health", example: "Gesundheit ist das Wichtigste.", exampleEn: "Health is the most important thing." },
  { german: "Krankheit", english: "illness / disease", article: "die", partOfSpeech: "noun", category: "Health", example: "Die Krankheit ist nicht ansteckend.", exampleEn: "The illness is not contagious." },
  { german: "Schmerz", english: "pain", article: "der", partOfSpeech: "noun", category: "Health", example: "Der Schmerz wird langsam besser.", exampleEn: "The pain is slowly getting better." },
  { german: "Medikament", english: "medication", article: "das", partOfSpeech: "noun", category: "Health", example: "Nehmen Sie das Medikament dreimal täglich.", exampleEn: "Take the medication three times daily." },
  { german: "Apotheke", english: "pharmacy", article: "die", partOfSpeech: "noun", category: "Health", example: "Die Apotheke ist um die Ecke.", exampleEn: "The pharmacy is around the corner." },
  { german: "Rezept", english: "prescription", article: "das", partOfSpeech: "noun", category: "Health", example: "Ich brauche ein Rezept vom Arzt.", exampleEn: "I need a prescription from the doctor." },
  { german: "Termin", english: "appointment", article: "der", partOfSpeech: "noun", category: "Health", example: "Ich habe einen Termin beim Arzt.", exampleEn: "I have a doctor's appointment." },
  { german: "Fieber", english: "fever", article: "das", partOfSpeech: "noun", category: "Health", example: "Das Kind hat hohes Fieber.", exampleEn: "The child has a high fever." },
  { german: "Erkältung", english: "cold (illness)", article: "die", partOfSpeech: "noun", category: "Health", example: "Ich habe eine starke Erkältung.", exampleEn: "I have a bad cold." },
  { german: "Husten", english: "cough", article: "der", partOfSpeech: "noun", category: "Health", example: "Der Husten geht nicht weg.", exampleEn: "The cough won't go away." },
  { german: "Versicherung", english: "insurance", article: "die", partOfSpeech: "noun", category: "Health", example: "Haben Sie eine Krankenversicherung?", exampleEn: "Do you have health insurance?" },
  { german: "Unfall", english: "accident", article: "der", partOfSpeech: "noun", category: "Health", example: "Es gab einen Unfall auf der Autobahn.", exampleEn: "There was an accident on the highway." },

  // ─── Work ─────────────────────────────────────────────────────────
  { german: "Beruf", english: "profession / occupation", article: "der", partOfSpeech: "noun", category: "Work", example: "Was ist Ihr Beruf?", exampleEn: "What is your profession?" },
  { german: "Stelle", english: "job / position", article: "die", partOfSpeech: "noun", category: "Work", example: "Ich suche eine neue Stelle.", exampleEn: "I'm looking for a new position." },
  { german: "Firma", english: "company / firm", article: "die", partOfSpeech: "noun", category: "Work", example: "Die Firma hat 200 Mitarbeiter.", exampleEn: "The company has 200 employees." },
  { german: "Gehalt", english: "salary", article: "das", partOfSpeech: "noun", category: "Work", example: "Das Gehalt kommt am Ende des Monats.", exampleEn: "The salary comes at the end of the month." },
  { german: "Besprechung", english: "meeting", article: "die", partOfSpeech: "noun", category: "Work", example: "Die Besprechung dauert eine Stunde.", exampleEn: "The meeting lasts one hour." },
  { german: "Aufgabe", english: "task / assignment", article: "die", partOfSpeech: "noun", category: "Work", example: "Das ist eine schwierige Aufgabe.", exampleEn: "That is a difficult task." },
  { german: "Vertrag", english: "contract", article: "der", partOfSpeech: "noun", category: "Work", example: "Ich muss den Vertrag unterschreiben.", exampleEn: "I have to sign the contract." },
  { german: "Projekt", english: "project", article: "das", partOfSpeech: "noun", category: "Work", example: "Das Projekt ist fast fertig.", exampleEn: "The project is almost finished." },
  { german: "Bewerbung", english: "application (job)", article: "die", partOfSpeech: "noun", category: "Work", example: "Ich schicke meine Bewerbung morgen ab.", exampleEn: "I'll send my application tomorrow." },
  { german: "Urlaub", english: "vacation / holiday", article: "der", partOfSpeech: "noun", category: "Work", example: "Im August habe ich Urlaub.", exampleEn: "In August I have vacation." },
  { german: "Mitarbeiter", english: "employee / coworker", article: "der", partOfSpeech: "noun", category: "Work", example: "Die Mitarbeiter sind sehr motiviert.", exampleEn: "The employees are very motivated." },
  { german: "Erfahrung", english: "experience", article: "die", partOfSpeech: "noun", category: "Work", example: "Sie hat viel Erfahrung in diesem Bereich.", exampleEn: "She has a lot of experience in this field." },
  { german: "Lebenslauf", english: "resume / CV", article: "der", partOfSpeech: "noun", category: "Work", example: "Bitte schicken Sie Ihren Lebenslauf.", exampleEn: "Please send your resume." },
  { german: "Praktikum", english: "internship", article: "das", partOfSpeech: "noun", category: "Work", example: "Ich mache ein Praktikum bei einer Bank.", exampleEn: "I'm doing an internship at a bank." },
  { german: "Pause", english: "break / pause", article: "die", partOfSpeech: "noun", category: "Work", example: "Wir machen jetzt eine Pause.", exampleEn: "We're taking a break now." },

  // ─── Education ────────────────────────────────────────────────────
  { german: "Universität", english: "university", article: "die", partOfSpeech: "noun", category: "Education", example: "Sie studiert an der Universität.", exampleEn: "She studies at the university." },
  { german: "Kurs", english: "course", article: "der", partOfSpeech: "noun", category: "Education", example: "Der Deutschkurs beginnt nächste Woche.", exampleEn: "The German course starts next week." },
  { german: "Prüfung", english: "exam / test", article: "die", partOfSpeech: "noun", category: "Education", example: "Die Prüfung war sehr schwer.", exampleEn: "The exam was very hard." },
  { german: "Unterricht", english: "class / lesson", article: "der", partOfSpeech: "noun", category: "Education", example: "Der Unterricht beginnt um acht.", exampleEn: "Class starts at eight." },
  { german: "Hausaufgabe", english: "homework", article: "die", partOfSpeech: "noun", category: "Education", example: "Hast du die Hausaufgaben gemacht?", exampleEn: "Did you do the homework?" },
  { german: "Stift", english: "pen / pencil", article: "der", partOfSpeech: "noun", category: "Education", example: "Kann ich mir einen Stift leihen?", exampleEn: "Can I borrow a pen?" },
  { german: "Heft", english: "notebook / exercise book", article: "das", partOfSpeech: "noun", category: "Education", example: "Schreib das in dein Heft.", exampleEn: "Write that in your notebook." },
  { german: "Wörterbuch", english: "dictionary", article: "das", partOfSpeech: "noun", category: "Education", example: "Ich schlage das Wort im Wörterbuch nach.", exampleEn: "I look up the word in the dictionary." },
  { german: "Studium", english: "studies (university)", article: "das", partOfSpeech: "noun", category: "Education", example: "Nach dem Studium suche ich Arbeit.", exampleEn: "After my studies I'll look for work." },
  { german: "Klasse", english: "class / grade", article: "die", partOfSpeech: "noun", category: "Education", example: "In welcher Klasse bist du?", exampleEn: "What grade are you in?" },
  { german: "Note", english: "grade / mark", article: "die", partOfSpeech: "noun", category: "Education", example: "Ich habe eine gute Note bekommen.", exampleEn: "I got a good grade." },
  { german: "Bibliothek", english: "library", article: "die", partOfSpeech: "noun", category: "Education", example: "Die Bibliothek ist bis 20 Uhr geöffnet.", exampleEn: "The library is open until 8 PM." },
  { german: "Übung", english: "exercise / practice", article: "die", partOfSpeech: "noun", category: "Education", example: "Die Übung ist auf Seite zehn.", exampleEn: "The exercise is on page ten." },
  { german: "Bildung", english: "education", article: "die", partOfSpeech: "noun", category: "Education", example: "Bildung ist sehr wichtig.", exampleEn: "Education is very important." },
  { german: "Zeugnis", english: "report card / certificate", article: "das", partOfSpeech: "noun", category: "Education", example: "Das Zeugnis kommt am Freitag.", exampleEn: "The report card comes on Friday." },
  { german: "Wissenschaft", english: "science", article: "die", partOfSpeech: "noun", category: "Education", example: "Er interessiert sich für Wissenschaft.", exampleEn: "He is interested in science." },

  // ─── Transport ────────────────────────────────────────────────────
  { german: "Zug", english: "train", article: "der", partOfSpeech: "noun", category: "Transport", example: "Der Zug kommt in zehn Minuten.", exampleEn: "The train arrives in ten minutes." },
  { german: "Bus", english: "bus", article: "der", partOfSpeech: "noun", category: "Transport", example: "Der Bus fährt alle 15 Minuten.", exampleEn: "The bus runs every 15 minutes." },
  { german: "U-Bahn", english: "subway / metro", article: "die", partOfSpeech: "noun", category: "Transport", example: "Ich fahre mit der U-Bahn zur Arbeit.", exampleEn: "I take the subway to work." },
  { german: "Straßenbahn", english: "tram / streetcar", article: "die", partOfSpeech: "noun", category: "Transport", example: "Die Straßenbahn hält hier.", exampleEn: "The tram stops here." },
  { german: "Haltestelle", english: "stop (bus/tram)", article: "die", partOfSpeech: "noun", category: "Transport", example: "Die Haltestelle ist um die Ecke.", exampleEn: "The stop is around the corner." },
  { german: "Fahrkarte", english: "ticket (transport)", article: "die", partOfSpeech: "noun", category: "Transport", example: "Ich muss eine Fahrkarte kaufen.", exampleEn: "I need to buy a ticket." },
  { german: "Flug", english: "flight", article: "der", partOfSpeech: "noun", category: "Transport", example: "Der Flug dauert drei Stunden.", exampleEn: "The flight takes three hours." },
  { german: "Flugzeug", english: "airplane", article: "das", partOfSpeech: "noun", category: "Transport", example: "Das Flugzeug landet um 14 Uhr.", exampleEn: "The airplane lands at 2 PM." },
  { german: "Schiff", english: "ship", article: "das", partOfSpeech: "noun", category: "Transport", example: "Das Schiff fährt über den See.", exampleEn: "The ship crosses the lake." },
  { german: "Brücke", english: "bridge", article: "die", partOfSpeech: "noun", category: "Transport", example: "Wir gehen über die Brücke.", exampleEn: "We walk over the bridge." },
  { german: "Parkplatz", english: "parking lot / space", article: "der", partOfSpeech: "noun", category: "Transport", example: "Ich suche einen Parkplatz.", exampleEn: "I'm looking for a parking space." },
  { german: "Autobahn", english: "highway / motorway", article: "die", partOfSpeech: "noun", category: "Transport", example: "Auf der Autobahn gibt es einen Stau.", exampleEn: "There is a traffic jam on the highway." },
  { german: "Verkehr", english: "traffic", article: "der", partOfSpeech: "noun", category: "Transport", example: "Der Verkehr ist heute sehr schlimm.", exampleEn: "Traffic is very bad today." },
  { german: "Reise", english: "trip / journey", article: "die", partOfSpeech: "noun", category: "Transport", example: "Die Reise war sehr schön.", exampleEn: "The trip was very nice." },
  { german: "Koffer", english: "suitcase", article: "der", partOfSpeech: "noun", category: "Transport", example: "Ich packe meinen Koffer.", exampleEn: "I'm packing my suitcase." },
  { german: "Pass", english: "passport", article: "der", partOfSpeech: "noun", category: "Transport", example: "Haben Sie Ihren Pass dabei?", exampleEn: "Do you have your passport with you?" },
  { german: "Gepäck", english: "luggage / baggage", article: "das", partOfSpeech: "noun", category: "Transport", example: "Mein Gepäck ist zu schwer.", exampleEn: "My luggage is too heavy." },
  { german: "Führerschein", english: "driver's license", article: "der", partOfSpeech: "noun", category: "Transport", example: "Ich habe meinen Führerschein zu Hause.", exampleEn: "I left my driver's license at home." },
  { german: "Benzin", english: "gasoline / petrol", article: "das", partOfSpeech: "noun", category: "Transport", example: "Wir brauchen Benzin.", exampleEn: "We need gasoline." },
  { german: "Ampel", english: "traffic light", article: "die", partOfSpeech: "noun", category: "Transport", example: "Die Ampel ist rot.", exampleEn: "The traffic light is red." },

  // ─── Nature ───────────────────────────────────────────────────────
  { german: "Himmel", english: "sky / heaven", article: "der", partOfSpeech: "noun", category: "Nature", example: "Der Himmel ist heute blau.", exampleEn: "The sky is blue today." },
  { german: "Wolke", english: "cloud", article: "die", partOfSpeech: "noun", category: "Nature", example: "Dunkle Wolken kommen.", exampleEn: "Dark clouds are coming." },
  { german: "Stern", english: "star", article: "der", partOfSpeech: "noun", category: "Nature", example: "Heute Nacht sieht man viele Sterne.", exampleEn: "Tonight you can see many stars." },
  { german: "Wind", english: "wind", article: "der", partOfSpeech: "noun", category: "Nature", example: "Der Wind ist heute sehr stark.", exampleEn: "The wind is very strong today." },
  { german: "Wetter", english: "weather", article: "das", partOfSpeech: "noun", category: "Nature", example: "Wie wird das Wetter morgen?", exampleEn: "What will the weather be like tomorrow?" },
  { german: "Wald", english: "forest", article: "der", partOfSpeech: "noun", category: "Nature", example: "Wir wandern durch den Wald.", exampleEn: "We hike through the forest." },
  { german: "See", english: "lake", article: "der", partOfSpeech: "noun", category: "Nature", example: "Der See ist sehr tief.", exampleEn: "The lake is very deep." },
  { german: "Wiese", english: "meadow", article: "die", partOfSpeech: "noun", category: "Nature", example: "Die Kinder spielen auf der Wiese.", exampleEn: "The children play on the meadow." },
  { german: "Feld", english: "field", article: "das", partOfSpeech: "noun", category: "Nature", example: "Das Feld ist voller Weizen.", exampleEn: "The field is full of wheat." },
  { german: "Stein", english: "stone / rock", article: "der", partOfSpeech: "noun", category: "Nature", example: "Vorsicht, da liegt ein Stein.", exampleEn: "Careful, there's a stone there." },
  { german: "Sand", english: "sand", article: "der", partOfSpeech: "noun", category: "Nature", example: "Die Kinder spielen im Sand.", exampleEn: "The children play in the sand." },
  { german: "Insel", english: "island", article: "die", partOfSpeech: "noun", category: "Nature", example: "Die Insel ist wunderschön.", exampleEn: "The island is beautiful." },
  { german: "Strand", english: "beach", article: "der", partOfSpeech: "noun", category: "Nature", example: "Wir gehen an den Strand.", exampleEn: "We're going to the beach." },
  { german: "Luft", english: "air", article: "die", partOfSpeech: "noun", category: "Nature", example: "Die Luft ist heute frisch.", exampleEn: "The air is fresh today." },
  { german: "Feuer", english: "fire", article: "das", partOfSpeech: "noun", category: "Nature", example: "Wir machen ein Feuer im Kamin.", exampleEn: "We're making a fire in the fireplace." },
  { german: "Erde", english: "earth / soil", article: "die", partOfSpeech: "noun", category: "Nature", example: "Die Erde im Garten ist trocken.", exampleEn: "The soil in the garden is dry." },
  { german: "Eis", english: "ice / ice cream", article: "das", partOfSpeech: "noun", category: "Nature", example: "Im Winter gibt es Eis auf dem See.", exampleEn: "In winter there is ice on the lake." },
  { german: "Sturm", english: "storm", article: "der", partOfSpeech: "noun", category: "Nature", example: "Ein Sturm kommt heute Nacht.", exampleEn: "A storm is coming tonight." },
  { german: "Tal", english: "valley", article: "das", partOfSpeech: "noun", category: "Nature", example: "Das Dorf liegt in einem schönen Tal.", exampleEn: "The village lies in a beautiful valley." },
  { german: "Ufer", english: "shore / bank", article: "das", partOfSpeech: "noun", category: "Nature", example: "Wir sitzen am Ufer des Flusses.", exampleEn: "We sit on the bank of the river." },
  { german: "Blatt", english: "leaf / sheet", article: "das", partOfSpeech: "noun", category: "Nature", example: "Im Herbst fallen die Blätter.", exampleEn: "In autumn the leaves fall." },

  // ─── Animals ──────────────────────────────────────────────────────
  { german: "Hund", english: "dog", article: "der", partOfSpeech: "noun", category: "Animals", example: "Der Hund bellt laut.", exampleEn: "The dog barks loudly." },
  { german: "Katze", english: "cat", article: "die", partOfSpeech: "noun", category: "Animals", example: "Die Katze schläft auf dem Sofa.", exampleEn: "The cat sleeps on the sofa." },
  { german: "Vogel", english: "bird", article: "der", partOfSpeech: "noun", category: "Animals", example: "Der Vogel singt morgens.", exampleEn: "The bird sings in the morning." },
  { german: "Pferd", english: "horse", article: "das", partOfSpeech: "noun", category: "Animals", example: "Das Pferd läuft schnell.", exampleEn: "The horse runs fast." },
  { german: "Kuh", english: "cow", article: "die", partOfSpeech: "noun", category: "Animals", example: "Die Kuh steht auf der Wiese.", exampleEn: "The cow stands on the meadow." },
  { german: "Schwein", english: "pig", article: "das", partOfSpeech: "noun", category: "Animals", example: "Das Schwein frisst gerne.", exampleEn: "The pig likes to eat." },
  { german: "Maus", english: "mouse", article: "die", partOfSpeech: "noun", category: "Animals", example: "Die Maus ist im Keller.", exampleEn: "The mouse is in the basement." },
  { german: "Bär", english: "bear", article: "der", partOfSpeech: "noun", category: "Animals", weakNoun: true, example: "Der Bär ist das Wappentier von Berlin.", exampleEn: "The bear is Berlin's heraldic animal." },
  { german: "Schmetterling", english: "butterfly", article: "der", partOfSpeech: "noun", category: "Animals", example: "Der Schmetterling fliegt von Blume zu Blume.", exampleEn: "The butterfly flies from flower to flower." },
  { german: "Kaninchen", english: "rabbit", article: "das", partOfSpeech: "noun", category: "Animals", example: "Das Kaninchen frisst eine Karotte.", exampleEn: "The rabbit is eating a carrot." },
  { german: "Tier", english: "animal", article: "das", partOfSpeech: "noun", category: "Animals", example: "Welches Tier magst du am liebsten?", exampleEn: "Which animal do you like best?" },
  { german: "Ente", english: "duck", article: "die", partOfSpeech: "noun", category: "Animals", example: "Die Enten schwimmen auf dem See.", exampleEn: "The ducks swim on the lake." },
  { german: "Schlange", english: "snake", article: "die", partOfSpeech: "noun", category: "Animals", example: "Die Schlange liegt in der Sonne.", exampleEn: "The snake is lying in the sun." },
  { german: "Wolf", english: "wolf", article: "der", partOfSpeech: "noun", category: "Animals", example: "Der Wolf lebt im Wald.", exampleEn: "The wolf lives in the forest." },
  { german: "Schaf", english: "sheep", article: "das", partOfSpeech: "noun", category: "Animals", example: "Das Schaf frisst Gras.", exampleEn: "The sheep eats grass." },
  { german: "Frosch", english: "frog", article: "der", partOfSpeech: "noun", category: "Animals", example: "Der Frosch sitzt am Teich.", exampleEn: "The frog sits by the pond." },
  { german: "Insekt", english: "insect", article: "das", partOfSpeech: "noun", category: "Animals", example: "Das Insekt fliegt zum Licht.", exampleEn: "The insect flies toward the light." },

  // ─── City ─────────────────────────────────────────────────────────
  { german: "Platz", english: "square / place", article: "der", partOfSpeech: "noun", category: "City", example: "Wir treffen uns auf dem Platz.", exampleEn: "We'll meet at the square." },
  { german: "Laden", english: "shop / store", article: "der", partOfSpeech: "noun", category: "City", example: "Der Laden schließt um 18 Uhr.", exampleEn: "The shop closes at 6 PM." },
  { german: "Geschäft", english: "shop / business", article: "das", partOfSpeech: "noun", category: "City", example: "Das Geschäft hat heute geöffnet.", exampleEn: "The shop is open today." },
  { german: "Bank", english: "bank", article: "die", partOfSpeech: "noun", category: "City", example: "Ich muss zur Bank gehen.", exampleEn: "I have to go to the bank." },
  { german: "Post", english: "post office / mail", article: "die", partOfSpeech: "noun", category: "City", example: "Ich bringe das Paket zur Post.", exampleEn: "I'm taking the package to the post office." },
  { german: "Museum", english: "museum", article: "das", partOfSpeech: "noun", category: "City", example: "Das Museum ist sehr interessant.", exampleEn: "The museum is very interesting." },
  { german: "Theater", english: "theater", article: "das", partOfSpeech: "noun", category: "City", example: "Wir gehen heute Abend ins Theater.", exampleEn: "We're going to the theater tonight." },
  { german: "Kino", english: "cinema / movie theater", article: "das", partOfSpeech: "noun", category: "City", example: "Der Film läuft im Kino.", exampleEn: "The film is playing at the cinema." },
  { german: "Hotel", english: "hotel", article: "das", partOfSpeech: "noun", category: "City", example: "Das Hotel liegt im Zentrum.", exampleEn: "The hotel is located in the center." },
  { german: "Park", english: "park", article: "der", partOfSpeech: "noun", category: "City", example: "Wir spazieren durch den Park.", exampleEn: "We walk through the park." },
  { german: "Bibliothek", english: "library", article: "die", partOfSpeech: "noun", category: "City", example: "Ich lerne in der Bibliothek.", exampleEn: "I study in the library." },
  { german: "Rathaus", english: "city hall / town hall", article: "das", partOfSpeech: "noun", category: "City", example: "Das Rathaus steht am Marktplatz.", exampleEn: "The town hall is at the market square." },
  { german: "Polizei", english: "police", article: "die", partOfSpeech: "noun", category: "City", example: "Ruf die Polizei an!", exampleEn: "Call the police!" },
  { german: "Feuerwehr", english: "fire department", article: "die", partOfSpeech: "noun", category: "City", example: "Die Feuerwehr kommt schnell.", exampleEn: "The fire department arrives quickly." },
  { german: "Gebäude", english: "building", article: "das", partOfSpeech: "noun", category: "City", example: "Das Gebäude ist sehr alt.", exampleEn: "The building is very old." },
  { german: "Supermarkt", english: "supermarket", article: "der", partOfSpeech: "noun", category: "City", example: "Ich gehe zum Supermarkt.", exampleEn: "I'm going to the supermarket." },
  { german: "Bäckerei", english: "bakery", article: "die", partOfSpeech: "noun", category: "City", example: "Die Bäckerei öffnet um sechs Uhr.", exampleEn: "The bakery opens at six o'clock." },
  { german: "Dorf", english: "village", article: "das", partOfSpeech: "noun", category: "City", example: "Das Dorf ist klein und ruhig.", exampleEn: "The village is small and quiet." },
  { german: "Stadtzentrum", english: "city center", article: "das", partOfSpeech: "noun", category: "City", example: "Das Hotel ist im Stadtzentrum.", exampleEn: "The hotel is in the city center." },
  { german: "Ecke", english: "corner", article: "die", partOfSpeech: "noun", category: "City", example: "Die Apotheke ist um die Ecke.", exampleEn: "The pharmacy is around the corner." },
  { german: "Spielplatz", english: "playground", article: "der", partOfSpeech: "noun", category: "City", example: "Die Kinder spielen auf dem Spielplatz.", exampleEn: "The children play on the playground." },

  // ─── Technology ───────────────────────────────────────────────────
  { german: "Computer", english: "computer", article: "der", partOfSpeech: "noun", category: "Technology", example: "Der Computer ist kaputt.", exampleEn: "The computer is broken." },
  { german: "Internet", english: "internet", article: "das", partOfSpeech: "noun", category: "Technology", example: "Das Internet ist langsam.", exampleEn: "The internet is slow." },
  { german: "Handy", english: "cell phone", article: "das", partOfSpeech: "noun", category: "Technology", example: "Wo ist mein Handy?", exampleEn: "Where is my cell phone?" },
  { german: "Bildschirm", english: "screen / monitor", article: "der", partOfSpeech: "noun", category: "Technology", example: "Der Bildschirm ist zu klein.", exampleEn: "The screen is too small." },
  { german: "Drucker", english: "printer", article: "der", partOfSpeech: "noun", category: "Technology", example: "Der Drucker funktioniert nicht.", exampleEn: "The printer doesn't work." },
  { german: "Tastatur", english: "keyboard", article: "die", partOfSpeech: "noun", category: "Technology", example: "Die Tastatur ist neu.", exampleEn: "The keyboard is new." },
  { german: "Nachricht", english: "message", article: "die", partOfSpeech: "noun", category: "Technology", example: "Ich habe eine Nachricht bekommen.", exampleEn: "I received a message." },
  { german: "E-Mail", english: "email", article: "die", partOfSpeech: "noun", category: "Technology", example: "Ich schicke dir eine E-Mail.", exampleEn: "I'll send you an email." },
  { german: "Webseite", english: "website", article: "die", partOfSpeech: "noun", category: "Technology", example: "Die Webseite ist sehr übersichtlich.", exampleEn: "The website is very clear." },
  { german: "Passwort", english: "password", article: "das", partOfSpeech: "noun", category: "Technology", example: "Ich habe mein Passwort vergessen.", exampleEn: "I forgot my password." },
  { german: "Datei", english: "file", article: "die", partOfSpeech: "noun", category: "Technology", example: "Die Datei ist zu groß.", exampleEn: "The file is too large." },
  { german: "Programm", english: "program / show", article: "das", partOfSpeech: "noun", category: "Technology", example: "Welches Programm benutzt du?", exampleEn: "Which program do you use?" },
  { german: "Kamera", english: "camera", article: "die", partOfSpeech: "noun", category: "Technology", example: "Ich habe eine neue Kamera.", exampleEn: "I have a new camera." },
  { german: "Foto", english: "photo", article: "das", partOfSpeech: "noun", category: "Technology", example: "Das Foto ist sehr schön.", exampleEn: "The photo is very nice." },
  { german: "Fernseher", english: "television / TV set", article: "der", partOfSpeech: "noun", category: "Technology", example: "Der Fernseher ist aus.", exampleEn: "The TV is off." },
  { german: "Radio", english: "radio", article: "das", partOfSpeech: "noun", category: "Technology", example: "Ich höre Radio beim Kochen.", exampleEn: "I listen to the radio while cooking." },
  { german: "Maschine", english: "machine", article: "die", partOfSpeech: "noun", category: "Technology", example: "Die Maschine arbeitet automatisch.", exampleEn: "The machine works automatically." },
  { german: "Batterie", english: "battery", article: "die", partOfSpeech: "noun", category: "Technology", example: "Die Batterie ist leer.", exampleEn: "The battery is dead." },

  // ─── Sports ───────────────────────────────────────────────────────
  { german: "Sport", english: "sport / exercise", article: "der", partOfSpeech: "noun", category: "Sports", example: "Sport ist gesund.", exampleEn: "Exercise is healthy." },
  { german: "Fußball", english: "soccer / football", article: "der", partOfSpeech: "noun", category: "Sports", example: "Wir spielen am Wochenende Fußball.", exampleEn: "We play soccer on the weekend." },
  { german: "Spiel", english: "game / match", article: "das", partOfSpeech: "noun", category: "Sports", example: "Das Spiel beginnt um drei.", exampleEn: "The game starts at three." },
  { german: "Mannschaft", english: "team", article: "die", partOfSpeech: "noun", category: "Sports", example: "Unsere Mannschaft hat gewonnen.", exampleEn: "Our team won." },
  { german: "Ball", english: "ball", article: "der", partOfSpeech: "noun", category: "Sports", example: "Wirf mir den Ball zu!", exampleEn: "Throw me the ball!" },
  { german: "Tor", english: "goal / gate", article: "das", partOfSpeech: "noun", category: "Sports", example: "Er hat ein Tor geschossen.", exampleEn: "He scored a goal." },
  { german: "Schwimmbad", english: "swimming pool", article: "das", partOfSpeech: "noun", category: "Sports", example: "Wir gehen ins Schwimmbad.", exampleEn: "We're going to the swimming pool." },
  { german: "Stadion", english: "stadium", article: "das", partOfSpeech: "noun", category: "Sports", example: "Das Stadion ist ausverkauft.", exampleEn: "The stadium is sold out." },
  { german: "Rennen", english: "race", article: "das", partOfSpeech: "noun", category: "Sports", example: "Das Rennen war sehr spannend.", exampleEn: "The race was very exciting." },
  { german: "Lauf", english: "run", article: "der", partOfSpeech: "noun", category: "Sports", example: "Der Lauf war zehn Kilometer lang.", exampleEn: "The run was ten kilometers long." },
  { german: "Training", english: "training / practice", article: "das", partOfSpeech: "noun", category: "Sports", example: "Das Training beginnt um sechs.", exampleEn: "Training starts at six." },
  { german: "Verein", english: "club / association", article: "der", partOfSpeech: "noun", category: "Sports", example: "Ich bin im Sportverein.", exampleEn: "I'm in the sports club." },
  { german: "Meisterschaft", english: "championship", article: "die", partOfSpeech: "noun", category: "Sports", example: "Die Meisterschaft findet im Mai statt.", exampleEn: "The championship takes place in May." },
  { german: "Rad", english: "wheel / bicycle", article: "das", partOfSpeech: "noun", category: "Sports", example: "Ich fahre gerne Rad.", exampleEn: "I like to ride a bike." },
  { german: "Helm", english: "helmet", article: "der", partOfSpeech: "noun", category: "Sports", example: "Trag immer einen Helm beim Radfahren.", exampleEn: "Always wear a helmet when cycling." },

  // ─── Emotions ─────────────────────────────────────────────────────
  { german: "Freude", english: "joy / happiness", article: "die", partOfSpeech: "noun", category: "Emotions", example: "Die Freude war groß.", exampleEn: "The joy was great." },
  { german: "Angst", english: "fear / anxiety", article: "die", partOfSpeech: "noun", category: "Emotions", example: "Sie hat Angst vor Spinnen.", exampleEn: "She is afraid of spiders." },
  { german: "Wut", english: "anger / rage", article: "die", partOfSpeech: "noun", category: "Emotions", example: "Er konnte seine Wut nicht kontrollieren.", exampleEn: "He couldn't control his anger." },
  { german: "Trauer", english: "sadness / grief", article: "die", partOfSpeech: "noun", category: "Emotions", example: "Die Trauer war tief.", exampleEn: "The grief was deep." },
  { german: "Glück", english: "happiness / luck", article: "das", partOfSpeech: "noun", category: "Emotions", example: "Das war großes Glück!", exampleEn: "That was great luck!" },
  { german: "Hoffnung", english: "hope", article: "die", partOfSpeech: "noun", category: "Emotions", example: "Die Hoffnung stirbt zuletzt.", exampleEn: "Hope dies last." },
  { german: "Sorge", english: "worry / concern", article: "die", partOfSpeech: "noun", category: "Emotions", example: "Mach dir keine Sorgen!", exampleEn: "Don't worry!" },
  { german: "Überraschung", english: "surprise", article: "die", partOfSpeech: "noun", category: "Emotions", example: "Das war eine schöne Überraschung.", exampleEn: "That was a nice surprise." },
  { german: "Vertrauen", english: "trust", article: "das", partOfSpeech: "noun", category: "Emotions", example: "Vertrauen ist sehr wichtig.", exampleEn: "Trust is very important." },
  { german: "Mut", english: "courage", article: "der", partOfSpeech: "noun", category: "Emotions", example: "Dafür braucht man Mut.", exampleEn: "That takes courage." },
  { german: "Gefühl", english: "feeling / emotion", article: "das", partOfSpeech: "noun", category: "Emotions", example: "Ich habe ein gutes Gefühl.", exampleEn: "I have a good feeling." },
  { german: "Lust", english: "desire / pleasure", article: "die", partOfSpeech: "noun", category: "Emotions", example: "Hast du Lust auf ein Eis?", exampleEn: "Do you feel like having ice cream?" },
  { german: "Langeweile", english: "boredom", article: "die", partOfSpeech: "noun", category: "Emotions", example: "Mir ist vor Langeweile fast eingeschlafen.", exampleEn: "I almost fell asleep from boredom." },
  { german: "Stolz", english: "pride", article: "der", partOfSpeech: "noun", category: "Emotions", example: "Er ist voller Stolz auf seine Tochter.", exampleEn: "He is full of pride for his daughter." },

  // ─── Time ─────────────────────────────────────────────────────────
  { german: "Morgen", english: "morning", article: "der", partOfSpeech: "noun", category: "Time", example: "Am Morgen trinke ich Kaffee.", exampleEn: "In the morning I drink coffee." },
  { german: "Abend", english: "evening", article: "der", partOfSpeech: "noun", category: "Time", example: "Am Abend lese ich ein Buch.", exampleEn: "In the evening I read a book." },
  { german: "Mittag", english: "noon / midday", article: "der", partOfSpeech: "noun", category: "Time", example: "Um Mittag essen wir zu Hause.", exampleEn: "At noon we eat at home." },
  { german: "Mitternacht", english: "midnight", article: "die", partOfSpeech: "noun", category: "Time", example: "Um Mitternacht gehen wir schlafen.", exampleEn: "At midnight we go to sleep." },
  { german: "Wochenende", english: "weekend", article: "das", partOfSpeech: "noun", category: "Time", example: "Am Wochenende fahren wir weg.", exampleEn: "On the weekend we're going away." },
  { german: "Montag", english: "Monday", article: "der", partOfSpeech: "noun", category: "Time", example: "Am Montag fängt die Arbeit an.", exampleEn: "Work starts on Monday." },
  { german: "Dienstag", english: "Tuesday", article: "der", partOfSpeech: "noun", category: "Time", example: "Am Dienstag habe ich Deutschkurs.", exampleEn: "On Tuesday I have German class." },
  { german: "Mittwoch", english: "Wednesday", article: "der", partOfSpeech: "noun", category: "Time", example: "Mittwoch ist die Mitte der Woche.", exampleEn: "Wednesday is the middle of the week." },
  { german: "Donnerstag", english: "Thursday", article: "der", partOfSpeech: "noun", category: "Time", example: "Am Donnerstag gehe ich zum Sport.", exampleEn: "On Thursday I go to exercise." },
  { german: "Freitag", english: "Friday", article: "der", partOfSpeech: "noun", category: "Time", example: "Freitag ist mein Lieblingstag.", exampleEn: "Friday is my favorite day." },
  { german: "Samstag", english: "Saturday", article: "der", partOfSpeech: "noun", category: "Time", example: "Am Samstag gehen wir einkaufen.", exampleEn: "On Saturday we go shopping." },
  { german: "Sonntag", english: "Sunday", article: "der", partOfSpeech: "noun", category: "Time", example: "Am Sonntag ruhen wir uns aus.", exampleEn: "On Sunday we rest." },
  { german: "Frühling", english: "spring", article: "der", partOfSpeech: "noun", category: "Time", example: "Im Frühling blühen die Blumen.", exampleEn: "In spring the flowers bloom." },
  { german: "Sommer", english: "summer", article: "der", partOfSpeech: "noun", category: "Time", example: "Im Sommer fahren wir ans Meer.", exampleEn: "In summer we go to the sea." },
  { german: "Herbst", english: "autumn / fall", article: "der", partOfSpeech: "noun", category: "Time", example: "Im Herbst werden die Blätter bunt.", exampleEn: "In autumn the leaves turn colorful." },
  { german: "Winter", english: "winter", article: "der", partOfSpeech: "noun", category: "Time", example: "Im Winter ist es kalt und dunkel.", exampleEn: "In winter it's cold and dark." },
  { german: "Vergangenheit", english: "past", article: "die", partOfSpeech: "noun", category: "Time", example: "Das liegt in der Vergangenheit.", exampleEn: "That lies in the past." },
  { german: "Zukunft", english: "future", article: "die", partOfSpeech: "noun", category: "Time", example: "Niemand kennt die Zukunft.", exampleEn: "Nobody knows the future." },
  { german: "Gegenwart", english: "present / present time", article: "die", partOfSpeech: "noun", category: "Time", example: "Lebe in der Gegenwart.", exampleEn: "Live in the present." },
  { german: "Anfang", english: "beginning", article: "der", partOfSpeech: "noun", category: "Time", example: "Am Anfang war es schwer.", exampleEn: "In the beginning it was hard." },
  { german: "Ende", english: "end", article: "das", partOfSpeech: "noun", category: "Time", example: "Das Ende des Films war traurig.", exampleEn: "The end of the film was sad." },
  { german: "Moment", english: "moment", article: "der", partOfSpeech: "noun", category: "Time", example: "Einen Moment bitte.", exampleEn: "One moment please." },
  { german: "Datum", english: "date", article: "das", partOfSpeech: "noun", category: "Time", example: "Welches Datum ist heute?", exampleEn: "What is today's date?" },
  { german: "Jahrhundert", english: "century", article: "das", partOfSpeech: "noun", category: "Time", example: "Das Gebäude ist aus dem 18. Jahrhundert.", exampleEn: "The building is from the 18th century." },
  { german: "Geburtstag", english: "birthday", article: "der", partOfSpeech: "noun", category: "Time", example: "Wann hast du Geburtstag?", exampleEn: "When is your birthday?" },
  { german: "Feiertag", english: "holiday / public holiday", article: "der", partOfSpeech: "noun", category: "Time", example: "Morgen ist ein Feiertag.", exampleEn: "Tomorrow is a holiday." },
  { german: "Sekunde", english: "second", article: "die", partOfSpeech: "noun", category: "Time", example: "Warte eine Sekunde.", exampleEn: "Wait a second." },

  // ─── Abstract ─────────────────────────────────────────────────────
  { german: "Idee", english: "idea", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Das ist eine gute Idee.", exampleEn: "That's a good idea." },
  { german: "Meinung", english: "opinion", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Was ist deine Meinung?", exampleEn: "What is your opinion?" },
  { german: "Grund", english: "reason", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Es gibt einen guten Grund dafür.", exampleEn: "There is a good reason for that." },
  { german: "Ziel", english: "goal / destination", article: "das", partOfSpeech: "noun", category: "Abstract", example: "Mein Ziel ist es, Deutsch zu lernen.", exampleEn: "My goal is to learn German." },
  { german: "Recht", english: "right / law", article: "das", partOfSpeech: "noun", category: "Abstract", example: "Jeder hat das Recht auf Bildung.", exampleEn: "Everyone has the right to education." },
  { german: "Regel", english: "rule", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Man muss die Regeln beachten.", exampleEn: "One must follow the rules." },
  { german: "Wahrheit", english: "truth", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Sag mir die Wahrheit.", exampleEn: "Tell me the truth." },
  { german: "Freiheit", english: "freedom", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Freiheit ist ein wichtiger Wert.", exampleEn: "Freedom is an important value." },
  { german: "Möglichkeit", english: "possibility / opportunity", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Es gibt viele Möglichkeiten.", exampleEn: "There are many possibilities." },
  { german: "Unterschied", english: "difference", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Was ist der Unterschied?", exampleEn: "What is the difference?" },
  { german: "Bedeutung", english: "meaning / importance", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Das Wort hat zwei Bedeutungen.", exampleEn: "The word has two meanings." },
  { german: "Beispiel", english: "example", article: "das", partOfSpeech: "noun", category: "Abstract", example: "Können Sie mir ein Beispiel geben?", exampleEn: "Can you give me an example?" },
  { german: "Erfolg", english: "success", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Viel Erfolg bei der Prüfung!", exampleEn: "Good luck on the exam!" },
  { german: "Fehler", english: "mistake / error", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Jeder macht Fehler.", exampleEn: "Everyone makes mistakes." },
  { german: "Lösung", english: "solution", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Wir finden eine Lösung.", exampleEn: "We'll find a solution." },
  { german: "Entscheidung", english: "decision", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Das war eine schwierige Entscheidung.", exampleEn: "That was a difficult decision." },
  { german: "Verantwortung", english: "responsibility", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Das ist eine große Verantwortung.", exampleEn: "That is a big responsibility." },
  { german: "Interesse", english: "interest", article: "das", partOfSpeech: "noun", category: "Abstract", example: "Ich habe großes Interesse an Kunst.", exampleEn: "I have a great interest in art." },
  { german: "Wunsch", english: "wish", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Ich habe einen Wunsch.", exampleEn: "I have a wish." },
  { german: "Traum", english: "dream", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Ich hatte einen schönen Traum.", exampleEn: "I had a nice dream." },
  { german: "Gedanke", english: "thought", article: "der", partOfSpeech: "noun", category: "Abstract", weakNoun: true, example: "Das ist ein guter Gedanke.", exampleEn: "That's a good thought." },
  { german: "Erinnerung", english: "memory / reminder", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Das ist eine schöne Erinnerung.", exampleEn: "That's a nice memory." },
  { german: "Wissen", english: "knowledge", article: "das", partOfSpeech: "noun", category: "Abstract", example: "Wissen ist Macht.", exampleEn: "Knowledge is power." },
  { german: "Kultur", english: "culture", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Die deutsche Kultur ist vielfältig.", exampleEn: "German culture is diverse." },
  { german: "Gesellschaft", english: "society", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Die Gesellschaft verändert sich.", exampleEn: "Society is changing." },
  { german: "Kraft", english: "strength / power", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Ich habe keine Kraft mehr.", exampleEn: "I have no more strength." },
  { german: "Sicherheit", english: "safety / security", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Sicherheit ist sehr wichtig.", exampleEn: "Safety is very important." },
  { german: "Hilfe", english: "help", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Ich brauche Hilfe.", exampleEn: "I need help." },
  { german: "Änderung", english: "change / modification", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Es gibt eine Änderung im Plan.", exampleEn: "There is a change in the plan." },
  { german: "Beziehung", english: "relationship", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Sie haben eine gute Beziehung.", exampleEn: "They have a good relationship." },
  { german: "Frieden", english: "peace", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Alle Menschen wünschen sich Frieden.", exampleEn: "All people wish for peace." },
  { german: "Zustand", english: "condition / state", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Das Haus ist in gutem Zustand.", exampleEn: "The house is in good condition." },
  { german: "Auswahl", english: "selection / choice", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Die Auswahl ist groß.", exampleEn: "The selection is large." },
  { german: "Vorteil", english: "advantage", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Das hat viele Vorteile.", exampleEn: "That has many advantages." },
  { german: "Nachteil", english: "disadvantage", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Der einzige Nachteil ist der Preis.", exampleEn: "The only disadvantage is the price." },
  { german: "Sinn", english: "sense / meaning", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Das macht keinen Sinn.", exampleEn: "That doesn't make sense." },
  { german: "Weise", english: "way / manner", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Auf diese Weise geht es schneller.", exampleEn: "This way it goes faster." },
  { german: "Einfluss", english: "influence", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Musik hat einen großen Einfluss auf mich.", exampleEn: "Music has a big influence on me." },
  { german: "Zusammenhang", english: "context / connection", article: "der", partOfSpeech: "noun", category: "Abstract", example: "In diesem Zusammenhang ist das wichtig.", exampleEn: "In this context that is important." },
  { german: "Vorstellung", english: "idea / introduction / performance", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Ich habe keine Vorstellung davon.", exampleEn: "I have no idea about it." },
  { german: "Auftrag", english: "order / assignment", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Wir haben einen neuen Auftrag.", exampleEn: "We have a new assignment." },
  { german: "Preis", english: "price / prize", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Der Preis ist zu hoch.", exampleEn: "The price is too high." },
  { german: "Wert", english: "value / worth", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Das hat einen großen Wert.", exampleEn: "That has great value." },
  { german: "Form", english: "form / shape", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Die Form des Gebäudes ist ungewöhnlich.", exampleEn: "The shape of the building is unusual." },
  { german: "Seite", english: "page / side", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Öffnen Sie das Buch auf Seite zehn.", exampleEn: "Open the book to page ten." },
  { german: "Teil", english: "part", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Das ist ein wichtiger Teil des Plans.", exampleEn: "That is an important part of the plan." },
  { german: "Stück", english: "piece", article: "das", partOfSpeech: "noun", category: "Abstract", example: "Ich hätte gerne ein Stück Kuchen.", exampleEn: "I would like a piece of cake." },
  { german: "Gruppe", english: "group", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Die Gruppe trifft sich um drei.", exampleEn: "The group meets at three." },
  { german: "Nummer", english: "number", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Was ist Ihre Telefonnummer?", exampleEn: "What is your phone number?" },
  { german: "Name", english: "name", article: "der", partOfSpeech: "noun", category: "Abstract", weakNoun: true, example: "Wie ist Ihr Name?", exampleEn: "What is your name?" },
  { german: "Farbe", english: "color", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Welche Farbe magst du am liebsten?", exampleEn: "Which color do you like best?" },
  { german: "Größe", english: "size / height", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Welche Größe brauchen Sie?", exampleEn: "What size do you need?" },
  { german: "Richtung", english: "direction", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Geh in diese Richtung.", exampleEn: "Go in this direction." },
  { german: "Situation", english: "situation", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Die Situation ist schwierig.", exampleEn: "The situation is difficult." },
  { german: "Information", english: "information", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Ich brauche mehr Informationen.", exampleEn: "I need more information." },
  { german: "Entwicklung", english: "development", article: "die", partOfSpeech: "noun", category: "Abstract", example: "Die Entwicklung geht schnell voran.", exampleEn: "The development is progressing quickly." },
  { german: "Ergebnis", english: "result", article: "das", partOfSpeech: "noun", category: "Abstract", example: "Das Ergebnis war überraschend.", exampleEn: "The result was surprising." },
  { german: "Versuch", english: "attempt / experiment", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Der erste Versuch hat nicht geklappt.", exampleEn: "The first attempt didn't work." },
  { german: "Schutz", english: "protection", article: "der", partOfSpeech: "noun", category: "Abstract", example: "Diese Creme bietet Schutz vor der Sonne.", exampleEn: "This cream offers protection from the sun." },
];
