import type { VocabWordBase } from "../german-types";

export const EXPANDED_PREPOSITIONS: VocabWordBase[] = [
  // ─── Akkusativ ──────────────────────────────────────────────────
  {
    german: "durch",
    english: "through",
    partOfSpeech: "preposition",
    category: "Akkusativ",
    example: "Wir gehen durch den Park.",
    exampleEn: "We walk through the park.",
  },
  {
    german: "für",
    english: "for",
    partOfSpeech: "preposition",
    category: "Akkusativ",
    example: "Das Geschenk ist für dich.",
    exampleEn: "The gift is for you.",
  },
  {
    german: "gegen",
    english: "against",
    partOfSpeech: "preposition",
    category: "Akkusativ",
    example: "Er spielt gegen seinen Bruder.",
    exampleEn: "He plays against his brother.",
  },
  {
    german: "ohne",
    english: "without",
    partOfSpeech: "preposition",
    category: "Akkusativ",
    example: "Ich trinke Kaffee ohne Zucker.",
    exampleEn: "I drink coffee without sugar.",
  },
  {
    german: "um",
    english: "around; at (time)",
    partOfSpeech: "preposition",
    category: "Akkusativ",
    example: "Der Zug fährt um acht Uhr.",
    exampleEn: "The train leaves at eight o'clock.",
  },
  {
    german: "bis",
    english: "until; to",
    partOfSpeech: "preposition",
    category: "Akkusativ",
    example: "Ich arbeite bis fünf Uhr.",
    exampleEn: "I work until five o'clock.",
  },
  {
    german: "entlang",
    english: "along",
    partOfSpeech: "preposition",
    category: "Akkusativ",
    example: "Wir gehen den Fluss entlang.",
    exampleEn: "We walk along the river.",
  },
  {
    german: "wider",
    english: "against; contrary to",
    partOfSpeech: "preposition",
    category: "Akkusativ",
    example: "Das ist wider meine Erwartung.",
    exampleEn: "That is contrary to my expectation.",
  },

  // ─── Dativ ──────────────────────────────────────────────────────
  {
    german: "aus",
    english: "from; out of",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Ich komme aus Deutschland.",
    exampleEn: "I come from Germany.",
  },
  {
    german: "außer",
    english: "except for; besides",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Alle kommen außer dir.",
    exampleEn: "Everyone is coming except you.",
  },
  {
    german: "bei",
    english: "at; near; with (at someone's place)",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Ich wohne bei meinen Eltern.",
    exampleEn: "I live with my parents.",
  },
  {
    german: "gegenüber",
    english: "opposite; across from",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Die Bank ist gegenüber dem Supermarkt.",
    exampleEn: "The bank is across from the supermarket.",
  },
  {
    german: "mit",
    english: "with",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Ich fahre mit dem Bus.",
    exampleEn: "I go by bus.",
  },
  {
    german: "nach",
    english: "after; to (a place)",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Nach dem Essen gehe ich spazieren.",
    exampleEn: "After the meal I go for a walk.",
  },
  {
    german: "seit",
    english: "since; for (time)",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Ich lerne seit zwei Jahren Deutsch.",
    exampleEn: "I have been learning German for two years.",
  },
  {
    german: "von",
    english: "from; of; by",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Das Buch ist von meinem Freund.",
    exampleEn: "The book is from my friend.",
  },
  {
    german: "zu",
    english: "to; at",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Ich gehe zu Fuß zur Schule.",
    exampleEn: "I walk to school.",
  },
  {
    german: "ab",
    english: "from; starting from",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Ab morgen esse ich gesünder.",
    exampleEn: "Starting from tomorrow I will eat healthier.",
  },
  {
    german: "entsprechend",
    english: "according to; corresponding to",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Er handelt entsprechend den Regeln.",
    exampleEn: "He acts according to the rules.",
  },
  {
    german: "gemäß",
    english: "according to; in accordance with",
    partOfSpeech: "preposition",
    category: "Dativ",
    example: "Gemäß dem Gesetz ist das verboten.",
    exampleEn: "According to the law, that is forbidden.",
  },

  // ─── Two-Way / Wechselpräpositionen ────────────────────────────
  {
    german: "an",
    english: "at; on (vertical surface)",
    partOfSpeech: "preposition",
    category: "Wechsel (Two-Way)",
    example: "Das Bild hängt an der Wand.",
    exampleEn: "The picture hangs on the wall.",
  },
  {
    german: "auf",
    english: "on (horizontal surface); onto",
    partOfSpeech: "preposition",
    category: "Wechsel (Two-Way)",
    example: "Das Buch liegt auf dem Tisch.",
    exampleEn: "The book is on the table.",
  },
  {
    german: "hinter",
    english: "behind",
    partOfSpeech: "preposition",
    category: "Wechsel (Two-Way)",
    example: "Die Katze sitzt hinter dem Sofa.",
    exampleEn: "The cat is sitting behind the sofa.",
  },
  {
    german: "in",
    english: "in; into",
    partOfSpeech: "preposition",
    category: "Wechsel (Two-Way)",
    example: "Wir sind in der Schule.",
    exampleEn: "We are in school.",
  },
  {
    german: "neben",
    english: "next to; beside",
    partOfSpeech: "preposition",
    category: "Wechsel (Two-Way)",
    example: "Er sitzt neben mir.",
    exampleEn: "He sits next to me.",
  },
  {
    german: "über",
    english: "over; above; about",
    partOfSpeech: "preposition",
    category: "Wechsel (Two-Way)",
    example: "Die Lampe hängt über dem Tisch.",
    exampleEn: "The lamp hangs above the table.",
  },
  {
    german: "unter",
    english: "under; below; among",
    partOfSpeech: "preposition",
    category: "Wechsel (Two-Way)",
    example: "Die Schuhe stehen unter dem Bett.",
    exampleEn: "The shoes are under the bed.",
  },
  {
    german: "vor",
    english: "in front of; before; ago",
    partOfSpeech: "preposition",
    category: "Wechsel (Two-Way)",
    example: "Er wartet vor dem Kino.",
    exampleEn: "He is waiting in front of the cinema.",
  },
  {
    german: "zwischen",
    english: "between",
    partOfSpeech: "preposition",
    category: "Wechsel (Two-Way)",
    example: "Der Park liegt zwischen der Schule und dem Krankenhaus.",
    exampleEn: "The park is between the school and the hospital.",
  },

  // ─── Genitiv ────────────────────────────────────────────────────
  {
    german: "anstatt",
    english: "instead of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Anstatt des Autos nehme ich das Fahrrad.",
    exampleEn: "Instead of the car, I take the bicycle.",
  },
  {
    german: "statt",
    english: "instead of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Statt eines Kuchens bringe ich Obst mit.",
    exampleEn: "Instead of a cake, I bring fruit.",
  },
  {
    german: "außerhalb",
    english: "outside of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Er wohnt außerhalb der Stadt.",
    exampleEn: "He lives outside the city.",
  },
  {
    german: "innerhalb",
    english: "inside of; within",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Innerhalb der Stadt gibt es viele Parks.",
    exampleEn: "Within the city there are many parks.",
  },
  {
    german: "trotz",
    english: "despite; in spite of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Trotz des Regens gehen wir spazieren.",
    exampleEn: "Despite the rain we go for a walk.",
  },
  {
    german: "während",
    english: "during",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Während des Sommers reise ich viel.",
    exampleEn: "During the summer I travel a lot.",
  },
  {
    german: "wegen",
    english: "because of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Wegen des Wetters bleiben wir zu Hause.",
    exampleEn: "Because of the weather we stay at home.",
  },
  {
    german: "oberhalb",
    english: "above",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Das Dorf liegt oberhalb des Tals.",
    exampleEn: "The village is above the valley.",
  },
  {
    german: "unterhalb",
    english: "below",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Der See liegt unterhalb des Berges.",
    exampleEn: "The lake is below the mountain.",
  },
  {
    german: "diesseits",
    english: "on this side of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Diesseits des Flusses gibt es einen Wald.",
    exampleEn: "On this side of the river there is a forest.",
  },
  {
    german: "jenseits",
    english: "on the other side of; beyond",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Jenseits der Grenze liegt Österreich.",
    exampleEn: "On the other side of the border is Austria.",
  },
  {
    german: "laut",
    english: "according to",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Laut des Berichts steigen die Preise.",
    exampleEn: "According to the report, prices are rising.",
  },
  {
    german: "mittels",
    english: "by means of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Man kann mittels einer App bezahlen.",
    exampleEn: "You can pay by means of an app.",
  },
  {
    german: "mangels",
    english: "for lack of; due to lack of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Mangels Beweisen wurde er freigesprochen.",
    exampleEn: "For lack of evidence he was acquitted.",
  },
  {
    german: "aufgrund",
    english: "on the basis of; due to",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Aufgrund des Unfalls gibt es einen Stau.",
    exampleEn: "Due to the accident there is a traffic jam.",
  },
  {
    german: "infolge",
    english: "as a result of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Infolge des Sturms fiel der Strom aus.",
    exampleEn: "As a result of the storm the power went out.",
  },
  {
    german: "anhand",
    english: "on the basis of; by means of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Anhand der Karte finden wir den Weg.",
    exampleEn: "By means of the map we find the way.",
  },
  {
    german: "zugunsten",
    english: "in favor of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Er verzichtet zugunsten seiner Schwester.",
    exampleEn: "He gives up in favor of his sister.",
  },
  {
    german: "zuungunsten",
    english: "to the disadvantage of",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Die Entscheidung fiel zuungunsten des Klägers.",
    exampleEn: "The decision was to the disadvantage of the plaintiff.",
  },
  {
    german: "abseits",
    english: "away from; off",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Das Haus steht abseits der Straße.",
    exampleEn: "The house stands away from the road.",
  },
  {
    german: "bezüglich",
    english: "regarding; concerning",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Bezüglich Ihrer Frage habe ich eine Antwort.",
    exampleEn: "Regarding your question, I have an answer.",
  },
  {
    german: "hinsichtlich",
    english: "with regard to; concerning",
    partOfSpeech: "preposition",
    category: "Genitiv",
    example: "Hinsichtlich der Kosten müssen wir sparen.",
    exampleEn: "With regard to costs, we need to save.",
  },
];
