import type { VocabWordBase } from "../german-types";

export const EXPANDED_VERBS: VocabWordBase[] = [
  // ─── Essential ──────────────────────────────────────────────────
  { german: "tun", english: "to do", partOfSpeech: "verb", category: "Essential", example: "Was tust du gerade?", exampleEn: "What are you doing right now?" },
  { german: "lassen", english: "to let / to leave", partOfSpeech: "verb", category: "Essential", example: "Lass mich in Ruhe!", exampleEn: "Leave me alone!" },
  { german: "halten", english: "to hold / to stop", partOfSpeech: "verb", category: "Essential", example: "Kannst du das bitte halten?", exampleEn: "Can you hold this please?" },
  { german: "bringen", english: "to bring", partOfSpeech: "verb", category: "Essential", example: "Ich bringe dir ein Glas Wasser.", exampleEn: "I'll bring you a glass of water." },
  { german: "tragen", english: "to carry / to wear", partOfSpeech: "verb", category: "Essential", example: "Sie trägt einen roten Mantel.", exampleEn: "She is wearing a red coat." },
  { german: "legen", english: "to lay / to put", partOfSpeech: "verb", category: "Essential", example: "Leg das Buch auf den Tisch.", exampleEn: "Put the book on the table." },
  { german: "stellen", english: "to place / to put (upright)", partOfSpeech: "verb", category: "Essential", example: "Stell die Flasche in den Kühlschrank.", exampleEn: "Put the bottle in the fridge." },
  { german: "ziehen", english: "to pull / to move", partOfSpeech: "verb", category: "Essential", example: "Zieh bitte die Tür zu.", exampleEn: "Please pull the door shut." },
  { german: "drücken", english: "to push / to press", partOfSpeech: "verb", category: "Essential", example: "Drück den Knopf.", exampleEn: "Press the button." },
  { german: "heißen", english: "to be called", partOfSpeech: "verb", category: "Essential", example: "Wie heißt du?", exampleEn: "What is your name?" },
  { german: "scheinen", english: "to seem / to shine", partOfSpeech: "verb", category: "Essential", example: "Die Sonne scheint heute.", exampleEn: "The sun is shining today." },
  { german: "fallen", english: "to fall", partOfSpeech: "verb", category: "Essential", example: "Die Blätter fallen im Herbst.", exampleEn: "The leaves fall in autumn." },
  { german: "liegen", english: "to lie / to be situated", partOfSpeech: "verb", category: "Essential", example: "Das Buch liegt auf dem Tisch.", exampleEn: "The book is on the table." },
  { german: "zeigen", english: "to show", partOfSpeech: "verb", category: "Essential", example: "Kannst du mir den Weg zeigen?", exampleEn: "Can you show me the way?" },
  { german: "führen", english: "to lead / to guide", partOfSpeech: "verb", category: "Essential", example: "Er führt die Gruppe durch die Stadt.", exampleEn: "He leads the group through the city." },
  { german: "beginnen", english: "to begin", partOfSpeech: "verb", category: "Essential", example: "Der Film beginnt um acht Uhr.", exampleEn: "The movie begins at eight o'clock." },
  { german: "versuchen", english: "to try / to attempt", partOfSpeech: "verb", category: "Essential", example: "Ich versuche, pünktlich zu sein.", exampleEn: "I try to be on time." },
  { german: "bekommen", english: "to get / to receive", partOfSpeech: "verb", category: "Essential", example: "Ich habe ein Paket bekommen.", exampleEn: "I received a package." },
  { german: "erreichen", english: "to reach / to achieve", partOfSpeech: "verb", category: "Essential", example: "Wir haben unser Ziel erreicht.", exampleEn: "We reached our goal." },
  { german: "schaffen", english: "to manage / to create", partOfSpeech: "verb", category: "Essential", example: "Du schaffst das!", exampleEn: "You can do it!" },
  { german: "gehören", english: "to belong to", partOfSpeech: "verb", category: "Essential", example: "Das Buch gehört mir.", exampleEn: "The book belongs to me." },
  { german: "erscheinen", english: "to appear", partOfSpeech: "verb", category: "Essential", example: "Das Buch erscheint nächsten Monat.", exampleEn: "The book appears next month." },
  { german: "bestehen", english: "to exist / to pass (an exam)", partOfSpeech: "verb", category: "Essential", example: "Er hat die Prüfung bestanden.", exampleEn: "He passed the exam." },
  { german: "entstehen", english: "to arise / to develop", partOfSpeech: "verb", category: "Essential", example: "Dabei entstehen keine Kosten.", exampleEn: "No costs arise from this." },
  { german: "erhalten", english: "to receive / to maintain", partOfSpeech: "verb", category: "Essential", example: "Ich habe deine Nachricht erhalten.", exampleEn: "I received your message." },
  { german: "bilden", english: "to form / to educate", partOfSpeech: "verb", category: "Essential", example: "Die Kinder bilden einen Kreis.", exampleEn: "The children form a circle." },
  { german: "ergeben", english: "to result in / to yield", partOfSpeech: "verb", category: "Essential", example: "Die Umfrage ergibt ein klares Bild.", exampleEn: "The survey yields a clear picture." },
  { german: "handeln", english: "to act / to trade", partOfSpeech: "verb", category: "Essential", example: "Wir müssen schnell handeln.", exampleEn: "We must act quickly." },
  { german: "fehlen", english: "to be missing / to lack", partOfSpeech: "verb", category: "Essential", example: "Mir fehlt meine Familie.", exampleEn: "I miss my family." },
  { german: "bedeuten", english: "to mean / to signify", partOfSpeech: "verb", category: "Essential", example: "Was bedeutet dieses Wort?", exampleEn: "What does this word mean?" },
  { german: "nutzen", english: "to use / to utilize", partOfSpeech: "verb", category: "Essential", example: "Wir nutzen das Internet jeden Tag.", exampleEn: "We use the internet every day." },
  { german: "gelten", english: "to be valid / to apply", partOfSpeech: "verb", category: "Essential", example: "Diese Regel gilt für alle.", exampleEn: "This rule applies to everyone." },
  { german: "schauen", english: "to look / to watch", partOfSpeech: "verb", category: "Essential", example: "Schau mal aus dem Fenster!", exampleEn: "Look out the window!" },
  { german: "bieten", english: "to offer", partOfSpeech: "verb", category: "Essential", example: "Das Hotel bietet viele Aktivitäten.", exampleEn: "The hotel offers many activities." },
  { german: "warten", english: "to wait", partOfSpeech: "verb", category: "Essential", example: "Ich warte auf den Bus.", exampleEn: "I'm waiting for the bus." },

  // ─── Modal & Auxiliary ──────────────────────────────────────────
  { german: "pflegen", english: "to be accustomed to / to care for", partOfSpeech: "verb", category: "Modal", example: "Sie pflegt ihre Großmutter.", exampleEn: "She cares for her grandmother." },
  { german: "scheinen", english: "to seem / to appear", partOfSpeech: "verb", category: "Modal", example: "Er scheint müde zu sein.", exampleEn: "He seems to be tired." },
  { german: "vermögen", english: "to be able to (formal)", partOfSpeech: "verb", category: "Modal", example: "Ich vermag das nicht zu erklären.", exampleEn: "I am unable to explain that." },

  // ─── Communication ──────────────────────────────────────────────
  { german: "erzählen", english: "to tell / to narrate", partOfSpeech: "verb", category: "Communication", example: "Er erzählt eine Geschichte.", exampleEn: "He tells a story." },
  { german: "fragen", english: "to ask", partOfSpeech: "verb", category: "Communication", example: "Darf ich dich etwas fragen?", exampleEn: "May I ask you something?" },
  { german: "antworten", english: "to answer", partOfSpeech: "verb", category: "Communication", example: "Sie antwortet sofort.", exampleEn: "She answers immediately." },
  { german: "erklären", english: "to explain", partOfSpeech: "verb", category: "Communication", example: "Kannst du mir das erklären?", exampleEn: "Can you explain that to me?" },
  { german: "beschreiben", english: "to describe", partOfSpeech: "verb", category: "Communication", example: "Beschreibe dein Haus.", exampleEn: "Describe your house." },
  { german: "rufen", english: "to call / to shout", partOfSpeech: "verb", category: "Communication", example: "Sie ruft seinen Namen.", exampleEn: "She calls his name." },
  { german: "anrufen", english: "to call (on the phone)", partOfSpeech: "verb", category: "Communication", example: "Ich rufe dich morgen an.", exampleEn: "I'll call you tomorrow." },
  { german: "reden", english: "to talk", partOfSpeech: "verb", category: "Communication", example: "Wir müssen darüber reden.", exampleEn: "We need to talk about it." },
  { german: "meinen", english: "to mean / to think", partOfSpeech: "verb", category: "Communication", example: "Was meinst du damit?", exampleEn: "What do you mean by that?" },
  { german: "behaupten", english: "to claim / to assert", partOfSpeech: "verb", category: "Communication", example: "Er behauptet, er war nicht da.", exampleEn: "He claims he wasn't there." },
  { german: "berichten", english: "to report", partOfSpeech: "verb", category: "Communication", example: "Die Zeitung berichtet über das Ereignis.", exampleEn: "The newspaper reports on the event." },
  { german: "mitteilen", english: "to inform / to communicate", partOfSpeech: "verb", category: "Communication", example: "Ich muss dir etwas mitteilen.", exampleEn: "I have to tell you something." },
  { german: "besprechen", english: "to discuss", partOfSpeech: "verb", category: "Communication", example: "Wir besprechen das Problem morgen.", exampleEn: "We'll discuss the problem tomorrow." },
  { german: "übersetzen", english: "to translate", partOfSpeech: "verb", category: "Communication", example: "Kannst du das ins Englische übersetzen?", exampleEn: "Can you translate that into English?" },
  { german: "erwähnen", english: "to mention", partOfSpeech: "verb", category: "Communication", example: "Er hat das nie erwähnt.", exampleEn: "He never mentioned that." },
  { german: "betonen", english: "to emphasize / to stress", partOfSpeech: "verb", category: "Communication", example: "Sie betont die Wichtigkeit der Übung.", exampleEn: "She emphasizes the importance of practice." },
  { german: "bitten", english: "to ask / to request", partOfSpeech: "verb", category: "Communication", example: "Ich bitte dich um Hilfe.", exampleEn: "I'm asking you for help." },
  { german: "versprechen", english: "to promise", partOfSpeech: "verb", category: "Communication", example: "Ich verspreche dir, pünktlich zu sein.", exampleEn: "I promise you to be on time." },
  { german: "vorschlagen", english: "to suggest / to propose", partOfSpeech: "verb", category: "Communication", example: "Ich schlage einen Spaziergang vor.", exampleEn: "I suggest a walk." },
  { german: "sich unterhalten", english: "to have a conversation", partOfSpeech: "verb", category: "Communication", example: "Wir unterhalten uns über das Wetter.", exampleEn: "We're chatting about the weather." },
  { german: "flüstern", english: "to whisper", partOfSpeech: "verb", category: "Communication", example: "Sie flüstert ihm etwas ins Ohr.", exampleEn: "She whispers something in his ear." },
  { german: "schreien", english: "to scream / to shout", partOfSpeech: "verb", category: "Communication", example: "Das Kind schreit laut.", exampleEn: "The child screams loudly." },
  { german: "schweigen", english: "to be silent", partOfSpeech: "verb", category: "Communication", example: "Er schweigt und sagt nichts.", exampleEn: "He remains silent and says nothing." },
  { german: "diskutieren", english: "to discuss / to debate", partOfSpeech: "verb", category: "Communication", example: "Wir diskutieren über Politik.", exampleEn: "We discuss politics." },
  { german: "zustimmen", english: "to agree", partOfSpeech: "verb", category: "Communication", example: "Ich stimme dir zu.", exampleEn: "I agree with you." },
  { german: "widersprechen", english: "to contradict", partOfSpeech: "verb", category: "Communication", example: "Er widerspricht mir ständig.", exampleEn: "He constantly contradicts me." },
  { german: "sich entschuldigen", english: "to apologize", partOfSpeech: "verb", category: "Communication", example: "Ich entschuldige mich für die Verspätung.", exampleEn: "I apologize for the delay." },
  { german: "grüßen", english: "to greet", partOfSpeech: "verb", category: "Communication", example: "Sie grüßt ihre Nachbarn freundlich.", exampleEn: "She greets her neighbors kindly." },
  { german: "sich verabschieden", english: "to say goodbye", partOfSpeech: "verb", category: "Communication", example: "Wir verabschieden uns am Bahnhof.", exampleEn: "We say goodbye at the train station." },
  { german: "danken", english: "to thank", partOfSpeech: "verb", category: "Communication", example: "Ich danke dir für deine Hilfe.", exampleEn: "I thank you for your help." },
  { german: "loben", english: "to praise", partOfSpeech: "verb", category: "Communication", example: "Die Lehrerin lobt den Schüler.", exampleEn: "The teacher praises the student." },
  { german: "kritisieren", english: "to criticize", partOfSpeech: "verb", category: "Communication", example: "Er kritisiert meine Arbeit oft.", exampleEn: "He often criticizes my work." },
  { german: "warnen", english: "to warn", partOfSpeech: "verb", category: "Communication", example: "Sie warnt ihn vor der Gefahr.", exampleEn: "She warns him of the danger." },
  { german: "sich beschweren", english: "to complain", partOfSpeech: "verb", category: "Communication", example: "Er beschwert sich über den Lärm.", exampleEn: "He complains about the noise." },
  { german: "lügen", english: "to lie (tell untruths)", partOfSpeech: "verb", category: "Communication", example: "Du sollst nicht lügen.", exampleEn: "You should not lie." },
  { german: "zugeben", english: "to admit", partOfSpeech: "verb", category: "Communication", example: "Er gibt seinen Fehler zu.", exampleEn: "He admits his mistake." },

  // ─── Movement ───────────────────────────────────────────────────
  { german: "rennen", english: "to run", partOfSpeech: "verb", category: "Movement", example: "Die Kinder rennen im Park.", exampleEn: "The children run in the park." },
  { german: "fliegen", english: "to fly", partOfSpeech: "verb", category: "Movement", example: "Wir fliegen morgen nach Berlin.", exampleEn: "We fly to Berlin tomorrow." },
  { german: "schwimmen", english: "to swim", partOfSpeech: "verb", category: "Movement", example: "Im Sommer schwimme ich gern.", exampleEn: "In summer I like to swim." },
  { german: "springen", english: "to jump", partOfSpeech: "verb", category: "Movement", example: "Das Kind springt über die Pfütze.", exampleEn: "The child jumps over the puddle." },
  { german: "klettern", english: "to climb", partOfSpeech: "verb", category: "Movement", example: "Wir klettern auf den Berg.", exampleEn: "We climb the mountain." },
  { german: "steigen", english: "to climb / to rise", partOfSpeech: "verb", category: "Movement", example: "Die Preise steigen.", exampleEn: "The prices are rising." },
  { german: "aufstehen", english: "to get up / to stand up", partOfSpeech: "verb", category: "Movement", example: "Ich stehe jeden Tag um sechs Uhr auf.", exampleEn: "I get up at six o'clock every day." },
  { german: "sich setzen", english: "to sit down", partOfSpeech: "verb", category: "Movement", example: "Bitte setzen Sie sich.", exampleEn: "Please sit down." },
  { german: "sich hinlegen", english: "to lie down", partOfSpeech: "verb", category: "Movement", example: "Ich lege mich kurz hin.", exampleEn: "I'm lying down briefly." },
  { german: "sich bewegen", english: "to move", partOfSpeech: "verb", category: "Movement", example: "Du musst dich mehr bewegen.", exampleEn: "You need to move more." },
  { german: "sich drehen", english: "to turn / to rotate", partOfSpeech: "verb", category: "Movement", example: "Die Erde dreht sich um die Sonne.", exampleEn: "The Earth rotates around the Sun." },
  { german: "zurückkehren", english: "to return", partOfSpeech: "verb", category: "Movement", example: "Wir kehren morgen zurück.", exampleEn: "We return tomorrow." },
  { german: "einsteigen", english: "to get in / to board", partOfSpeech: "verb", category: "Movement", example: "Bitte einsteigen, der Zug fährt ab!", exampleEn: "Please board, the train is departing!" },
  { german: "aussteigen", english: "to get out / to exit", partOfSpeech: "verb", category: "Movement", example: "Wir steigen an der nächsten Haltestelle aus.", exampleEn: "We get off at the next stop." },
  { german: "umsteigen", english: "to transfer / to change (trains)", partOfSpeech: "verb", category: "Movement", example: "Du musst in München umsteigen.", exampleEn: "You have to transfer in Munich." },
  { german: "wandern", english: "to hike", partOfSpeech: "verb", category: "Movement", example: "Am Wochenende wandern wir in den Bergen.", exampleEn: "On the weekend we hike in the mountains." },
  { german: "reisen", english: "to travel", partOfSpeech: "verb", category: "Movement", example: "Ich reise gern nach Italien.", exampleEn: "I like to travel to Italy." },
  { german: "folgen", english: "to follow", partOfSpeech: "verb", category: "Movement", example: "Folgen Sie mir bitte.", exampleEn: "Please follow me." },
  { german: "schleichen", english: "to sneak / to creep", partOfSpeech: "verb", category: "Movement", example: "Die Katze schleicht durch den Garten.", exampleEn: "The cat sneaks through the garden." },
  { german: "eilen", english: "to hurry", partOfSpeech: "verb", category: "Movement", example: "Wir müssen uns eilen.", exampleEn: "We have to hurry." },
  { german: "sich beeilen", english: "to hurry up", partOfSpeech: "verb", category: "Movement", example: "Beeile dich, der Bus kommt!", exampleEn: "Hurry up, the bus is coming!" },
  { german: "ankommen", english: "to arrive", partOfSpeech: "verb", category: "Movement", example: "Der Zug kommt um zehn Uhr an.", exampleEn: "The train arrives at ten o'clock." },
  { german: "abfahren", english: "to depart", partOfSpeech: "verb", category: "Movement", example: "Der Bus fährt in fünf Minuten ab.", exampleEn: "The bus departs in five minutes." },
  { german: "überqueren", english: "to cross", partOfSpeech: "verb", category: "Movement", example: "Wir überqueren die Straße.", exampleEn: "We cross the street." },
  { german: "landen", english: "to land", partOfSpeech: "verb", category: "Movement", example: "Das Flugzeug landet bald.", exampleEn: "The airplane will land soon." },
  { german: "schieben", english: "to push / to shove", partOfSpeech: "verb", category: "Movement", example: "Er schiebt den Kinderwagen.", exampleEn: "He pushes the stroller." },
  { german: "werfen", english: "to throw", partOfSpeech: "verb", category: "Movement", example: "Er wirft den Ball.", exampleEn: "He throws the ball." },
  { german: "fangen", english: "to catch", partOfSpeech: "verb", category: "Movement", example: "Sie fängt den Ball.", exampleEn: "She catches the ball." },
  { german: "heben", english: "to lift / to raise", partOfSpeech: "verb", category: "Movement", example: "Er hebt die schwere Kiste.", exampleEn: "He lifts the heavy box." },
  { german: "sinken", english: "to sink / to drop", partOfSpeech: "verb", category: "Movement", example: "Die Temperatur sinkt.", exampleEn: "The temperature is dropping." },
  { german: "rutschen", english: "to slide / to slip", partOfSpeech: "verb", category: "Movement", example: "Das Kind rutscht auf der Rutsche.", exampleEn: "The child slides down the slide." },
  { german: "stolpern", english: "to stumble / to trip", partOfSpeech: "verb", category: "Movement", example: "Ich bin über einen Stein gestolpert.", exampleEn: "I stumbled over a stone." },
  { german: "treten", english: "to step / to kick", partOfSpeech: "verb", category: "Movement", example: "Er tritt auf die Bremse.", exampleEn: "He steps on the brake." },

  // ─── Daily Life ─────────────────────────────────────────────────
  { german: "aufwachen", english: "to wake up", partOfSpeech: "verb", category: "Daily Life", example: "Ich wache jeden Tag um sieben Uhr auf.", exampleEn: "I wake up at seven o'clock every day." },
  { german: "sich anziehen", english: "to get dressed", partOfSpeech: "verb", category: "Daily Life", example: "Ich ziehe mich schnell an.", exampleEn: "I get dressed quickly." },
  { german: "sich ausziehen", english: "to get undressed", partOfSpeech: "verb", category: "Daily Life", example: "Die Kinder ziehen sich vor dem Baden aus.", exampleEn: "The children get undressed before bathing." },
  { german: "sich waschen", english: "to wash oneself", partOfSpeech: "verb", category: "Daily Life", example: "Ich wasche mir die Hände.", exampleEn: "I wash my hands." },
  { german: "duschen", english: "to shower", partOfSpeech: "verb", category: "Daily Life", example: "Ich dusche morgens.", exampleEn: "I shower in the morning." },
  { german: "sich rasieren", english: "to shave", partOfSpeech: "verb", category: "Daily Life", example: "Er rasiert sich jeden Morgen.", exampleEn: "He shaves every morning." },
  { german: "sich kämmen", english: "to comb one's hair", partOfSpeech: "verb", category: "Daily Life", example: "Sie kämmt sich die Haare.", exampleEn: "She combs her hair." },
  { german: "putzen", english: "to clean", partOfSpeech: "verb", category: "Daily Life", example: "Ich putze die Wohnung am Samstag.", exampleEn: "I clean the apartment on Saturday." },
  { german: "sich die Zähne putzen", english: "to brush one's teeth", partOfSpeech: "verb", category: "Daily Life", example: "Ich putze mir zweimal am Tag die Zähne.", exampleEn: "I brush my teeth twice a day." },
  { german: "waschen", english: "to wash", partOfSpeech: "verb", category: "Daily Life", example: "Ich wasche die Wäsche.", exampleEn: "I wash the laundry." },
  { german: "bügeln", english: "to iron", partOfSpeech: "verb", category: "Daily Life", example: "Sie bügelt das Hemd.", exampleEn: "She irons the shirt." },
  { german: "aufräumen", english: "to tidy up", partOfSpeech: "verb", category: "Daily Life", example: "Räum dein Zimmer auf!", exampleEn: "Tidy up your room!" },
  { german: "abwaschen", english: "to wash dishes", partOfSpeech: "verb", category: "Daily Life", example: "Wer wäscht heute ab?", exampleEn: "Who does the dishes today?" },
  { german: "staubsaugen", english: "to vacuum", partOfSpeech: "verb", category: "Daily Life", example: "Ich staubsauge das Wohnzimmer.", exampleEn: "I vacuum the living room." },
  { german: "wohnen", english: "to live / to reside", partOfSpeech: "verb", category: "Daily Life", example: "Ich wohne in Berlin.", exampleEn: "I live in Berlin." },
  { german: "umziehen", english: "to move (house)", partOfSpeech: "verb", category: "Daily Life", example: "Wir ziehen nächsten Monat um.", exampleEn: "We're moving next month." },
  { german: "mieten", english: "to rent", partOfSpeech: "verb", category: "Daily Life", example: "Wir mieten eine kleine Wohnung.", exampleEn: "We rent a small apartment." },
  { german: "einladen", english: "to invite", partOfSpeech: "verb", category: "Daily Life", example: "Ich lade dich zum Essen ein.", exampleEn: "I invite you to dinner." },
  { german: "packen", english: "to pack", partOfSpeech: "verb", category: "Daily Life", example: "Ich packe meinen Koffer.", exampleEn: "I pack my suitcase." },
  { german: "auspacken", english: "to unpack", partOfSpeech: "verb", category: "Daily Life", example: "Ich packe die Einkäufe aus.", exampleEn: "I unpack the groceries." },
  { german: "öffnen", english: "to open", partOfSpeech: "verb", category: "Daily Life", example: "Öffne bitte das Fenster.", exampleEn: "Please open the window." },
  { german: "schließen", english: "to close", partOfSpeech: "verb", category: "Daily Life", example: "Schließ bitte die Tür.", exampleEn: "Please close the door." },
  { german: "aufmachen", english: "to open (informal)", partOfSpeech: "verb", category: "Daily Life", example: "Mach bitte die Tür auf.", exampleEn: "Please open the door." },
  { german: "zumachen", english: "to close (informal)", partOfSpeech: "verb", category: "Daily Life", example: "Mach das Fenster zu, es ist kalt.", exampleEn: "Close the window, it's cold." },
  { german: "anmachen", english: "to turn on", partOfSpeech: "verb", category: "Daily Life", example: "Mach bitte das Licht an.", exampleEn: "Please turn on the light." },
  { german: "ausmachen", english: "to turn off", partOfSpeech: "verb", category: "Daily Life", example: "Mach den Fernseher aus.", exampleEn: "Turn off the TV." },
  { german: "reparieren", english: "to repair / to fix", partOfSpeech: "verb", category: "Daily Life", example: "Er repariert das Fahrrad.", exampleEn: "He repairs the bicycle." },
  { german: "parken", english: "to park", partOfSpeech: "verb", category: "Daily Life", example: "Wo kann ich hier parken?", exampleEn: "Where can I park here?" },
  { german: "tanken", english: "to refuel", partOfSpeech: "verb", category: "Daily Life", example: "Wir müssen tanken.", exampleEn: "We need to refuel." },
  { german: "frühstücken", english: "to have breakfast", partOfSpeech: "verb", category: "Daily Life", example: "Ich frühstücke um acht Uhr.", exampleEn: "I have breakfast at eight." },
  { german: "sich schminken", english: "to put on makeup", partOfSpeech: "verb", category: "Daily Life", example: "Sie schminkt sich vor dem Spiegel.", exampleEn: "She puts on makeup in front of the mirror." },
  { german: "gießen", english: "to water / to pour", partOfSpeech: "verb", category: "Daily Life", example: "Ich gieße die Blumen.", exampleEn: "I water the flowers." },
  { german: "füttern", english: "to feed (animals)", partOfSpeech: "verb", category: "Daily Life", example: "Sie füttert die Katze.", exampleEn: "She feeds the cat." },
  { german: "ausruhen", english: "to rest", partOfSpeech: "verb", category: "Daily Life", example: "Ich muss mich ausruhen.", exampleEn: "I need to rest." },
  { german: "sich fertig machen", english: "to get ready", partOfSpeech: "verb", category: "Daily Life", example: "Mach dich fertig, wir gehen!", exampleEn: "Get ready, we're leaving!" },
  { german: "einschlafen", english: "to fall asleep", partOfSpeech: "verb", category: "Daily Life", example: "Das Kind schläft schnell ein.", exampleEn: "The child falls asleep quickly." },

  // ─── Work & Career ──────────────────────────────────────────────
  { german: "verdienen", english: "to earn", partOfSpeech: "verb", category: "Work", example: "Sie verdient gut.", exampleEn: "She earns well." },
  { german: "sich bewerben", english: "to apply (for a job)", partOfSpeech: "verb", category: "Work", example: "Ich bewerbe mich um die Stelle.", exampleEn: "I'm applying for the position." },
  { german: "kündigen", english: "to quit / to resign", partOfSpeech: "verb", category: "Work", example: "Er hat seine Stelle gekündigt.", exampleEn: "He quit his job." },
  { german: "einstellen", english: "to hire / to employ", partOfSpeech: "verb", category: "Work", example: "Die Firma stellt neue Mitarbeiter ein.", exampleEn: "The company hires new employees." },
  { german: "leiten", english: "to lead / to manage", partOfSpeech: "verb", category: "Work", example: "Sie leitet das Projekt.", exampleEn: "She manages the project." },
  { german: "entwickeln", english: "to develop", partOfSpeech: "verb", category: "Work", example: "Wir entwickeln eine neue App.", exampleEn: "We are developing a new app." },
  { german: "planen", english: "to plan", partOfSpeech: "verb", category: "Work", example: "Wir planen eine Konferenz.", exampleEn: "We are planning a conference." },
  { german: "organisieren", english: "to organize", partOfSpeech: "verb", category: "Work", example: "Sie organisiert das Treffen.", exampleEn: "She organizes the meeting." },
  { german: "überprüfen", english: "to check / to review", partOfSpeech: "verb", category: "Work", example: "Ich überprüfe die Zahlen.", exampleEn: "I'm checking the numbers." },
  { german: "unterschreiben", english: "to sign", partOfSpeech: "verb", category: "Work", example: "Bitte unterschreiben Sie hier.", exampleEn: "Please sign here." },
  { german: "drucken", english: "to print", partOfSpeech: "verb", category: "Work", example: "Ich drucke das Dokument aus.", exampleEn: "I'm printing the document." },
  { german: "kopieren", english: "to copy", partOfSpeech: "verb", category: "Work", example: "Kopiere bitte diese Datei.", exampleEn: "Please copy this file." },
  { german: "liefern", english: "to deliver / to supply", partOfSpeech: "verb", category: "Work", example: "Das Paket wird morgen geliefert.", exampleEn: "The package will be delivered tomorrow." },
  { german: "bestellen", english: "to order", partOfSpeech: "verb", category: "Work", example: "Ich bestelle das Material online.", exampleEn: "I order the material online." },
  { german: "bearbeiten", english: "to edit / to process", partOfSpeech: "verb", category: "Work", example: "Ich bearbeite das Dokument.", exampleEn: "I'm editing the document." },
  { german: "gründen", english: "to found / to establish", partOfSpeech: "verb", category: "Work", example: "Sie hat eine Firma gegründet.", exampleEn: "She founded a company." },
  { german: "herstellen", english: "to produce / to manufacture", partOfSpeech: "verb", category: "Work", example: "Die Fabrik stellt Autos her.", exampleEn: "The factory produces cars." },
  { german: "verwalten", english: "to manage / to administer", partOfSpeech: "verb", category: "Work", example: "Er verwaltet die Finanzen.", exampleEn: "He manages the finances." },
  { german: "sich verspäten", english: "to be late", partOfSpeech: "verb", category: "Work", example: "Ich habe mich verspätet.", exampleEn: "I was late." },
  { german: "teilnehmen", english: "to participate / to attend", partOfSpeech: "verb", category: "Work", example: "Ich nehme an dem Meeting teil.", exampleEn: "I'm attending the meeting." },
  { german: "vorstellen", english: "to introduce / to present", partOfSpeech: "verb", category: "Work", example: "Darf ich mich vorstellen?", exampleEn: "May I introduce myself?" },
  { german: "vereinbaren", english: "to arrange / to agree on", partOfSpeech: "verb", category: "Work", example: "Wir vereinbaren einen Termin.", exampleEn: "We arrange an appointment." },
  { german: "zusammenarbeiten", english: "to collaborate", partOfSpeech: "verb", category: "Work", example: "Wir arbeiten gut zusammen.", exampleEn: "We work well together." },
  { german: "verhandeln", english: "to negotiate", partOfSpeech: "verb", category: "Work", example: "Sie verhandeln über den Preis.", exampleEn: "They negotiate the price." },

  // ─── Thinking & Mental ──────────────────────────────────────────
  { german: "überlegen", english: "to consider / to think about", partOfSpeech: "verb", category: "Thinking", example: "Ich überlege mir das.", exampleEn: "I'll think about it." },
  { german: "nachdenken", english: "to think about / to reflect", partOfSpeech: "verb", category: "Thinking", example: "Ich denke über dein Angebot nach.", exampleEn: "I'm thinking about your offer." },
  { german: "erinnern", english: "to remind", partOfSpeech: "verb", category: "Thinking", example: "Erinnerst du mich bitte daran?", exampleEn: "Can you remind me of that?" },
  { german: "sich erinnern", english: "to remember", partOfSpeech: "verb", category: "Thinking", example: "Ich erinnere mich an den Tag.", exampleEn: "I remember that day." },
  { german: "vergessen", english: "to forget", partOfSpeech: "verb", category: "Thinking", example: "Ich habe meinen Schlüssel vergessen.", exampleEn: "I forgot my key." },
  { german: "entscheiden", english: "to decide", partOfSpeech: "verb", category: "Thinking", example: "Wir müssen uns schnell entscheiden.", exampleEn: "We must decide quickly." },
  { german: "sich entschließen", english: "to make up one's mind", partOfSpeech: "verb", category: "Thinking", example: "Er hat sich entschlossen, umzuziehen.", exampleEn: "He made up his mind to move." },
  { german: "vermuten", english: "to suspect / to assume", partOfSpeech: "verb", category: "Thinking", example: "Ich vermute, dass er recht hat.", exampleEn: "I suspect he's right." },
  { german: "bezweifeln", english: "to doubt", partOfSpeech: "verb", category: "Thinking", example: "Ich bezweifle, dass das stimmt.", exampleEn: "I doubt that's true." },
  { german: "sich vorstellen", english: "to imagine", partOfSpeech: "verb", category: "Thinking", example: "Stell dir das vor!", exampleEn: "Imagine that!" },
  { german: "planen", english: "to plan", partOfSpeech: "verb", category: "Thinking", example: "Ich plane meinen Tag.", exampleEn: "I plan my day." },
  { german: "sich konzentrieren", english: "to concentrate", partOfSpeech: "verb", category: "Thinking", example: "Ich kann mich nicht konzentrieren.", exampleEn: "I can't concentrate." },
  { german: "bemerken", english: "to notice", partOfSpeech: "verb", category: "Thinking", example: "Hast du das bemerkt?", exampleEn: "Did you notice that?" },
  { german: "erkennen", english: "to recognize / to realize", partOfSpeech: "verb", category: "Thinking", example: "Ich habe dich nicht erkannt.", exampleEn: "I didn't recognize you." },
  { german: "vergleichen", english: "to compare", partOfSpeech: "verb", category: "Thinking", example: "Vergleich die zwei Angebote.", exampleEn: "Compare the two offers." },
  { german: "annehmen", english: "to assume / to accept", partOfSpeech: "verb", category: "Thinking", example: "Ich nehme an, du hast recht.", exampleEn: "I assume you're right." },
  { german: "sich wundern", english: "to wonder / to be surprised", partOfSpeech: "verb", category: "Thinking", example: "Ich wundere mich über sein Verhalten.", exampleEn: "I wonder about his behavior." },
  { german: "rechnen", english: "to calculate / to expect", partOfSpeech: "verb", category: "Thinking", example: "Ich rechne mit schlechtem Wetter.", exampleEn: "I expect bad weather." },
  { german: "beurteilen", english: "to judge / to assess", partOfSpeech: "verb", category: "Thinking", example: "Man sollte niemanden vorschnell beurteilen.", exampleEn: "One shouldn't judge anyone hastily." },
  { german: "sich irren", english: "to be mistaken", partOfSpeech: "verb", category: "Thinking", example: "Ich habe mich geirrt.", exampleEn: "I was mistaken." },
  { german: "analysieren", english: "to analyze", partOfSpeech: "verb", category: "Thinking", example: "Wir analysieren die Daten.", exampleEn: "We analyze the data." },
  { german: "sich merken", english: "to remember / to memorize", partOfSpeech: "verb", category: "Thinking", example: "Ich kann mir die Nummer nicht merken.", exampleEn: "I can't memorize the number." },
  { german: "einschätzen", english: "to assess / to estimate", partOfSpeech: "verb", category: "Thinking", example: "Ich kann die Lage nicht einschätzen.", exampleEn: "I can't assess the situation." },

  // ─── Emotions ───────────────────────────────────────────────────
  { german: "sich freuen", english: "to be happy / to look forward to", partOfSpeech: "verb", category: "Emotions", example: "Ich freue mich auf den Urlaub.", exampleEn: "I'm looking forward to the vacation." },
  { german: "lieben", english: "to love", partOfSpeech: "verb", category: "Emotions", example: "Ich liebe meine Familie.", exampleEn: "I love my family." },
  { german: "hassen", english: "to hate", partOfSpeech: "verb", category: "Emotions", example: "Er hasst Ungerechtigkeit.", exampleEn: "He hates injustice." },
  { german: "sich ärgern", english: "to be annoyed", partOfSpeech: "verb", category: "Emotions", example: "Ich ärgere mich über den Stau.", exampleEn: "I'm annoyed by the traffic jam." },
  { german: "sich fürchten", english: "to be afraid", partOfSpeech: "verb", category: "Emotions", example: "Sie fürchtet sich vor Spinnen.", exampleEn: "She is afraid of spiders." },
  { german: "hoffen", english: "to hope", partOfSpeech: "verb", category: "Emotions", example: "Ich hoffe, dass alles gut wird.", exampleEn: "I hope everything will be fine." },
  { german: "wünschen", english: "to wish", partOfSpeech: "verb", category: "Emotions", example: "Ich wünsche dir alles Gute.", exampleEn: "I wish you all the best." },
  { german: "vermissen", english: "to miss (someone)", partOfSpeech: "verb", category: "Emotions", example: "Ich vermisse dich.", exampleEn: "I miss you." },
  { german: "sich sorgen", english: "to worry", partOfSpeech: "verb", category: "Emotions", example: "Ich sorge mich um meine Eltern.", exampleEn: "I worry about my parents." },
  { german: "weinen", english: "to cry", partOfSpeech: "verb", category: "Emotions", example: "Das Kind weint.", exampleEn: "The child is crying." },
  { german: "lachen", english: "to laugh", partOfSpeech: "verb", category: "Emotions", example: "Wir lachen viel zusammen.", exampleEn: "We laugh a lot together." },
  { german: "lächeln", english: "to smile", partOfSpeech: "verb", category: "Emotions", example: "Sie lächelt freundlich.", exampleEn: "She smiles kindly." },
  { german: "sich schämen", english: "to be ashamed", partOfSpeech: "verb", category: "Emotions", example: "Er schämt sich für sein Verhalten.", exampleEn: "He is ashamed of his behavior." },
  { german: "staunen", english: "to be amazed", partOfSpeech: "verb", category: "Emotions", example: "Die Kinder staunen über den Zaubertrick.", exampleEn: "The children are amazed by the magic trick." },
  { german: "sich langweilen", english: "to be bored", partOfSpeech: "verb", category: "Emotions", example: "Mir ist langweilig, ich langweile mich.", exampleEn: "I'm bored." },
  { german: "genießen", english: "to enjoy", partOfSpeech: "verb", category: "Emotions", example: "Ich genieße das schöne Wetter.", exampleEn: "I enjoy the nice weather." },
  { german: "leiden", english: "to suffer", partOfSpeech: "verb", category: "Emotions", example: "Er leidet unter Kopfschmerzen.", exampleEn: "He suffers from headaches." },
  { german: "überraschen", english: "to surprise", partOfSpeech: "verb", category: "Emotions", example: "Die Nachricht hat mich überrascht.", exampleEn: "The news surprised me." },
  { german: "erschrecken", english: "to frighten / to be startled", partOfSpeech: "verb", category: "Emotions", example: "Du hast mich erschreckt!", exampleEn: "You startled me!" },
  { german: "sich entspannen", english: "to relax", partOfSpeech: "verb", category: "Emotions", example: "Am Wochenende entspanne ich mich.", exampleEn: "On the weekend I relax." },
  { german: "bedauern", english: "to regret", partOfSpeech: "verb", category: "Emotions", example: "Ich bedauere meine Entscheidung.", exampleEn: "I regret my decision." },
  { german: "sich aufregen", english: "to get upset", partOfSpeech: "verb", category: "Emotions", example: "Reg dich nicht auf!", exampleEn: "Don't get upset!" },
  { german: "bewundern", english: "to admire", partOfSpeech: "verb", category: "Emotions", example: "Ich bewundere deine Geduld.", exampleEn: "I admire your patience." },
  { german: "sich verlieben", english: "to fall in love", partOfSpeech: "verb", category: "Emotions", example: "Sie hat sich in ihn verliebt.", exampleEn: "She fell in love with him." },
  { german: "beneiden", english: "to envy", partOfSpeech: "verb", category: "Emotions", example: "Ich beneide dich um dein Talent.", exampleEn: "I envy your talent." },
  { german: "bereuen", english: "to regret / to repent", partOfSpeech: "verb", category: "Emotions", example: "Er bereut seine Worte.", exampleEn: "He regrets his words." },
  { german: "sich beruhigen", english: "to calm down", partOfSpeech: "verb", category: "Emotions", example: "Beruhige dich, es ist alles gut.", exampleEn: "Calm down, everything is fine." },
  { german: "sich ekeln", english: "to be disgusted", partOfSpeech: "verb", category: "Emotions", example: "Ich ekle mich vor Spinnen.", exampleEn: "I'm disgusted by spiders." },
  { german: "stören", english: "to disturb / to bother", partOfSpeech: "verb", category: "Emotions", example: "Stört es dich, wenn ich rauche?", exampleEn: "Does it bother you if I smoke?" },
  { german: "sich freuen über", english: "to be happy about", partOfSpeech: "verb", category: "Emotions", example: "Ich freue mich über das Geschenk.", exampleEn: "I'm happy about the gift." },

  // ─── Social ─────────────────────────────────────────────────────
  { german: "sich treffen", english: "to meet up", partOfSpeech: "verb", category: "Social", example: "Wir treffen uns um drei.", exampleEn: "We meet at three." },
  { german: "besuchen", english: "to visit", partOfSpeech: "verb", category: "Social", example: "Ich besuche meine Großeltern.", exampleEn: "I visit my grandparents." },
  { german: "heiraten", english: "to marry", partOfSpeech: "verb", category: "Social", example: "Sie heiraten im Juni.", exampleEn: "They get married in June." },
  { german: "sich scheiden lassen", english: "to get divorced", partOfSpeech: "verb", category: "Social", example: "Sie lassen sich scheiden.", exampleEn: "They are getting divorced." },
  { german: "sich verabreden", english: "to make a date / to arrange to meet", partOfSpeech: "verb", category: "Social", example: "Wir verabreden uns für Freitag.", exampleEn: "We arrange to meet on Friday." },
  { german: "feiern", english: "to celebrate", partOfSpeech: "verb", category: "Social", example: "Wir feiern seinen Geburtstag.", exampleEn: "We celebrate his birthday." },
  { german: "schenken", english: "to give (as a gift)", partOfSpeech: "verb", category: "Social", example: "Was schenkst du ihr?", exampleEn: "What are you giving her?" },
  { german: "teilen", english: "to share / to divide", partOfSpeech: "verb", category: "Social", example: "Wir teilen uns die Pizza.", exampleEn: "We share the pizza." },
  { german: "sich streiten", english: "to argue / to fight", partOfSpeech: "verb", category: "Social", example: "Die Kinder streiten sich oft.", exampleEn: "The children argue often." },
  { german: "sich vertragen", english: "to get along / to make up", partOfSpeech: "verb", category: "Social", example: "Die Geschwister vertragen sich wieder.", exampleEn: "The siblings have made up again." },
  { german: "sich kümmern", english: "to take care of", partOfSpeech: "verb", category: "Social", example: "Ich kümmere mich um die Kinder.", exampleEn: "I take care of the children." },
  { german: "unterstützen", english: "to support", partOfSpeech: "verb", category: "Social", example: "Meine Familie unterstützt mich.", exampleEn: "My family supports me." },
  { german: "vertrauen", english: "to trust", partOfSpeech: "verb", category: "Social", example: "Ich vertraue dir.", exampleEn: "I trust you." },
  { german: "respektieren", english: "to respect", partOfSpeech: "verb", category: "Social", example: "Wir respektieren deine Meinung.", exampleEn: "We respect your opinion." },
  { german: "sich küssen", english: "to kiss", partOfSpeech: "verb", category: "Social", example: "Sie küssen sich zum Abschied.", exampleEn: "They kiss goodbye." },
  { german: "umarmen", english: "to hug", partOfSpeech: "verb", category: "Social", example: "Sie umarmt ihre Freundin.", exampleEn: "She hugs her friend." },
  { german: "sich trennen", english: "to separate / to break up", partOfSpeech: "verb", category: "Social", example: "Sie haben sich getrennt.", exampleEn: "They broke up." },
  { german: "sich versöhnen", english: "to reconcile", partOfSpeech: "verb", category: "Social", example: "Sie versöhnen sich nach dem Streit.", exampleEn: "They reconcile after the argument." },
  { german: "kennenlernen", english: "to get to know / to meet", partOfSpeech: "verb", category: "Social", example: "Wo habt ihr euch kennengelernt?", exampleEn: "Where did you meet?" },
  { german: "sich anfreunden", english: "to become friends", partOfSpeech: "verb", category: "Social", example: "Sie hat sich schnell angefreundet.", exampleEn: "She made friends quickly." },
  { german: "einladen", english: "to invite", partOfSpeech: "verb", category: "Social", example: "Ich lade alle Freunde ein.", exampleEn: "I invite all friends." },
  { german: "absagen", english: "to cancel", partOfSpeech: "verb", category: "Social", example: "Ich muss das Treffen absagen.", exampleEn: "I have to cancel the meeting." },
  { german: "zusagen", english: "to accept (an invitation)", partOfSpeech: "verb", category: "Social", example: "Alle Gäste haben zugesagt.", exampleEn: "All guests have accepted." },
  { german: "sich benehmen", english: "to behave", partOfSpeech: "verb", category: "Social", example: "Benimm dich!", exampleEn: "Behave yourself!" },

  // ─── Cooking & Food ─────────────────────────────────────────────
  { german: "kochen", english: "to cook", partOfSpeech: "verb", category: "Cooking", example: "Ich koche heute Abend.", exampleEn: "I'm cooking tonight." },
  { german: "backen", english: "to bake", partOfSpeech: "verb", category: "Cooking", example: "Sie backt einen Kuchen.", exampleEn: "She bakes a cake." },
  { german: "braten", english: "to fry / to roast", partOfSpeech: "verb", category: "Cooking", example: "Ich brate das Fleisch.", exampleEn: "I fry the meat." },
  { german: "schneiden", english: "to cut", partOfSpeech: "verb", category: "Cooking", example: "Schneide bitte das Brot.", exampleEn: "Please cut the bread." },
  { german: "rühren", english: "to stir", partOfSpeech: "verb", category: "Cooking", example: "Rühr die Soße um.", exampleEn: "Stir the sauce." },
  { german: "schmecken", english: "to taste", partOfSpeech: "verb", category: "Cooking", example: "Die Suppe schmeckt gut.", exampleEn: "The soup tastes good." },
  { german: "riechen", english: "to smell", partOfSpeech: "verb", category: "Cooking", example: "Das Essen riecht lecker.", exampleEn: "The food smells delicious." },
  { german: "würzen", english: "to season", partOfSpeech: "verb", category: "Cooking", example: "Würze die Suppe mit Salz.", exampleEn: "Season the soup with salt." },
  { german: "abschmecken", english: "to taste / to adjust seasoning", partOfSpeech: "verb", category: "Cooking", example: "Schmeck die Soße noch mal ab.", exampleEn: "Taste the sauce once more." },
  { german: "einfrieren", english: "to freeze", partOfSpeech: "verb", category: "Cooking", example: "Ich friere das Fleisch ein.", exampleEn: "I freeze the meat." },
  { german: "auftauen", english: "to thaw / to defrost", partOfSpeech: "verb", category: "Cooking", example: "Das Hähnchen muss auftauen.", exampleEn: "The chicken needs to thaw." },
  { german: "aufwärmen", english: "to heat up / to reheat", partOfSpeech: "verb", category: "Cooking", example: "Ich wärme das Essen auf.", exampleEn: "I'm reheating the food." },
  { german: "mischen", english: "to mix", partOfSpeech: "verb", category: "Cooking", example: "Mische die Zutaten zusammen.", exampleEn: "Mix the ingredients together." },
  { german: "schälen", english: "to peel", partOfSpeech: "verb", category: "Cooking", example: "Schäl die Kartoffeln.", exampleEn: "Peel the potatoes." },
  { german: "abspülen", english: "to rinse", partOfSpeech: "verb", category: "Cooking", example: "Spül bitte das Gemüse ab.", exampleEn: "Please rinse the vegetables." },
  { german: "servieren", english: "to serve", partOfSpeech: "verb", category: "Cooking", example: "Das Essen wird jetzt serviert.", exampleEn: "The food is being served now." },
  { german: "probieren", english: "to try / to taste", partOfSpeech: "verb", category: "Cooking", example: "Probier mal die Suppe!", exampleEn: "Try the soup!" },
  { german: "grillen", english: "to grill / to barbecue", partOfSpeech: "verb", category: "Cooking", example: "Wir grillen im Garten.", exampleEn: "We barbecue in the garden." },
  { german: "decken", english: "to set (the table)", partOfSpeech: "verb", category: "Cooking", example: "Kannst du den Tisch decken?", exampleEn: "Can you set the table?" },

  // ─── Shopping ───────────────────────────────────────────────────
  { german: "einkaufen", english: "to shop / to buy", partOfSpeech: "verb", category: "Shopping", example: "Ich kaufe im Supermarkt ein.", exampleEn: "I shop at the supermarket." },
  { german: "verkaufen", english: "to sell", partOfSpeech: "verb", category: "Shopping", example: "Er verkauft sein altes Auto.", exampleEn: "He sells his old car." },
  { german: "bezahlen", english: "to pay", partOfSpeech: "verb", category: "Shopping", example: "Ich bezahle mit Karte.", exampleEn: "I pay by card." },
  { german: "kosten", english: "to cost", partOfSpeech: "verb", category: "Shopping", example: "Wie viel kostet das?", exampleEn: "How much does that cost?" },
  { german: "sparen", english: "to save (money)", partOfSpeech: "verb", category: "Shopping", example: "Ich spare für eine Reise.", exampleEn: "I'm saving for a trip." },
  { german: "ausgeben", english: "to spend (money)", partOfSpeech: "verb", category: "Shopping", example: "Sie gibt viel Geld für Kleidung aus.", exampleEn: "She spends a lot of money on clothes." },
  { german: "umtauschen", english: "to exchange / to return", partOfSpeech: "verb", category: "Shopping", example: "Kann ich das Hemd umtauschen?", exampleEn: "Can I exchange the shirt?" },
  { german: "anprobieren", english: "to try on", partOfSpeech: "verb", category: "Shopping", example: "Ich möchte die Hose anprobieren.", exampleEn: "I'd like to try on the pants." },
  { german: "vergleichen", english: "to compare", partOfSpeech: "verb", category: "Shopping", example: "Ich vergleiche die Preise.", exampleEn: "I compare the prices." },
  { german: "leihen", english: "to lend / to borrow", partOfSpeech: "verb", category: "Shopping", example: "Kannst du mir zehn Euro leihen?", exampleEn: "Can you lend me ten euros?" },
  { german: "zurückgeben", english: "to return / to give back", partOfSpeech: "verb", category: "Shopping", example: "Ich gebe das Buch morgen zurück.", exampleEn: "I'll return the book tomorrow." },
  { german: "sich leisten", english: "to afford", partOfSpeech: "verb", category: "Shopping", example: "Ich kann mir das nicht leisten.", exampleEn: "I can't afford that." },
  { german: "rabattieren", english: "to discount", partOfSpeech: "verb", category: "Shopping", example: "Das Geschäft rabattiert viele Produkte.", exampleEn: "The store discounts many products." },

  // ─── Health ─────────────────────────────────────────────────────
  { german: "sich fühlen", english: "to feel", partOfSpeech: "verb", category: "Health", example: "Ich fühle mich nicht gut.", exampleEn: "I don't feel well." },
  { german: "husten", english: "to cough", partOfSpeech: "verb", category: "Health", example: "Er hustet seit drei Tagen.", exampleEn: "He has been coughing for three days." },
  { german: "niesen", english: "to sneeze", partOfSpeech: "verb", category: "Health", example: "Ich muss ständig niesen.", exampleEn: "I keep sneezing." },
  { german: "sich erkälten", english: "to catch a cold", partOfSpeech: "verb", category: "Health", example: "Ich habe mich erkältet.", exampleEn: "I caught a cold." },
  { german: "heilen", english: "to heal / to cure", partOfSpeech: "verb", category: "Health", example: "Die Wunde heilt schnell.", exampleEn: "The wound heals quickly." },
  { german: "sich verletzen", english: "to injure oneself", partOfSpeech: "verb", category: "Health", example: "Er hat sich am Knie verletzt.", exampleEn: "He injured his knee." },
  { german: "bluten", english: "to bleed", partOfSpeech: "verb", category: "Health", example: "Die Wunde blutet.", exampleEn: "The wound is bleeding." },
  { german: "atmen", english: "to breathe", partOfSpeech: "verb", category: "Health", example: "Atme tief ein und aus.", exampleEn: "Breathe in and out deeply." },
  { german: "untersuchen", english: "to examine", partOfSpeech: "verb", category: "Health", example: "Der Arzt untersucht den Patienten.", exampleEn: "The doctor examines the patient." },
  { german: "verschreiben", english: "to prescribe", partOfSpeech: "verb", category: "Health", example: "Der Arzt verschreibt ein Medikament.", exampleEn: "The doctor prescribes a medication." },
  { german: "operieren", english: "to operate (surgery)", partOfSpeech: "verb", category: "Health", example: "Der Chirurg operiert morgen.", exampleEn: "The surgeon operates tomorrow." },
  { german: "sich erholen", english: "to recover", partOfSpeech: "verb", category: "Health", example: "Sie erholt sich von der Grippe.", exampleEn: "She is recovering from the flu." },
  { german: "trainieren", english: "to train / to exercise", partOfSpeech: "verb", category: "Health", example: "Ich trainiere dreimal pro Woche.", exampleEn: "I exercise three times a week." },
  { german: "sich dehnen", english: "to stretch", partOfSpeech: "verb", category: "Health", example: "Dehne dich vor dem Sport.", exampleEn: "Stretch before exercising." },
  { german: "abnehmen", english: "to lose weight", partOfSpeech: "verb", category: "Health", example: "Ich möchte fünf Kilo abnehmen.", exampleEn: "I want to lose five kilos." },
  { german: "zunehmen", english: "to gain weight", partOfSpeech: "verb", category: "Health", example: "Im Winter nehme ich immer zu.", exampleEn: "In winter I always gain weight." },
  { german: "sich anstecken", english: "to catch (an illness)", partOfSpeech: "verb", category: "Health", example: "Ich habe mich bei meinem Kollegen angesteckt.", exampleEn: "I caught it from my colleague." },
  { german: "impfen", english: "to vaccinate", partOfSpeech: "verb", category: "Health", example: "Das Kind wird heute geimpft.", exampleEn: "The child is being vaccinated today." },
  { german: "sich ausruhen", english: "to rest / to relax", partOfSpeech: "verb", category: "Health", example: "Du musst dich ausruhen.", exampleEn: "You need to rest." },
  { german: "verbinden", english: "to bandage / to connect", partOfSpeech: "verb", category: "Health", example: "Die Krankenschwester verbindet die Wunde.", exampleEn: "The nurse bandages the wound." },
  { german: "schwitzen", english: "to sweat", partOfSpeech: "verb", category: "Health", example: "Ich schwitze beim Sport.", exampleEn: "I sweat while exercising." },
  { german: "sich übergeben", english: "to vomit", partOfSpeech: "verb", category: "Health", example: "Ihm ist schlecht und er übergibt sich.", exampleEn: "He feels sick and is vomiting." },

  // ─── Nature & Weather ───────────────────────────────────────────
  { german: "regnen", english: "to rain", partOfSpeech: "verb", category: "Nature", example: "Es regnet den ganzen Tag.", exampleEn: "It rains all day." },
  { german: "schneien", english: "to snow", partOfSpeech: "verb", category: "Nature", example: "Es schneit seit gestern.", exampleEn: "It has been snowing since yesterday." },
  { german: "wachsen", english: "to grow", partOfSpeech: "verb", category: "Nature", example: "Die Blumen wachsen schnell.", exampleEn: "The flowers grow quickly." },
  { german: "blühen", english: "to bloom / to flower", partOfSpeech: "verb", category: "Nature", example: "Die Rosen blühen im Sommer.", exampleEn: "The roses bloom in summer." },
  { german: "pflanzen", english: "to plant", partOfSpeech: "verb", category: "Nature", example: "Wir pflanzen einen Baum.", exampleEn: "We plant a tree." },
  { german: "ernten", english: "to harvest", partOfSpeech: "verb", category: "Nature", example: "Die Bauern ernten das Getreide.", exampleEn: "The farmers harvest the grain." },
  { german: "frieren", english: "to freeze / to be cold", partOfSpeech: "verb", category: "Nature", example: "Mir friert, es ist so kalt.", exampleEn: "I'm freezing, it's so cold." },
  { german: "tauen", english: "to thaw / to melt", partOfSpeech: "verb", category: "Nature", example: "Der Schnee taut im Frühling.", exampleEn: "The snow melts in spring." },
  { german: "stürmen", english: "to storm", partOfSpeech: "verb", category: "Nature", example: "Es stürmt draußen.", exampleEn: "It's storming outside." },
  { german: "donnern", english: "to thunder", partOfSpeech: "verb", category: "Nature", example: "Es donnert in der Ferne.", exampleEn: "It's thundering in the distance." },
  { german: "blitzen", english: "to flash (lightning)", partOfSpeech: "verb", category: "Nature", example: "Es blitzt am Himmel.", exampleEn: "Lightning flashes in the sky." },
  { german: "wehen", english: "to blow (wind)", partOfSpeech: "verb", category: "Nature", example: "Der Wind weht stark.", exampleEn: "The wind blows strongly." },
  { german: "trocknen", english: "to dry", partOfSpeech: "verb", category: "Nature", example: "Die Wäsche trocknet in der Sonne.", exampleEn: "The laundry dries in the sun." },
  { german: "schmelzen", english: "to melt", partOfSpeech: "verb", category: "Nature", example: "Das Eis schmilzt in der Sonne.", exampleEn: "The ice melts in the sun." },
  { german: "fließen", english: "to flow", partOfSpeech: "verb", category: "Nature", example: "Der Fluss fließt ins Meer.", exampleEn: "The river flows into the sea." },
  { german: "untergehen", english: "to set (sun) / to sink", partOfSpeech: "verb", category: "Nature", example: "Die Sonne geht unter.", exampleEn: "The sun is setting." },
  { german: "aufgehen", english: "to rise (sun)", partOfSpeech: "verb", category: "Nature", example: "Die Sonne geht im Osten auf.", exampleEn: "The sun rises in the east." },
  { german: "leuchten", english: "to glow / to shine", partOfSpeech: "verb", category: "Nature", example: "Die Sterne leuchten am Himmel.", exampleEn: "The stars glow in the sky." },
  { german: "brennen", english: "to burn", partOfSpeech: "verb", category: "Nature", example: "Das Feuer brennt im Kamin.", exampleEn: "The fire burns in the fireplace." },

  // ─── Technology ─────────────────────────────────────────────────
  { german: "herunterladen", english: "to download", partOfSpeech: "verb", category: "Technology", example: "Ich lade die App herunter.", exampleEn: "I'm downloading the app." },
  { german: "hochladen", english: "to upload", partOfSpeech: "verb", category: "Technology", example: "Ich lade das Foto hoch.", exampleEn: "I'm uploading the photo." },
  { german: "speichern", english: "to save (data)", partOfSpeech: "verb", category: "Technology", example: "Speichere die Datei regelmäßig.", exampleEn: "Save the file regularly." },
  { german: "löschen", english: "to delete", partOfSpeech: "verb", category: "Technology", example: "Lösche die alte Datei.", exampleEn: "Delete the old file." },
  { german: "klicken", english: "to click", partOfSpeech: "verb", category: "Technology", example: "Klicke auf den Link.", exampleEn: "Click on the link." },
  { german: "tippen", english: "to type", partOfSpeech: "verb", category: "Technology", example: "Sie tippt schnell.", exampleEn: "She types quickly." },
  { german: "installieren", english: "to install", partOfSpeech: "verb", category: "Technology", example: "Ich installiere ein neues Programm.", exampleEn: "I'm installing a new program." },
  { german: "aktualisieren", english: "to update", partOfSpeech: "verb", category: "Technology", example: "Aktualisiere dein Betriebssystem.", exampleEn: "Update your operating system." },
  { german: "einloggen", english: "to log in", partOfSpeech: "verb", category: "Technology", example: "Logge dich in dein Konto ein.", exampleEn: "Log in to your account." },
  { german: "ausloggen", english: "to log out", partOfSpeech: "verb", category: "Technology", example: "Logge dich nach der Arbeit aus.", exampleEn: "Log out after work." },
  { german: "programmieren", english: "to program", partOfSpeech: "verb", category: "Technology", example: "Er programmiert eine Website.", exampleEn: "He's programming a website." },
  { german: "scannen", english: "to scan", partOfSpeech: "verb", category: "Technology", example: "Ich scanne das Dokument.", exampleEn: "I scan the document." },
  { german: "verbinden", english: "to connect", partOfSpeech: "verb", category: "Technology", example: "Verbinde das Gerät mit dem WLAN.", exampleEn: "Connect the device to the WiFi." },
  { german: "laden", english: "to charge / to load", partOfSpeech: "verb", category: "Technology", example: "Ich muss mein Handy laden.", exampleEn: "I need to charge my phone." },
  { german: "googeln", english: "to google", partOfSpeech: "verb", category: "Technology", example: "Ich google das schnell.", exampleEn: "I'll google that quickly." },
  { german: "streamen", english: "to stream", partOfSpeech: "verb", category: "Technology", example: "Wir streamen einen Film.", exampleEn: "We're streaming a movie." },
  { german: "chatten", english: "to chat (online)", partOfSpeech: "verb", category: "Technology", example: "Wir chatten über WhatsApp.", exampleEn: "We chat on WhatsApp." },
  { german: "posten", english: "to post (online)", partOfSpeech: "verb", category: "Technology", example: "Sie postet ein Foto auf Instagram.", exampleEn: "She posts a photo on Instagram." },
  { german: "teilen", english: "to share (online)", partOfSpeech: "verb", category: "Technology", example: "Er teilt den Artikel auf Facebook.", exampleEn: "He shares the article on Facebook." },
  { german: "ausschalten", english: "to turn off / to switch off", partOfSpeech: "verb", category: "Technology", example: "Schalte den Computer aus.", exampleEn: "Turn off the computer." },
  { german: "einschalten", english: "to turn on / to switch on", partOfSpeech: "verb", category: "Technology", example: "Schalte den Fernseher ein.", exampleEn: "Turn on the TV." },
  { german: "abstürzen", english: "to crash (computer)", partOfSpeech: "verb", category: "Technology", example: "Mein Computer ist abgestürzt.", exampleEn: "My computer crashed." },
  { german: "sichern", english: "to back up / to secure", partOfSpeech: "verb", category: "Technology", example: "Sichere deine Daten regelmäßig.", exampleEn: "Back up your data regularly." },

  // ─── Learning & Education ───────────────────────────────────────
  { german: "studieren", english: "to study (at university)", partOfSpeech: "verb", category: "Learning", example: "Ich studiere Medizin.", exampleEn: "I study medicine." },
  { german: "üben", english: "to practice", partOfSpeech: "verb", category: "Learning", example: "Ich übe jeden Tag Klavier.", exampleEn: "I practice piano every day." },
  { german: "unterrichten", english: "to teach", partOfSpeech: "verb", category: "Learning", example: "Sie unterrichtet Deutsch.", exampleEn: "She teaches German." },
  { german: "prüfen", english: "to test / to examine", partOfSpeech: "verb", category: "Learning", example: "Der Lehrer prüft die Schüler.", exampleEn: "The teacher tests the students." },
  { german: "bestehen", english: "to pass (an exam)", partOfSpeech: "verb", category: "Learning", example: "Ich habe die Prüfung bestanden.", exampleEn: "I passed the exam." },
  { german: "durchfallen", english: "to fail (an exam)", partOfSpeech: "verb", category: "Learning", example: "Er ist durch die Prüfung durchgefallen.", exampleEn: "He failed the exam." },
  { german: "wiederholen", english: "to repeat / to review", partOfSpeech: "verb", category: "Learning", example: "Wiederholen Sie bitte den Satz.", exampleEn: "Please repeat the sentence." },
  { german: "buchstabieren", english: "to spell", partOfSpeech: "verb", category: "Learning", example: "Können Sie Ihren Namen buchstabieren?", exampleEn: "Can you spell your name?" },
  { german: "aussprechen", english: "to pronounce", partOfSpeech: "verb", category: "Learning", example: "Wie spricht man dieses Wort aus?", exampleEn: "How do you pronounce this word?" },
  { german: "korrigieren", english: "to correct", partOfSpeech: "verb", category: "Learning", example: "Der Lehrer korrigiert die Hausaufgaben.", exampleEn: "The teacher corrects the homework." },
  { german: "sich vorbereiten", english: "to prepare", partOfSpeech: "verb", category: "Learning", example: "Ich bereite mich auf die Prüfung vor.", exampleEn: "I'm preparing for the exam." },
  { german: "recherchieren", english: "to research", partOfSpeech: "verb", category: "Learning", example: "Ich recherchiere für meine Arbeit.", exampleEn: "I'm researching for my paper." },
  { german: "sich anmelden", english: "to register / to sign up", partOfSpeech: "verb", category: "Learning", example: "Ich melde mich für den Kurs an.", exampleEn: "I'm signing up for the course." },
  { german: "sich abmelden", english: "to deregister / to sign out", partOfSpeech: "verb", category: "Learning", example: "Ich melde mich vom Kurs ab.", exampleEn: "I'm deregistering from the course." },
  { german: "nachschlagen", english: "to look up", partOfSpeech: "verb", category: "Learning", example: "Ich schlage das Wort im Wörterbuch nach.", exampleEn: "I look up the word in the dictionary." },
  { german: "auswendig lernen", english: "to memorize / to learn by heart", partOfSpeech: "verb", category: "Learning", example: "Ich lerne das Gedicht auswendig.", exampleEn: "I'm memorizing the poem." },
  { german: "zusammenfassen", english: "to summarize", partOfSpeech: "verb", category: "Learning", example: "Fasse den Text zusammen.", exampleEn: "Summarize the text." },
  { german: "markieren", english: "to highlight / to mark", partOfSpeech: "verb", category: "Learning", example: "Markiere die wichtigen Stellen.", exampleEn: "Highlight the important parts." },
  { german: "abgeben", english: "to hand in / to submit", partOfSpeech: "verb", category: "Learning", example: "Gib die Hausaufgabe bis morgen ab.", exampleEn: "Hand in the homework by tomorrow." },
  { german: "notieren", english: "to note down", partOfSpeech: "verb", category: "Learning", example: "Notiere dir die Telefonnummer.", exampleEn: "Note down the phone number." },

  // ─── Perception & Senses ────────────────────────────────────────
  { german: "hören", english: "to hear", partOfSpeech: "verb", category: "Perception", example: "Ich höre Musik.", exampleEn: "I listen to music." },
  { german: "zuhören", english: "to listen", partOfSpeech: "verb", category: "Perception", example: "Hör mir bitte zu!", exampleEn: "Please listen to me!" },
  { german: "fühlen", english: "to feel / to touch", partOfSpeech: "verb", category: "Perception", example: "Fühl mal, wie weich das ist.", exampleEn: "Feel how soft this is." },
  { german: "beobachten", english: "to observe / to watch", partOfSpeech: "verb", category: "Perception", example: "Ich beobachte die Vögel.", exampleEn: "I observe the birds." },
  { german: "berühren", english: "to touch", partOfSpeech: "verb", category: "Perception", example: "Bitte nicht berühren!", exampleEn: "Please don't touch!" },
  { german: "merken", english: "to notice / to sense", partOfSpeech: "verb", category: "Perception", example: "Ich habe nichts gemerkt.", exampleEn: "I didn't notice anything." },
  { german: "spüren", english: "to sense / to feel", partOfSpeech: "verb", category: "Perception", example: "Ich spüre den Wind.", exampleEn: "I feel the wind." },
  { german: "blicken", english: "to glance / to look", partOfSpeech: "verb", category: "Perception", example: "Er blickt aus dem Fenster.", exampleEn: "He looks out the window." },
  { german: "erblicken", english: "to spot / to catch sight of", partOfSpeech: "verb", category: "Perception", example: "Sie erblickt ihren Freund in der Menge.", exampleEn: "She spots her friend in the crowd." },
  { german: "lauschen", english: "to listen intently / to eavesdrop", partOfSpeech: "verb", category: "Perception", example: "Sie lauscht der Musik.", exampleEn: "She listens intently to the music." },

  // ─── Possession & Exchange ──────────────────────────────────────
  { german: "besitzen", english: "to own / to possess", partOfSpeech: "verb", category: "Possession", example: "Er besitzt ein großes Haus.", exampleEn: "He owns a large house." },
  { german: "behalten", english: "to keep", partOfSpeech: "verb", category: "Possession", example: "Du kannst das Buch behalten.", exampleEn: "You can keep the book." },
  { german: "verlieren", english: "to lose", partOfSpeech: "verb", category: "Possession", example: "Ich habe meinen Schlüssel verloren.", exampleEn: "I lost my key." },
  { german: "suchen", english: "to search / to look for", partOfSpeech: "verb", category: "Possession", example: "Ich suche meine Brille.", exampleEn: "I'm looking for my glasses." },
  { german: "sammeln", english: "to collect", partOfSpeech: "verb", category: "Possession", example: "Er sammelt Briefmarken.", exampleEn: "He collects stamps." },
  { german: "tauschen", english: "to exchange / to swap", partOfSpeech: "verb", category: "Possession", example: "Wollen wir die Plätze tauschen?", exampleEn: "Shall we swap seats?" },
  { german: "ausleihen", english: "to borrow / to lend", partOfSpeech: "verb", category: "Possession", example: "Kann ich mir das Buch ausleihen?", exampleEn: "Can I borrow the book?" },
  { german: "verschenken", english: "to give away", partOfSpeech: "verb", category: "Possession", example: "Sie verschenkt alte Kleidung.", exampleEn: "She gives away old clothes." },
  { german: "wegwerfen", english: "to throw away", partOfSpeech: "verb", category: "Possession", example: "Wirf das nicht weg!", exampleEn: "Don't throw that away!" },
  { german: "aufbewahren", english: "to store / to keep", partOfSpeech: "verb", category: "Possession", example: "Bewahre die Dokumente sicher auf.", exampleEn: "Store the documents safely." },
  { german: "entdecken", english: "to discover", partOfSpeech: "verb", category: "Possession", example: "Wir haben einen neuen Weg entdeckt.", exampleEn: "We discovered a new path." },
  { german: "verteilen", english: "to distribute", partOfSpeech: "verb", category: "Possession", example: "Sie verteilt die Geschenke.", exampleEn: "She distributes the gifts." },

  // ─── Change & Creation ──────────────────────────────────────────
  { german: "ändern", english: "to change / to alter", partOfSpeech: "verb", category: "Change", example: "Ich ändere meine Meinung.", exampleEn: "I'm changing my mind." },
  { german: "sich verändern", english: "to change (oneself)", partOfSpeech: "verb", category: "Change", example: "Die Stadt hat sich sehr verändert.", exampleEn: "The city has changed a lot." },
  { german: "verbessern", english: "to improve", partOfSpeech: "verb", category: "Change", example: "Ich möchte mein Deutsch verbessern.", exampleEn: "I want to improve my German." },
  { german: "verschlechtern", english: "to worsen", partOfSpeech: "verb", category: "Change", example: "Das Wetter verschlechtert sich.", exampleEn: "The weather is worsening." },
  { german: "zerstören", english: "to destroy", partOfSpeech: "verb", category: "Change", example: "Der Sturm hat das Dach zerstört.", exampleEn: "The storm destroyed the roof." },
  { german: "bauen", english: "to build", partOfSpeech: "verb", category: "Change", example: "Wir bauen ein Haus.", exampleEn: "We are building a house." },
  { german: "gestalten", english: "to design / to shape", partOfSpeech: "verb", category: "Change", example: "Sie gestaltet eine Website.", exampleEn: "She designs a website." },
  { german: "erstellen", english: "to create / to produce", partOfSpeech: "verb", category: "Change", example: "Ich erstelle einen Bericht.", exampleEn: "I'm creating a report." },
  { german: "ersetzen", english: "to replace", partOfSpeech: "verb", category: "Change", example: "Wir ersetzen die alten Fenster.", exampleEn: "We replace the old windows." },
  { german: "erweitern", english: "to expand / to extend", partOfSpeech: "verb", category: "Change", example: "Sie erweitern das Angebot.", exampleEn: "They expand the offering." },
  { german: "reduzieren", english: "to reduce", partOfSpeech: "verb", category: "Change", example: "Wir reduzieren den Preis.", exampleEn: "We reduce the price." },
  { german: "anpassen", english: "to adapt / to adjust", partOfSpeech: "verb", category: "Change", example: "Passen Sie die Einstellungen an.", exampleEn: "Adjust the settings." },
  { german: "umwandeln", english: "to convert / to transform", partOfSpeech: "verb", category: "Change", example: "Wir wandeln die Datei in PDF um.", exampleEn: "We convert the file to PDF." },
  { german: "malen", english: "to paint / to draw", partOfSpeech: "verb", category: "Change", example: "Das Kind malt ein Bild.", exampleEn: "The child paints a picture." },
  { german: "zeichnen", english: "to draw", partOfSpeech: "verb", category: "Change", example: "Er zeichnet ein Porträt.", exampleEn: "He draws a portrait." },
  { german: "basteln", english: "to do crafts / to tinker", partOfSpeech: "verb", category: "Change", example: "Die Kinder basteln Weihnachtskarten.", exampleEn: "The children make Christmas cards." },
  { german: "nähen", english: "to sew", partOfSpeech: "verb", category: "Change", example: "Sie näht ein Kleid.", exampleEn: "She sews a dress." },
  { german: "befestigen", english: "to attach / to fasten", partOfSpeech: "verb", category: "Change", example: "Befestige das Foto an der Wand.", exampleEn: "Attach the photo to the wall." },
  { german: "trennen", english: "to separate", partOfSpeech: "verb", category: "Change", example: "Wir trennen den Müll.", exampleEn: "We separate the trash." },
  { german: "mischen", english: "to mix / to blend", partOfSpeech: "verb", category: "Change", example: "Mische Rot und Blau.", exampleEn: "Mix red and blue." },

  // ─── Obligation & Permission ────────────────────────────────────
  { german: "erlauben", english: "to allow / to permit", partOfSpeech: "verb", category: "Obligation", example: "Meine Eltern erlauben mir das.", exampleEn: "My parents allow me to do that." },
  { german: "verbieten", english: "to forbid / to prohibit", partOfSpeech: "verb", category: "Obligation", example: "Rauchen ist hier verboten.", exampleEn: "Smoking is prohibited here." },
  { german: "zwingen", english: "to force / to compel", partOfSpeech: "verb", category: "Obligation", example: "Niemand zwingt dich dazu.", exampleEn: "Nobody forces you to do that." },
  { german: "verpflichten", english: "to obligate", partOfSpeech: "verb", category: "Obligation", example: "Der Vertrag verpflichtet uns.", exampleEn: "The contract obligates us." },
  { german: "empfehlen", english: "to recommend", partOfSpeech: "verb", category: "Obligation", example: "Ich empfehle dir dieses Restaurant.", exampleEn: "I recommend this restaurant to you." },
  { german: "raten", english: "to advise / to guess", partOfSpeech: "verb", category: "Obligation", example: "Ich rate dir, früh zu kommen.", exampleEn: "I advise you to come early." },
  { german: "sich weigern", english: "to refuse", partOfSpeech: "verb", category: "Obligation", example: "Er weigert sich, das zu tun.", exampleEn: "He refuses to do that." },
  { german: "gehorchen", english: "to obey", partOfSpeech: "verb", category: "Obligation", example: "Der Hund gehorcht seinem Besitzer.", exampleEn: "The dog obeys its owner." },
  { german: "einhalten", english: "to comply with / to keep", partOfSpeech: "verb", category: "Obligation", example: "Bitte halte die Regeln ein.", exampleEn: "Please comply with the rules." },
  { german: "verstoßen", english: "to violate / to break (a rule)", partOfSpeech: "verb", category: "Obligation", example: "Er verstößt gegen das Gesetz.", exampleEn: "He violates the law." },

  // ─── Abstract & Miscellaneous ───────────────────────────────────
  { german: "wählen", english: "to choose / to vote", partOfSpeech: "verb", category: "Abstract", example: "Ich wähle das rote Kleid.", exampleEn: "I choose the red dress." },
  { german: "dauern", english: "to last / to take (time)", partOfSpeech: "verb", category: "Abstract", example: "Wie lange dauert die Fahrt?", exampleEn: "How long does the trip take?" },
  { german: "passen", english: "to fit / to suit", partOfSpeech: "verb", category: "Abstract", example: "Die Schuhe passen mir nicht.", exampleEn: "The shoes don't fit me." },
  { german: "reichen", english: "to be enough / to hand", partOfSpeech: "verb", category: "Abstract", example: "Das Geld reicht nicht.", exampleEn: "The money isn't enough." },
  { german: "klappen", english: "to work out / to go well", partOfSpeech: "verb", category: "Abstract", example: "Hat alles geklappt?", exampleEn: "Did everything work out?" },
  { german: "stimmen", english: "to be correct / to vote", partOfSpeech: "verb", category: "Abstract", example: "Das stimmt.", exampleEn: "That's correct." },
  { german: "sich lohnen", english: "to be worthwhile", partOfSpeech: "verb", category: "Abstract", example: "Der Ausflug lohnt sich.", exampleEn: "The trip is worthwhile." },
  { german: "funktionieren", english: "to function / to work", partOfSpeech: "verb", category: "Abstract", example: "Das Gerät funktioniert nicht.", exampleEn: "The device doesn't work." },
  { german: "existieren", english: "to exist", partOfSpeech: "verb", category: "Abstract", example: "Das Problem existiert schon lange.", exampleEn: "The problem has existed for a long time." },
  { german: "passieren", english: "to happen", partOfSpeech: "verb", category: "Abstract", example: "Was ist passiert?", exampleEn: "What happened?" },
  { german: "geschehen", english: "to happen / to occur", partOfSpeech: "verb", category: "Abstract", example: "Es ist ein Unfall geschehen.", exampleEn: "An accident occurred." },
  { german: "gelingen", english: "to succeed", partOfSpeech: "verb", category: "Abstract", example: "Es ist mir gelungen.", exampleEn: "I succeeded." },
  { german: "scheitern", english: "to fail", partOfSpeech: "verb", category: "Abstract", example: "Das Projekt ist gescheitert.", exampleEn: "The project failed." },
  { german: "sich eignen", english: "to be suitable", partOfSpeech: "verb", category: "Abstract", example: "Das Buch eignet sich für Anfänger.", exampleEn: "The book is suitable for beginners." },
  { german: "abhängen", english: "to depend on", partOfSpeech: "verb", category: "Abstract", example: "Das hängt vom Wetter ab.", exampleEn: "That depends on the weather." },
  { german: "sich gewöhnen", english: "to get used to", partOfSpeech: "verb", category: "Abstract", example: "Ich gewöhne mich an das Klima.", exampleEn: "I'm getting used to the climate." },
  { german: "aushalten", english: "to endure / to bear", partOfSpeech: "verb", category: "Abstract", example: "Ich kann die Hitze nicht aushalten.", exampleEn: "I can't bear the heat." },
  { german: "vermeiden", english: "to avoid", partOfSpeech: "verb", category: "Abstract", example: "Vermeide unnötigen Stress.", exampleEn: "Avoid unnecessary stress." },
  { german: "aufgeben", english: "to give up", partOfSpeech: "verb", category: "Abstract", example: "Gib niemals auf!", exampleEn: "Never give up!" },
  { german: "anfangen", english: "to start / to begin", partOfSpeech: "verb", category: "Abstract", example: "Wann fängt der Kurs an?", exampleEn: "When does the course start?" },
  { german: "aufhören", english: "to stop / to cease", partOfSpeech: "verb", category: "Abstract", example: "Hör auf zu reden!", exampleEn: "Stop talking!" },
  { german: "fortsetzen", english: "to continue", partOfSpeech: "verb", category: "Abstract", example: "Wir setzen die Arbeit morgen fort.", exampleEn: "We continue the work tomorrow." },
  { german: "beenden", english: "to finish / to end", partOfSpeech: "verb", category: "Abstract", example: "Ich habe das Projekt beendet.", exampleEn: "I finished the project." },
  { german: "abbrechen", english: "to cancel / to abort", partOfSpeech: "verb", category: "Abstract", example: "Er bricht das Studium ab.", exampleEn: "He drops out of university." },
  { german: "verschieben", english: "to postpone / to move", partOfSpeech: "verb", category: "Abstract", example: "Wir verschieben das Treffen.", exampleEn: "We postpone the meeting." },
  { german: "sich bemühen", english: "to make an effort", partOfSpeech: "verb", category: "Abstract", example: "Ich bemühe mich, besser zu werden.", exampleEn: "I make an effort to get better." },
  { german: "sich beschäftigen", english: "to occupy oneself with", partOfSpeech: "verb", category: "Abstract", example: "Ich beschäftige mich mit dem Thema.", exampleEn: "I'm occupied with the topic." },
  { german: "gehören", english: "to belong to", partOfSpeech: "verb", category: "Abstract", example: "Das gehört nicht hierher.", exampleEn: "That doesn't belong here." },
  { german: "betragen", english: "to amount to", partOfSpeech: "verb", category: "Abstract", example: "Die Kosten betragen hundert Euro.", exampleEn: "The costs amount to one hundred euros." },
  { german: "beeinflussen", english: "to influence", partOfSpeech: "verb", category: "Abstract", example: "Das Wetter beeinflusst meine Stimmung.", exampleEn: "The weather influences my mood." },
  { german: "sich handeln um", english: "to be about / to concern", partOfSpeech: "verb", category: "Abstract", example: "Es handelt sich um ein Missverständnis.", exampleEn: "It's about a misunderstanding." },
  { german: "verwenden", english: "to use / to apply", partOfSpeech: "verb", category: "Abstract", example: "Verwende nur natürliche Zutaten.", exampleEn: "Use only natural ingredients." },
  { german: "benutzen", english: "to use", partOfSpeech: "verb", category: "Abstract", example: "Benutze den Aufzug.", exampleEn: "Use the elevator." },
  { german: "benötigen", english: "to require / to need", partOfSpeech: "verb", category: "Abstract", example: "Wir benötigen mehr Zeit.", exampleEn: "We need more time." },
  { german: "betreffen", english: "to concern / to affect", partOfSpeech: "verb", category: "Abstract", example: "Das betrifft uns alle.", exampleEn: "That affects us all." },
  { german: "verursachen", english: "to cause", partOfSpeech: "verb", category: "Abstract", example: "Der Regen verursacht Überschwemmungen.", exampleEn: "The rain causes floods." },
  { german: "lösen", english: "to solve / to loosen", partOfSpeech: "verb", category: "Abstract", example: "Wir lösen das Problem zusammen.", exampleEn: "We solve the problem together." },
  { german: "sicherstellen", english: "to ensure", partOfSpeech: "verb", category: "Abstract", example: "Stellen Sie sicher, dass alles fertig ist.", exampleEn: "Make sure everything is ready." },
  { german: "sich kümmern um", english: "to take care of", partOfSpeech: "verb", category: "Abstract", example: "Ich kümmere mich darum.", exampleEn: "I'll take care of it." },
  { german: "vorziehen", english: "to prefer", partOfSpeech: "verb", category: "Abstract", example: "Ich ziehe Tee vor.", exampleEn: "I prefer tea." },
  { german: "verzichten", english: "to do without / to forgo", partOfSpeech: "verb", category: "Abstract", example: "Ich verzichte auf Zucker.", exampleEn: "I do without sugar." },
  { german: "verschwinden", english: "to disappear", partOfSpeech: "verb", category: "Abstract", example: "Die Katze ist verschwunden.", exampleEn: "The cat has disappeared." },
  { german: "übertreiben", english: "to exaggerate", partOfSpeech: "verb", category: "Abstract", example: "Übertreib nicht so!", exampleEn: "Don't exaggerate so much!" },
  { german: "sich täuschen", english: "to be deceived / to be wrong", partOfSpeech: "verb", category: "Abstract", example: "Da täuschst du dich.", exampleEn: "You're wrong about that." },
  { german: "schützen", english: "to protect", partOfSpeech: "verb", category: "Abstract", example: "Wir müssen die Umwelt schützen.", exampleEn: "We must protect the environment." },
  { german: "verhindern", english: "to prevent", partOfSpeech: "verb", category: "Abstract", example: "Wir müssen das verhindern.", exampleEn: "We must prevent that." },
  { german: "sorgen für", english: "to take care of / to ensure", partOfSpeech: "verb", category: "Abstract", example: "Ich sorge für Ordnung.", exampleEn: "I ensure order." },
  { german: "darstellen", english: "to represent / to depict", partOfSpeech: "verb", category: "Abstract", example: "Das Bild stellt eine Landschaft dar.", exampleEn: "The picture depicts a landscape." },
  { german: "sich herausstellen", english: "to turn out", partOfSpeech: "verb", category: "Abstract", example: "Es stellte sich heraus, dass er recht hatte.", exampleEn: "It turned out that he was right." },
  { german: "stammen", english: "to originate / to come from", partOfSpeech: "verb", category: "Abstract", example: "Ich stamme aus Deutschland.", exampleEn: "I come from Germany." },
  { german: "wachsen", english: "to grow", partOfSpeech: "verb", category: "Abstract", example: "Die Firma wächst schnell.", exampleEn: "The company grows quickly." },
  { german: "steigern", english: "to increase / to boost", partOfSpeech: "verb", category: "Abstract", example: "Wir steigern die Produktion.", exampleEn: "We increase production." },
  { german: "sinken", english: "to decrease / to decline", partOfSpeech: "verb", category: "Abstract", example: "Die Zahl der Bewerber sinkt.", exampleEn: "The number of applicants is declining." },
];
